## 分布式系统 公司内部管理系统用 主程序 用于杰毅麦特
spring:
  application:
    name: igams-web
  redis:
    # Redis服务器地址
    host: localhost
    # Redis服务器连接密码（默认为空）
    password: 
  mail:
    host: smtp.163.com
    viewname: 杰毅生物
    protocol: smtp
    username: 3
    password: 3
postsql:
  datasource:
    username: zzENemN8d+Z1Ai08Lhz8Wg==
    password: 64V/GRnagrxCs51ypST5UA==
    url: E6Bxa5hFXjN+sYdjKG06wJ6uruQXMYDyGKDj1QuKRQ6ZvrxcsVf4CWk43k+qSLjG
sqlserver:
  gmds:
    username: ${sqlgmuser:sa}
    password: ${sqlgmpass:ufida123}
    #jdbc:sqlserver://192.168.1.130:1433;database=ahos";
    url: ${sqlgmurl:jdbc:sqlserver://172.100.100.253:1433;DatabaseName=UFDATA_001_2016}
    flag: 麦特
  ## flag 配置了，那么物料这边就会往相应数据库插入数据，gmds为麦特，  matridx 为其他三个数据库。 但请购等地方直接确认matridxds ，不确认flg
  ## 所以可以配置信息但不设置flg，这样物料就不会插入四次，请购这个也会正常
  matridxds:
    username: ${sqluser:sa}
    password: ${sqlpass:Ufida123}
    #jdbc:sqlserver://192.168.1.130:1433;database=ahos;user=sa;password=ahtec";
    url: ${sqlurl:jdbc:sqlserver://172.100.100.253:1433;DatabaseName=UFDATA_001_2016}
logging:
  level:
    com.matridx.igams.sample.dao.post: debug
    com.matridx.igams.common.dao.post: debug
    com.matridx.igams.production.dao.post: debug
    com.matridx.igams.research.dao.post: debug
    com.matridx.igams.web.dao.post: debug
    com.matridx.igams.dmp.dao.post: debug
    com.matridx.igams.wechat.dao.post: debug
    com.matridx.igams.production.dao.matridxsql: debug
    com.matridx.igams.experiment.dao.post: debug
    com.matridx.igams.warehouse.dao.post: debug
##角色切换配置： 0不支持切换，1支持切换
matridx:
  role:
    switch: 1
  exptype:
    limit: 500
  fileupload:
    prefix: 
    tempPath: /matridx/fileupload/temp/
    releasePath: /matridx/fileupload/release/
  file:
    ##文件导出存放路径
    exportFilePath: /matridx/download/
    ##文件保存路径前缀
    pathPrefix: 
    ##文件转换最大次数
    translimit: 5
  ftp:
    wordpath: /wordFile
    pdfpath: /pdfFile
    url: 172.100.100.253
    user: ftpuser
    pd: matridx
    port: 21
  ##钉钉
  dingtalk:
    ## 服务器对外端口
    callbackurl: https://medlab.matridx.com
    cropid: 0CR1anbOp44yaNHXFfUd4o4MnJ6YpMRQ/pfWGZ61XBU6a102ncLvt/TPJLzC3j1r
    ## 要求解密后为43位
    aeskey: meg2JLExn/OMMQCDJvaAvT812XJ11pKFLXM6LJqL1+GM5YLWGZZkyvVMNH3H7QNm
    ## 解密后随意
    token: 9HASPQHOnVmPR6TilCzcDKS2CtVYmm+DHgdv6DOhL/M=
    appkey: PPauxmG26deNt+gVNYdxaHSu6qP7ioprB+VBCBnxVYY=
    appsecret: Zr2WSS3BkFtEs5KfvtVoaQeXTiOMf89aJt1au+TE9WzoHsS/90J4L8hv0vICTscALKgF6tdabMCmLKt0Rs9gJTJVhPyCTTb2m8Ia5X4cJ9k=
    agentid: d+TLAXIXpmzUN0M2HR7C8Q==
    miniurl: dingtalk://dingtalkclient/action/open_micro_app?miniAppId=2021001102630915&version=1560993&agentId=213508707&pVersion=1&packageType=1&corpId=ding3afdff6046a29be5
    ## 跳转钉钉小程序路径
    jumpdingtalkurl: Lz0Qi39mDV9YbnhyI3+8xhciRl4pY5+eMLzG+soXtK1iy373PwQ04d6uT8EjVHNzN1/TmqvX+PxcICDIthwarcnkEW6oiX7nSZjSdrpIWFouz7TUB9Q+1GIIysJ26i0NO05sBV/mJHB40XeEMBVBtLT9WYEj+n3K8x3EAwP7tEOazDHlvtl4be1KjJ/R5VDqVMZZEvfDAQCLrY0XaqUXfKIIVdtFTEHf/klymWO10sM=
  ##语音识别
  audio:
    savepath: /matridx/audio/save/
    audiotype: ali       ##ali  baidu
    accessKeyId: 
    accessKeySecret: 
    appid: 
  wechat:
    menuurl: http://111.0.123.76:18081
    applicationurl: http://172.100.100.253:8081
    ## 送检发送请求查询 检测结果的地址
    inspectionurl: http://172.100.100.253:8081
    ## 统计外部地址
    externalurl: http://111.0.123.76:18081
  systemflg:
    logourl: /images/logoIn-biology.png
    icourl: /images/favicon-gm.ico
    title: 杰毅麦特OA
    watermark: 杰毅麦特
    systemname: 杰毅麦特
    ## 合同起始编码
    contractcode: GM
    ## 合同买方邮箱
    contractemail: pengtingting@matridx.com
    ## 定时任务是否执行 0：不执行  1：执行
    remindflg: 1
    ## 启动时根据标记redisreset判断是否进行redis数据的删除重新加入的操作, 1进行操作，0不进行操作
    redisreset: 0
  prefix:
    ## 分布式系统，主程序的地址
    igamsweb: /igams-web
    ## 如果本身为分布式子系统，则这个地方不为空，到时候会自动连接主程序prefix.igamsweb，如果未设置，则直接访问本身
    urlprefix: 
  rabbit:
    ## 系统信息同步时的标记，还需在rabbit下进行配置，使Routing key为sys.igams.jcsj.del能同时匹配到sys.igams.jcsj.del，sys.igams.jcsj.del.production
    ## 其中production就是这个flg标记
    flg: 
    ## 不同Web系统直接需要区分，否则rabbit消息很有可能被未知系统截取
    preflg: gm.
zuul:
  #需要忽略的头部信息，不在传播到其他服务
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
  routes:
    igams-cloud-matridx: /matridxigams/**
    igams-cloud-lab: /labigams/**