## 分布式系统 公司内部管理系统用 主程序 用于杰毅麦特
spring:
  application:
    name: igams-web
  redis:
    # Redis服务器地址
    host: redis
    # Redis服务器连接密码（默认为空）
    password: 
  rabbitmq:
    port: 5672
    #发送确认
    publisher-confirms: true
    #addresses: ${mqaddr:admin:matridx2019!@172.17.60.192:5672}
    host: ${mqhost:172.17.60.192}
    username: ${mqname:admin}
    password: ${mqpass:matridx2019!}
  mail:
    host: smtp.163.com
    viewname: 杰毅生物
    protocol: smtp
    username: 3
    password: 3
postsql:
  datasource:
    username: AEBrmFhq9gZ4Yeq+mogdzQ==
    password: DmnVklgEln/9NePegyMNig==
    url: E6Bxa5hFXjN+sYdjKG06wAqfeQK7rfwXaPGZO5j0ihx5D+FWf9P4+oPwV0AJRB9Z
sqlserver:
  gmds:
    username: C7PnCpt+ks/6vf8lMKVK/w==
    password: pYp3U6ckXgrmMnqj3TzLAQ==
    #jdbc:sqlserver://192.168.1.130:1433;database=ahos";
    url: 05rJvWC/dZNwL93RtuHWFL1gjbOKK4njiHtPS3xM/t++qoIvC+7EEzgD2O+Oo2KX9hwh9PEgRNg4FkJWqFgNbg==
    ##flag: 麦特
  matridxds:
    username: C7PnCpt+ks/6vf8lMKVK/w==
    password: pYp3U6ckXgrmMnqj3TzLAQ==
    #jdbc:sqlserver://192.168.1.130:1433;database=ahos;user=sa;password=ahtec";
    url: 05rJvWC/dZNwL93RtuHWFL1gjbOKK4njiHtPS3xM/t++qoIvC+7EEzgD2O+Oo2KX9hwh9PEgRNg4FkJWqFgNbg==
    flag: 生物
##角色切换配置： 0不支持切换，1支持切换
matridx:
  role:
    switch: 1
  exptype:
    limit: 500
  fileupload:
    prefix: 
    tempPath: /matridx/fileupload/temp/
    releasePath: /matridx/fileupload/release/
  file:
    ##文件导出存放路径
    exportFilePath: /matridx/download/
    ##文件保存路径前缀
    pathPrefix: 
    ##文件转换最大次数
    translimit: 5
  ftp:
    wordpath: /wordFile
    pdfpath: /pdfFile
    url: 172.17.60.177
    user: ftpuser
    pd: matridx
    port: 21
  ##钉钉
  dingtalk:
    ## 服务器对外端口
    callbackurl: http://company.matridx.com
    cropid: PAi6mqqSMLdnxhFqQOdG7dsZefVmxGWVEvq0JsEZips=
    ## 要求解密后为43位
    aeskey: meg2JLExn/OMMQCDJvaAvT812XJ11pKFLXM6LJqL1+GM5YLWGZZkyvVMNH3H7QNm
    ## 解密后随意
    token: 9HASPQHOnVmPR6TilCzcDKS2CtVYmm+DHgdv6DOhL/M=
    appkey: SjiVL+I3B6kEhRLZF4/FYb4nE6hsaQF5pzqRdFsSUFM=
    appsecret: Rebf6/oPXPP/H41hYBzQimFnVrm0vsQCzaXvIC7i8a9qcdocNErZDsK6ol+OHhAmet3/jn0VpbpqWm8QoL8jSzJVhPyCTTb2m8Ia5X4cJ9k=
    agentid: 667lPwpNVwmh3pV6LMNA6Q==
    miniurl: dingtalk://dingtalkclient/action/open_micro_app?miniAppId=2021001102630915&version=1560993&agentId=213508707&pVersion=1&packageType=1&corpId=ding3afdff6046a29be5
    ## 跳转钉钉小程序路径
    jumpdingtalkurl: Lz0Qi39mDV9YbnhyI3+8xhciRl4pY5+eMLzG+soXtK1iy373PwQ04d6uT8EjVHNzN1/TmqvX+PxcICDIthwarcnkEW6oiX7nSZjSdrpIWFouz7TUB9Q+1GIIysJ26i0NO05sBV/mJHB40XeEMBVBtLT9WYEj+n3K8x3EAwP7tEOazDHlvtl4be1KjJ/R5VDqVMZZEvfDAQCLrY0XaqUXfKIIVdtFTEHf/klymWO10sM=
    ##钉钉小程序 现主要用于扫码登录所使用
    miniappkey: kC6c7IjbNcf50IqGMq1aaj+XplQLqSod0auY/BU5mEg=
    miniappsecret: 2ZmEBEks6lVSZU2dtA8Mu1dYLcRa7Pku9ta/fQaV5SD7Nled58UFOZti9RShQH7/jvWqydyU1pKGwFQT9P+A2DJVhPyCTTb2m8Ia5X4cJ9k=  
  ##语音识别
  audio:
    savepath: /matridx/audio/save/
    audiotype: ali       ##ali  baidu
    #accessKeyId: ZY5umhS7CN9RRVKg1x3poKfc8IzB4TkAp0/GRS/sXYo=
    #accessKeySecret: YgFUZcqxPzLq286Nwmfj4BFfN+QbP4eu8EGl52g42tIyVYT8gk029pvCGuV+HCfZ
    #appid: L2rjGmuPzJ9xmSU0/9iyFA==
    accessKeyId: 
    accessKeySecret: 
    appid: 
  wechat:
    menuurl: http://172.17.60.190
    applicationurl: http://172.17.60.190
    ## 送检发送请求查询 检测结果的地址
    inspectionurl: http://172.17.60.190
    ## 统计外部地址
    externalurl: http://company.matridx.com
    ## 钉钉回调注册地址190
    registerurl: https://company.matridx.com
  systemflg:
    logourl: /images/logoIn-biology.png
    title: 杰毅生物OA
    watermark: 杰毅麦特
    systemname: 杰毅生物
    ## 合同起始编码
    contractcode: GM
    ## 合同买方邮箱
    contractemail: pengtingting@matridx.com
    ## 系统是否执行定时任务 0：不执行    null或者1 ：执行
    remindflg: 1
    ## 启动时根据标记redisreset判断是否进行redis数据的删除重新加入的操作, 1进行操作，0不进行操作
    redisreset: 1
  ## 现主要用于身份证扫码
  baidu:
    appkey: zn7Nv0cL9ronYbOMXGK0dSZ/l4v/pcLnUVSVLhEx8R4=
    secret: H2Zh1KK6LQoEM/lgt2KrdETv0qH0itW6f4v9czTHB7YyVYT8gk029pvCGuV+HCfZ
  ##U8账套名称
  accountSet:
    accountName: "001"
  prefix:
    ## 分布式系统，主程序的地址
    igamsweb: /igams-web
    ## 如果本身为分布式子系统，则这个地方不为空，到时候会自动连接主程序prefix.igamsweb，如果未设置，则直接访问本身
    urlprefix: 
  rabbit:
    ## 系统信息同步时的标记，还需在rabbit下进行配置，使Routing key为sys.igams.jcsj.del能同时匹配到sys.igams.jcsj.del，sys.igams.jcsj.del.production
    ## 其中production就是这个flg标记
    flg: 
    ## 不同Web系统直接需要区分，否则rabbit消息很有可能被未知系统截取
    preflg: main.
  operationflg:
    ## 是否保存到U8里 0：不保存  1 保存
    operationcode: 1
  ## 水印
  watermark:
    ## 是否单独运行
    standalone: true
    ## 是否要覆盖目标文件
    overwrite: true
    screenShot: true
    ## 文档转换配置
    languageDir: /xpdf-chinese-simplified
    pdfToolsCmd: /opt/openoffice.org3/program/soffice
    openOfficeLocation: /opt/openoffice.org3/program
    pdfConverter: openoffice
    ## 水印图片路径
    imagePath: /images/logo/
    ## 水印字  杰毅生物
    watermark: 天使关爱计划
    ## 水印字体大小
    watermarkFontsize: 20
    ## 水印横向间隔（A4）数目
    watermarkNumX: 2
    ## 水印纵向间隔（A4）数目
    watermarkNumY: 3
    ## 水印显示透明度
    watermarkFillOpacity: 0.3
    ## 水印显示倾斜角度
    watermarkRotation: 35
    ## 水印字体
    watermarkFontsizeForImage: 30
zuul:
  #需要忽略的头部信息，不在传播到其他服务
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
  routes:
    igams-cloud-matridx: /matridxigams/**
    igams-cloud-lab: /labigams/**
    igams-cloud-hunan: /hnigams/**
server:
  port: ${sport:8086}