## 分布式系统 公司内部管理系统用 主程序 用于杰毅麦特
spring:
  application:
    name: igams-web
  redis:
    # Redis服务器地址
    host: redis
    # Redis服务器连接密码（默认为空）
    password: Matridx2021!
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接端口
    port: 6379
  rabbitmq:
    port: 5672
    #发送确认
    publisher-confirms: true
    #addresses: ${mqaddr:admin:matridx2019!@172.17.60.192:5672}
    host: ${mqhost:172.17.60.192}
    username: ${mqname:admin}
    password: ${mqpass:matridx2019!}
  mail:
    host: smtp.163.com
    viewname: 杰毅生物
    protocol: smtp
    username: 3
    password: 3
  config:
    import: optional:configserver:${uri:http://172.17.60.192:8860}
postsql:
  datasource:
    username: AEBrmFhq9gZ4Yeq+mogdzQ==
    password: DmnVklgEln/9NePegyMNig==
    url: E6Bxa5hFXjN+sYdjKG06wAqfeQK7rfwXaPGZO5j0ihx5D+FWf9P4+oPwV0AJRB9Z
sqlserver:
  gmds:
    username: C7PnCpt+ks/6vf8lMKVK/w==
    password: pYp3U6ckXgrmMnqj3TzLAQ==
    #jdbc:sqlserver://192.168.1.130:1433;database=ahos";
    ##url: 05rJvWC/dZNwL93RtuHWFL1gjbOKK4njiHtPS3xM/t++qoIvC+7EEzgD2O+Oo2KXXUwM1uj944lMCopLJDbKpQ==
    url: 05rJvWC/dZNwL93RtuHWFL1gjbOKK4njiHtPS3xM/t++qoIvC+7EEzgD2O+Oo2KXoGt8ORPBn6I3cenjs9CiuPCzkjmgcpT6Ntn5R9XiZEW9a/q8mGcIBJR6mtfl7eQ8nbOZF3oz6FJ+fUs2lf8BKQ==
    ##flag: 麦特
  matridxds:
    username: C7PnCpt+ks/6vf8lMKVK/w==
    password: pYp3U6ckXgrmMnqj3TzLAQ==
    #jdbc:sqlserver://192.168.1.130:1433;database=ahos;user=sa;password=ahtec";
    ##url: 05rJvWC/dZNwL93RtuHWFL1gjbOKK4njiHtPS3xM/t++qoIvC+7EEzgD2O+Oo2KXXUwM1uj944lMCopLJDbKpQ==
    url: 05rJvWC/dZNwL93RtuHWFL1gjbOKK4njiHtPS3xM/t++qoIvC+7EEzgD2O+Oo2KXoGt8ORPBn6I3cenjs9CiuPCzkjmgcpT6Ntn5R9XiZEW9a/q8mGcIBJR6mtfl7eQ8nbOZF3oz6FJ+fUs2lf8BKQ==
    flag: 生物
##角色切换配置： 0不支持切换，1支持切换
matridx:
  role:
    switch: 1
  exptype:
    limit: 500
  fileupload:
    prefix: 
    tempPath: /matridx/fileupload/temp/
    releasePath: /matridx/fileupload/release/
  file:
    ##文件导出存放路径
    exportFilePath: /matridx/download/
    ##文件保存路径前缀
    pathPrefix: 
    ##文件转换最大次数
    translimit: 5
  ftp:
    wordpath: /wordFile
    pdfpath: /pdfFile
    url: 172.17.60.177
    user: ftpuser
    pd: matridx
    port: 21
  ##钉钉
  dingtalk:
    ## 服务器对外端口
    callbackurl: https://company.matridx.com
    cropid: PAi6mqqSMLdnxhFqQOdG7dsZefVmxGWVEvq0JsEZips=
    ## 要求解密后为43位 原：meg2JLExn/OMMQCDJvaAvT812XJ11pKFLXM6LJqL1+GM5YLWGZZkyvVMNH3H7QNm
    ## Base加密前 matridx2020!HangZhou201@a123123 加密后去掉两个= CNvHhFpvwRH3WaVkArJm+twhLsBkrF6Uke3I2598OzqDZiUfpSYk+VdlzPLQGzle
    aeskey: meg2JLExn/OMMQCDJvaAvT812XJ11pKFLXM6LJqL1+GM5YLWGZZkyvVMNH3H7QNm
    ## 解密后随意
    token: 9HASPQHOnVmPR6TilCzcDKS2CtVYmm+DHgdv6DOhL/M=
    appkey: VLjcLsXLBqdq2VNg/1dHyePmCZS3ldtgPmRAaUXWevU=
    appsecret: yYMpuKIW6oB7g2q5tWuzGCZWZ36nxK6eqckVxXG7il7FMQmXYVeg7awzHZUoRtU2LeUo7pn111Pdq/XpcAouNTJVhPyCTTb2m8Ia5X4cJ9k=
    agentid: f58T3paimyGbD12fzBIgSA==
    ##miniurl: dingtalk://dingtalkclient/action/open_micro_app?miniAppId=2021001102630915&version=1560993&agentId=213508707&pVersion=1&packageType=1&corpId=ding3afdff6046a29be5
    ## 跳转钉钉小程序路径
    jumpdingtalkurl: Lz0Qi39mDV9YbnhyI3+8xhciRl4pY5+eMLzG+soXtK1iy373PwQ04d6uT8EjVHNz84DQUkLhuH9AIUKNQLyjjMqfbcQdiCnT+VDUXF7m82guz7TUB9Q+1GIIysJ26i0NauK5n/6kOGM6ZfZyjR9yOed294rmQV2NCYW7ej8zRi4y/ydIDnScydU5F6Oa7nrEWK7+FaEt+vRlxOn/gMXDhCt+eA0pOQ1kuDQGvZDPFxw=
    ##钉钉小程序 现主要用于扫码登录所使用 杰毅OA
    miniappkey: VLjcLsXLBqdq2VNg/1dHyePmCZS3ldtgPmRAaUXWevU=
    miniappsecret: yYMpuKIW6oB7g2q5tWuzGCZWZ36nxK6eqckVxXG7il7FMQmXYVeg7awzHZUoRtU2LeUo7pn111Pdq/XpcAouNTJVhPyCTTb2m8Ia5X4cJ9k=
  ##语音识别
  audio:
    savepath: /matridx/audio/save/
    audiotype: ali       ##ali  baidu
    #accessKeyId: ZY5umhS7CN9RRVKg1x3poKfc8IzB4TkAp0/GRS/sXYo=
    #accessKeySecret: YgFUZcqxPzLq286Nwmfj4BFfN+QbP4eu8EGl52g42tIyVYT8gk029pvCGuV+HCfZ
    #appid: L2rjGmuPzJ9xmSU0/9iyFA==
    accessKeyId: 
    accessKeySecret: 
    appid: 
  wechat:
    menuurl: https://service.matridx.com
    ##http://172.17.60.190
    applicationurl: https://company.matridx.com
    ## 送检发送请求查询 检测结果的地址 http://172.17.60.190
    inspectionurl: https://company.matridx.com
    ## 统计外部地址 http://124.160.226.74:8092
    externalurl: https://company.matridx.com
    ## 自定义外部地址，191服务器设置为190访问地址，190服务器设置为191地址
    customizeurl: https://medlab.matridx.com
    ## 钉钉回调注册地址190
    registerurl: https://company.matridx.com
  systemflg:
    logourl: /images/logoIn-biology-b.png
    title: 杰毅生物OA
    watermark: 恺思
    systemname: 恺思
    ## 合同起始编码
    contractcode: MD
    ## 合同买方邮箱
    contractemail: pengtingting@matridx.com
    ## 定时任务是否执行 0：不执行  1：执行
    remindflg: 1
    ## 启动时根据标记redisreset判断是否进行redis数据的删除重新加入的操作, 1进行操作，0不进行操作
    redisreset: 1
  ## cookie所存放的域名
  cookie:
    domain: matridx.com
    cookiekey: company.matridx.com
  ## 跳转的认证中心，如果用本系统，则不用设置，否则是 https://medlab.matridx.com/
  loginCentre:
    url: 
  ## 现主要用于身份证扫码
  baidu:
    appkey: zn7Nv0cL9ronYbOMXGK0dSZ/l4v/pcLnUVSVLhEx8R4=
    secret: H2Zh1KK6LQoEM/lgt2KrdETv0qH0itW6f4v9czTHB7YyVYT8gk029pvCGuV+HCfZ
  ##U8账套名称
  accountSet:
    accountName: "001"
  prefix:
    ## 分布式系统，主程序的地址
    igamsweb: /igams-web
    ## 如果本身为分布式子系统，则这个地方不为空，到时候会自动连接主程序prefix.igamsweb，如果未设置，则直接访问本身
    urlprefix: 
  rabbit:
    ## 系统信息同步时的标记，还需在rabbit下进行配置，使Routing key为sys.igams.jcsj.del能同时匹配到sys.igams.jcsj.del，sys.igams.jcsj.del.production
    ## 其中production就是这个flg标记
    flg: 
    ## 不同Web系统直接需要区分，否则rabbit消息很有可能被未知系统截取
    preflg: 
    ##是否发送rabbit标记(用户信息等)     1：发送 主要用于 product 和系统用户这边
    configflg: 1
    ##是否接收rabbit标记(用户信息等)     1：接收   
    receiveflg: 0
    ##体系同步是否发送    1：发送
    systemconfigflg: 0
    ##体系同步是否接收    1：接收
    systemreceiveflg: 0
  operationflg:
    ## 是否保存到U8里 0：不保存  1 保存
    operationcode: 1
  blanklist:
    host: 172.17.60.190,company.matridx.com
  # 网页端的AI助手配置
  aliyunBL:
    appId: QrHuoz9OXMdWTaaI5enoUiL0MNklF/ToWPITUocDa6wyVYT8gk029pvCGuV+HCfZ
    apiKey: 8hKq/Z3GmhTgFDZ25sFWv2ghoJT2TxRyGdNm69mm0zUG8O1oUTP6RvohZDdsA5Z/
zuul:
  #需要忽略的头部信息，不在传播到其他服务
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
  routes:
    # product模块下的杰毅生物的分布式，主要包括物料，请购，合同，仓库，文件
    igams-cloud-matridx: /matridxigams/**
    # product模块下的医检所的分布式，主要包括物料，请购，合同，仓库，文件
    igams-cloud-lab: /labigams/**
    # product模块下的湖南检验所的分布式，主要包括物料，请购，合同，仓库，文件
    igams-cloud-hunan: /hnigams/**
    # product模块下的恺思的分布式，主要包括物料，请购，合同，仓库，文件
    igams-cloud-ks: /ksigams/**
    # product模块下的杰毅基因的分布式，主要包括物料，请购，合同，仓库，文件
    igams-cloud-gene: /geneigams/**
    # hrm模块下的杰毅生物的分布式，主要包括人事管理等
    hrm-cloud-matridx: /matridxhrm/**
    # hrm模块下的医检所的分布式，主要包括人事管理等
    hrm-cloud-lab: /labhrm/**
    # hrm模块下的湖南检验所的分布式，主要包括人事管理等
    hrm-cloud-hunan: /hnhrm/**
    # hrm模块下的湖南检验所的分布式，主要包括人事管理等
    hrm-cloud-ks: /kshrm/**
## 打印sql
logging:
  config: classpath:/log4j-prod.xml
server:
  port: ${sport:8086}