spring:
  application:
    name: lwj-igams-web
  redis:
    ## Redis服务器地址
    host: 127.0.0.1
    ## Redis服务器连接密码（默认为空）
    password:
    port: 10001
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    viewname: 杰毅生物
    protocol: smtp
    username:
    password:
  config:
    import: optional:configserver:${uri:http://172.17.60.192:8760}
  rabbitmq:
    addresses: ${mqaddr:admin:matridx2019!@172.17.60.188:5672}
    host: ${mqhost:172.17.52.95}
    username: ${mqname:admin}
    password: ${mqpass:xksr0911.}
    virtualHost: ${mqvirtualhost:/}
    port: ${mqport:9003}
    report:
      host: 172.17.52.95
      port: 5672
      username: admin2
      password: xksr0911.
postsql:
  datasource:
    driverClassName: org.postgresql.Driver
    #    username: AEBrmFhq9gZ4Yeq+mogdzQ==
    #    password: MrTVAg0Sn2SfQZE/HUZ5IQ==
    #    url: E6Bxa5hFXjN+sYdjKG06wOCsp1DH0IZMJUquJ5w+uYPtmycHAIPwBJtbT3XsGaP4
    username: AEBrmFhq9gZ4Yeq+mogdzQ==
    password: DmnVklgEln/9NePegyMNig==
    url: E6Bxa5hFXjN+sYdjKG06wJ4rdyisoRVLdb2Upibi5aMnD4Uo6p8JvqzZOWVzceZa
    validationQuery: SELECT 1
#sqlserver:
#  gmds:
#    username: C7PnCpt+ks/6vf8lMKVK/w==
#    password: MrTVAg0Sn2SfQZE/HUZ5IQ==
#    #jdbc:sqlserver://192.168.1.130:1433;database=ahos";
#    url: 05rJvWC/dZNwL93RtuHWFJQs3FWGb6huklwUgf54u52+qoIvC+7EEzgD2O+Oo2KXoGt8ORPBn6I3cenjs9CiuPCzkjmgcpT6Ntn5R9XiZEW9a/q8mGcIBJR6mtfl7eQ8nbOZF3oz6FJ+fUs2lf8BKQ==
#  matridxds:
#    username: C7PnCpt+ks/6vf8lMKVK/w==
#    password: MrTVAg0Sn2SfQZE/HUZ5IQ==
#    #jdbc:sqlserver://192.168.1.130:1433;database=ahos";
#    url: 05rJvWC/dZNwL93RtuHWFJQs3FWGb6huklwUgf54u52+qoIvC+7EEzgD2O+Oo2KXoGt8ORPBn6I3cenjs9CiuPCzkjmgcpT6Ntn5R9XiZEW9a/q8mGcIBJR6mtfl7eQ8nbOZF3oz6FJ+fUs2lf8BKQ==
#    validationQuery: SELECT 1
#    # 针对当前系统物料需要保存的表来配置，其它业务不做判断
#    flag: 生物
##角色切换配置： 0不支持切换，1支持切换
matridx:
  ## cookie所存放的域名
  cookie:
    domain: 172.17.52.95
  ## 跳转的认证中心，如果用本系统，则不用设置，否则是 https://medlab.matridx.com/
  loginCentre:
    url:
  sf:
    ##顺丰平台顾客编码
    client_code: JYSWJW
    ##顺丰平台校验码
    check_word: x303u6lj59tqMKjBtEqqZjHCCgYqH40w
    ##顺丰生产环境地址
    call_url_prod: https://sfapi.sf-express.com/std/service
  role:
    switch: 1
  exptype:
    limit: 500
  fileupload:
    prefix:
    tempPath: /matridx/fileupload/temp/
    releasePath: /matridx/fileupload/release/
    createFolder:
  file:
    ##文件导出存放路径
    exportFilePath: /matridx/download/
    ##文件保存路径前缀
    pathPrefix:
    ##文件转换最大次数
    translimit: 5
  ftp:
    wordpath: /wordFile
    pdfpath: /pdfFile
    url: 172.17.60.177
    user: ftpuser
    pd: matridx
    port: 21
  ##钉钉
  dingtalk:
    appkey: oRNu8t5t3biW9wtBpq73ixnDfmq5vzEiYsWPreR6oBY=
    appsecret: rhqtmujOx/rMCLSt41jJ/q2o4eRTKwzBwuLGGV9HfDnCPhvjcw9QyRipKj2wZAGBLSyP3SRJyj9gsyARpBUUmTJVhPyCTTb2m8Ia5X4cJ9k=
    agentid: t2FsObI5DRqDRF28JeEDDA==
    token: 9HASPQHOnVmPR6TilCzcDKS2CtVYmm+DHgdv6DOhL/M=
    miniappkey: oRNu8t5t3biW9wtBpq73ixnDfmq5vzEiYsWPreR6oBY=
    miniappsecret: rhqtmujOx/rMCLSt41jJ/q2o4eRTKwzBwuLGGV9HfDnCPhvjcw9QyRipKj2wZAGBLSyP3SRJyj9gsyARpBUUmTJVhPyCTTb2m8Ia5X4cJ9k=
    matridx:
    ## 跳转钉钉小程序路径
    jumpdingtalkurl: Lz0Qi39mDV9YbnhyI3+8xhciRl4pY5+eMLzG+soXtK1iy373PwQ04d6uT8EjVHNz84DQUkLhuH9AIUKNQLyjjOjiS9ArxppJr5f0HUXjzpcuz7TUB9Q+1GIIysJ26i0NQwKe8hEu+soXw/g/x4sS1ud294rmQV2NCYW7ej8zRi4y/ydIDnScydU5F6Oa7nrEWK7+FaEt+vRlxOn/gMXDhCt+eA0pOQ1kuDQGvZDPFxw=
    ## 服务器对外端口
    #callbackurl: http://101.68.81.93
    cropid: PAi6mqqSMLdnxhFqQOdG7dsZefVmxGWVEvq0JsEZips=
    aeskey: 0t88uYEVcsN+rSL4kAfb3nMU5jf9VEX+6Bs1L49He+bmU4J5wqxCB8r1lHr8GfRg
    spaceId: PinppUR6gcJqUlPlyBOF6w==
    userId: eORAtKW87NvJWnZ0AvThdRSnBN8uIHILL056TUO3iYg=
  ##语音识别
  audio:
    savepath: /matridx/audio/save/
    audiotype: ali       ##ali  baidu
    #accessKeyId: ZY5umhS7CN9RRVKg1x3poKfc8IzB4TkAp0/GRS/sXYo=
    #accessKeySecret: YgFUZcqxPzLq286Nwmfj4BFfN+QbP4eu8EGl52g42tIyVYT8gk029pvCGuV+HCfZ
    #appid: L2rjGmuPzJ9xmSU0/9iyFA==
    accessKeyId: Fyj2gzZ9dU2Xw2lxrxfBQzJVhPyCTTb2m8Ia5X4cJ9k=
    accessKeySecret: AElsGW16bjaYU2qiTVqwIOzhlmPt5FpxGq6c5XKsKHM=
    appid: vo88lJAbqCj5CzwR8/u4cTJVhPyCTTb2m8Ia5X4cJ9k=
  wechat:
    ##菜单推送微信的地址
    menuurl: http://localhost:8085
    ##钉钉查看访问的路径
    applicationurl: http://172.17.52.95:8087
    ## 下载文件地址
    downloadUrl: /ws/common/downloadDocFile
    ## 送检发送请求查询 检测结果的地址
    inspectionurl: http://localhost:8085
    ## 统计外部地址
    externalurl: http://101.68.81.90:8093
    ## 钉钉回调注册地址190
    registerurl: http://172.17.60.190
    appid: 1
    secret: 2
    paternerkey:
    mchid:
  baidu:
    appkey:
    secret:
  alipay:
    ## 应用ID,您的APPID，收款账号既是您的APPID对应支付宝账号
    app_id:
    ## 应用ID,您的APPID，收款账号既是您的APPID对应支付宝账号
    #uid: 2088102177450010
    ## 商户私钥，您的PKCS8格式RSA2私钥
    alipay_private_key:
    ## 支付宝公钥,查看地址：https://openhome.alipay.com/platform/keyManage.htm 对应APPID下的支付宝公钥。
    alipay_public_key:
    ## 服务器异步通知页面路径  需http://格式的完整路径，不能加?id=123这类自定义参数
    notify_url: http://101.68.81.90:8099/wechat/pay/aliPayNotify
    ## 页面跳转同步通知页面路径 需http://格式的完整路径，不能加?id=123这类自定义参数
    return_url: http://101.68.81.90:8099/wechat/pay/aliPayComplete
    ## 签名方式
    alipay_sign_type: RSA2
    ## 支付宝网关
    gatewayUrl:
  ##阿里云短信
  aliyunSms:
    accessKeyId: GB3oWZjNqD177DTTdjKelzJVhPyCTTb2m8Ia5X4cJ9k=
    accessSecret: jDp6CBmApWl/XLtobsbblOs9lXhNO+2cV7zK3SuWHEc=
    signName: 杰毅检验
    signNameMatridx: 杰毅生物
    templateCode: SMS_170840387
    templateCodeXgyy: SMS_230420216
    templateCodeXgbg: SMS_230420609
  systemflg:
    logourl: /images/logoIn-biology.png
    watermark: 杰毅麦特
    systemname: 杰毅生物
  prefix:
    urlprefix:
    title: 杰毅生物OA
    igamsweb: /gxj-igams-web
  rabbit:
    ## 系统信息同步时的标记，还需在rabbit下进行配置，使Routing key为sys.igams.jcsj.del能同时匹配到sys.igams.jcsj.del，sys.igams.jcsj.del.production
    ## 其中production就是这个flg标记
    flg: .gxjprod
    preflg: matridx.tx.
    ##系统用户同步是否接受
    receiveflg: 0
    configflg: 0
    ##体系同步是否发送
    systemconfigflg: 0
    ##体系同步是否接受
    systemreceiveflg: 0
zuul:
  ##需要忽略的头部信息，不在传播到其他服务
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
  routes:
    lwj-igams-production: /matridxprod/**
    yjw-igams-production: /yjwprod/**
    lsy-igams-production: /lsyprod/**
    zh-igams-production: /zhprod/**
    gxj-igams-production: /gxjprod/**
    igams-cloud-lab: /labigams/**
server:
  port: 8087
#ssl:

#key-store: server.keystore

#key-alias: tomcat

#enabled: true

#key-store-password: matridx2019

#key-store-type: JKS