spring:
  application:
    name: lwj-igams-web
  redis:
    ## Redis服务器地址
    host: localhost
    ## Redis服务器连接密码（默认为空）
    password: 
    timeout: 1000
    port: 6379
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    viewname: 杰毅生物
    protocol: smtp
    username: 1
    password: 2
  rabbitmq:
    #port: 5672
    #address: ${mqaddr:admin:matridx2019!@60.191.45.243:5672}
    port: ${mqport:5672}
    #发送确认
    publisher-confirms: true
    host: ${mqhost:172.17.60.190}
    username: ${mqname:admin}
    password: ${mqpass:matridx2019!}
  config:
    import: optional:configserver:${uri:http://172.17.60.195:8760}
  cloud:
    config:
      ## 文件名称
      name: ${name:igams-production}
      ## 环境名称 配置文件会访问/{label}/{name}-{profiles}.yml,同时默认会取/{label}/{name}.yml 内容
      profile: ${profile:dev}
      uri: ${uri:http://172.17.60.193:8760}
      label: ${label:master}
      #discovery:
        #enabled: true
        #serviceId: config-server
    client:
      ipAddress: ${ipaddr:localhost}
    # https://www.jianshu.com/p/84f0667fa277 网络断连恢复引起的
    stream:
      default:
        group: ${spring.application.name}-${spring.cloud.client.ipAddress}-${server.port}
      rabbit:
        bindings:
          springCloudBusInput:
            consumer:
              # 队列声明重试次数 
              queue-declaration-retries: 2000
              # 重试间隔(ms)
              recovery-interval: 5000
              # 为true时，使用‘group’作为配置刷新队列的名称
              queue-name-group-only: true
postsql:
  datasource:
    username: AEBrmFhq9gZ4Yeq+mogdzQ==
    password: DmnVklgEln/9NePegyMNig==
    ## 172.17.60.191
    url: E6Bxa5hFXjN+sYdjKG06wMmkx+qqYfkCWPjuE2NhcPRZkpPdeTsAGVx3A+K775IF
    ## 172.17.60.190  124.160.226.75:19032
    #url: E6Bxa5hFXjN+sYdjKG06wMmkx+qqYfkCWPjuE2NhcPTE5f+tlAGOVPPNm8XBLfcj
    ## 172.17.60.189
    #url: E6Bxa5hFXjN+sYdjKG06wIghU01vQ9b6L6SijT9iGu4nD4Uo6p8JvqzZOWVzceZa
    ## 172.17.60.188  60.191.45.243:15432
    #url: E6Bxa5hFXjN+sYdjKG06wMObC3LI7FELOADo/+O8WH3tdhYTAh0la8hV2lZsSVSe
    ## 101.37.247.249
    #url: E6Bxa5hFXjN+sYdjKG06wMD2DA7457ThLcyaMeSx4sjGQazTc0qFRoUcmnKe9j1W
sqlserver:
  gmds:
  matridxds:
    driverClassName: org.postgresql.Driver
    username: 
    password: 
    #jdbc:sqlserver://192.168.1.130:1433;database=ahos";
    url: 
##角色切换配置： 0不支持切换，1支持切换
matridx:
  role:
    switch: 1
  basictype:
    file: config/comm/basicType.xml
  imptype:
    file: config/comm/config-import.xml
  exptype:
    file: config/comm/config-export.xml
    limit: 500
  fileupload:
    prefix: 
    tempPath: /matridx/fileupload/temp/
    releasePath: /matridx/fileupload/release/
  file:
    ##文件导出存放路径
    exportFilePath: /matridx/download/
    ##文件保存路径前缀
    pathPrefix: 
    ##文件转换最大次数
    translimit: 5
  ftp:
    wordpath: /wordFile
    pdfpath: /pdfFile
    url: 172.17.60.177
    user: root
    pd: 112
    port: 22
  dingtalk:
    ## 服务器对外端口
    callbackurl: https://medlab.matridx.com
    cropid: #PAi6mqqSMLdnxhFqQOdG7dsZefVmxGWVEvq0JsEZips=
    ## 要求解密后为43位
    aeskey: #meg2JLExn/OMMQCDJvaAvT812XJ11pKFLXM6LJqL1+GM5YLWGZZkyvVMNH3H7QNm
    ## 解密后随意
    token: #9HASPQHOnVmPR6TilCzcDKS2CtVYmm+DHgdv6DOhL/M=
    appkey: #SjiVL+I3B6kEhRLZF4/FYb4nE6hsaQF5pzqRdFsSUFM=
    appsecret: #Rebf6/oPXPP/H41hYBzQimFnVrm0vsQCzaXvIC7i8a9qcdocNErZDsK6ol+OHhAmet3/jn0VpbpqWm8QoL8jSzJVhPyCTTb2m8Ia5X4cJ9k=
    agentid: #667lPwpNVwmh3pV6LMNA6Q==
    ## 跳转钉钉小程序路径
    jumpdingtalkurl: #Lz0Qi39mDV9YbnhyI3+8xhciRl4pY5+eMLzG+soXtK1iy373PwQ04d6uT8EjVHNzN1/TmqvX+PxcICDIthwarcnkEW6oiX7nSZjSdrpIWFouz7TUB9Q+1GIIysJ26i0NO05sBV/mJHB40XeEMBVBtLT9WYEj+n3K8x3EAwP7tEOazDHlvtl4be1KjJ/R5VDqVMZZEvfDAQCLrY0XaqUXfKIIVdtFTEHf/klymWO10sM=
  ##语音识别
  audio:
    savepath: /matridx/audio/save/
    audiotype: ali       ##ali  baidu
    #accessKeyId: ZY5umhS7CN9RRVKg1x3poKfc8IzB4TkAp0/GRS/sXYo=
    #accessKeySecret: YgFUZcqxPzLq286Nwmfj4BFfN+QbP4eu8EGl52g42tIyVYT8gk029pvCGuV+HCfZ
    #appid: L2rjGmuPzJ9xmSU0/9iyFA==
    accessKeyId: Fyj2gzZ9dU2Xw2lxrxfBQzJVhPyCTTb2m8Ia5X4cJ9k=
    accessKeySecret: AElsGW16bjaYU2qiTVqwIOzhlmPt5FpxGq6c5XKsKHM=
    appid: vo88lJAbqCj5CzwR8/u4cTJVhPyCTTb2m8Ia5X4cJ9k=
  ##阿里云语音
  aliyunVoice: 
    accessKeyId: 
    accessSecret: 
  wechat:
    appid: CFnxXuOD6PhHWP+u8kHi9KeejrbjyDGLT/E/2gL4DEk=
    secret: HH0lmrK8Ys3sL2TWD1xXD8V45zWlpF1LceyOEfUZ8GMyVYT8gk029pvCGuV+HCfZ
    token: tknUOBawaYs4o/3HvH6KIw==
    menuurl: http://service.matridx.com
    ##钉钉查看访问的路径
    applicationurl: https://medlab.matridx.com
    ## 送检发送请求查询 检测结果的地址
    inspectionurl: http://172.17.60.226:8000
    ## 统计外部地址
    externalurl: https://medlab.matridx.com
  systemflg:
    logourl: /images/logoIn-biology-b.png
    watermark: 杰毅生物
    ## 定时任务是否执行 0：不执行  1：执行
    remindflg: 0
    ## 启动时根据标记redisreset判断是否进行redis数据的删除重新加入的操作, 1进行操作，0不进行操作
    redisreset: 1
  ##U8账套名称
  accountSet:
    accountName: 001
  prefix:
    urlprefix: 
    igamsweb: /igams-web
  rabbit:
    ## 系统信息同步时的标记，还需在rabbit下进行配置，使Routing key为sys.igams.jcsj.del能同时匹配到sys.igams.jcsj.del，sys.igams.jcsj.del.production
    ## 其中production就是这个flg标记
    flg: .hkweb
zuul:
  ##需要忽略的头部信息，不在传播到其他服务
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
  routes:
    lwj-igams-production: /matridxprod/**
    yjw-igams-production: /yjwprod/**
    lsy-igams-production: /lsyprod/**
    zh-igams-production: /zhprod/**
    igams-cloud-lab: /labigams/**
    igams-cloud-matridx: /matridxigams/**
server:
  port: ${sport:8086}