## 分布式系统 公司内部管理系统用 主程序 用于杰毅麦特
spring:
  ## druid配置
  datasource:
    ## 连接池最小连接数量
    minIdle: 5
    ## 连接池最大连接数量
    maxActive: 100
    ## 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
    initialSize: 10
    ## 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
    maxWait: 60000
    ## 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒;有两个含义：1) Destroy线程会检测连接的间隔时间 2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
    timeBetweenEvictionRunsMillis: 60000
    ## 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    ## 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    testWhileIdle: true
    ## 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    testOnBorrow: false
    ## 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false
    ## 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql5.5以下的版本中没有PSCache功能，建议关闭掉。5.5及以上版本有PSCache，建议开启。
    poolPreparedStatements: true
    ## 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
    maxPoolPreparedStatementPerConnectionSize: 100
    ## Druid的监控统计功能:属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：
    #监控统计用的filter:stat
    #日志用的filter:slf4j
    #防御SQL注入的filter:wall
    filters: config,stat,slf4j
    ## 连接数据库的额外参数 
    connectionProperties: 3000;
    ## 缺省多个DruidDataSource的监控数据是各自独立的，在Druid-0.2.17版本之后，支持配置公用监控数据，
    useGlobalDataSourceStat: true
    ## druid的登录用户名
    druidLoginName: admin
    ## druid的登录密码
    druidPassword: 1234
    ## 超过时间限制是否回收
    removeAbandoned: true
    ## 超过时间限制多长，单位是毫秒 ，180000毫秒=3分钟
    removeAbandonedTimeout: 180000
  application:
    name: igams-web-ezgene
  redis:
    # Redis服务器地址
    host: redis
    # Redis服务器连接密码（默认为空）
    password: Matridx2021!
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器连接端口
    port: 6379
  rabbitmq:
    port: 5672
    #发送确认
    publisher-confirms: true
    #addresses: ${mqaddr:admin:matridx2019!@172.17.60.185:5672}
    host: ${mqhost:172.17.60.185}
    username: ${mqname:admin}
    password: ${mqpass:matridx2019!}
  mail:
    host: smtp.163.com
    viewname: 杰毅生物
    protocol: smtp
    username: 3
    password: 3
  config:
    import: optional:configserver:${uri:http://172.17.60.192:8860}
  #spring boot自带的tomcat限制了上传图片的大小，为1M
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 2000MB
postsql:
  datasource:
    username: AEBrmFhq9gZ4Yeq+mogdzQ==
    password: DmnVklgEln/9NePegyMNig==
    url: E6Bxa5hFXjN+sYdjKG06wAqfeQK7rfwXaPGZO5j0ihx5D+FWf9P4+oPwV0AJRB9Z
sqlserver:
  gmds:
    username: C7PnCpt+ks/6vf8lMKVK/w==
    password: pYp3U6ckXgrmMnqj3TzLAQ==
    #jdbc:sqlserver://192.168.1.130:1433;database=ahos";
    ##url: 05rJvWC/dZNwL93RtuHWFL1gjbOKK4njiHtPS3xM/t++qoIvC+7EEzgD2O+Oo2KX7BCdYkmT2GB74TNRcG7Q3w==
    url: 05rJvWC/dZNwL93RtuHWFL1gjbOKK4njiHtPS3xM/t++qoIvC+7EEzgD2O+Oo2KXpZ9bIMU71RkYmgvEPXNXuPCzkjmgcpT6Ntn5R9XiZEW9a/q8mGcIBJR6mtfl7eQ8nbOZF3oz6FJ+fUs2lf8BKQ==
    ##flag: 麦特
  matridxds:
    username: C7PnCpt+ks/6vf8lMKVK/w==
    password: pYp3U6ckXgrmMnqj3TzLAQ==
    #jdbc:sqlserver://192.168.1.130:1433;database=ahos;user=sa;password=ahtec";
    ##url: 05rJvWC/dZNwL93RtuHWFL1gjbOKK4njiHtPS3xM/t++qoIvC+7EEzgD2O+Oo2KX7BCdYkmT2GB74TNRcG7Q3w==
    url: 05rJvWC/dZNwL93RtuHWFL1gjbOKK4njiHtPS3xM/t++qoIvC+7EEzgD2O+Oo2KXpZ9bIMU71RkYmgvEPXNXuPCzkjmgcpT6Ntn5R9XiZEW9a/q8mGcIBJR6mtfl7eQ8nbOZF3oz6FJ+fUs2lf8BKQ==
    flag: 生物
##角色切换配置： 0不支持切换，1支持切换
matridx:
  role:
    switch: 1
  exptype:
    limit: 500
  fileupload:
    prefix: 
    tempPath: /matridx/fileupload/temp/
    releasePath: /matridx/fileupload/release/
  file:
    ##文件导出存放路径
    exportFilePath: /matridx/download/
    ##文件保存路径前缀
    pathPrefix: 
    ##文件转换最大次数
    translimit: 5
  ftp:
    wordpath: /wordFile
    pdfpath: /pdfFile
    url: 172.17.60.177
    user: ftpuser
    pd: matridx
    port: 21
  ##钉钉
  dingtalk:
    ## 服务器对外端口
    callbackurl: https://ezgene.matridx.com
    ## 易速
    cropid: V+PkjclGojVyvr2Kd3sics7EkTGhIC6THv1K3I6rues6a102ncLvt/TPJLzC3j1r
    ## 要求解密后为43位 原：meg2JLExn/OMMQCDJvaAvT812XJ11pKFLXM6LJqL1+GM5YLWGZZkyvVMNH3H7QNm
    ## Base加密前 matridx2020!HangZhou201@a123123 加密后去掉两个= CNvHhFpvwRH3WaVkArJm+twhLsBkrF6Uke3I2598OzqDZiUfpSYk+VdlzPLQGzle
    aeskey: meg2JLExn/OMMQCDJvaAvT812XJ11pKFLXM6LJqL1+GM5YLWGZZkyvVMNH3H7QNm
    ## 解密后随意
    token: VwlWoQ1TjA/6guYS7p5g1b+hm2hwowkBuQRMXpOE2/UyVYT8gk029pvCGuV+HCfZ
    appkey: chaPuR6MUw4/nqeaCwXJg5RCHbkHB49MH96qdarTVzU=
    appsecret: Qw7h7cZGyPLCgNCfinuzFBoyoZOUtYZ1zSc3X5YZ7bDPjVlhx7V5tf0jKRCgLLmn8B5x3ZZORfhJgi3gxtf7ETJVhPyCTTb2m8Ia5X4cJ9k=
    agentid: h/kpR+Aw3wvvj/qFC+khJA==
    ##miniurl: dingtalk://dingtalkclient/action/open_micro_app?miniAppId=2021001102630915&version=1560993&agentId=213508707&pVersion=1&packageType=1&corpId=ding3afdff6046a29be5
    ## 跳转钉钉小程序路径
    jumpdingtalkurl: Lz0Qi39mDV9YbnhyI3+8xhciRl4pY5+eMLzG+soXtK1iy373PwQ04d6uT8EjVHNz84DQUkLhuH9AIUKNQLyjjDwoDYn+Uc906EdeFfIP4Xwuz7TUB9Q+1GIIysJ26i0NrQu80m8JS1lS7DzQ1Dc87Od294rmQV2NCYW7ej8zRi4y/ydIDnScydU5F6Oa7nrEpRlo1A0tb1qXquCeWLzuQ8MNMgMAyXdM84q30m7XH/fOWFMXF6taLM9TXnksbzFa
    ##钉钉小程序 现主要用于扫码登录所使用 杰毅OA
    miniappkey: chaPuR6MUw4/nqeaCwXJg5RCHbkHB49MH96qdarTVzU=
    miniappsecret: Qw7h7cZGyPLCgNCfinuzFBoyoZOUtYZ1zSc3X5YZ7bDPjVlhx7V5tf0jKRCgLLmn8B5x3ZZORfhJgi3gxtf7ETJVhPyCTTb2m8Ia5X4cJ9k=
  ##语音识别
  audio:
    savepath: /matridx/audio/save/
    audiotype: ali       ##ali  baidu
    #accessKeyId: ZY5umhS7CN9RRVKg1x3poKfc8IzB4TkAp0/GRS/sXYo=
    #accessKeySecret: YgFUZcqxPzLq286Nwmfj4BFfN+QbP4eu8EGl52g42tIyVYT8gk029pvCGuV+HCfZ
    #appid: L2rjGmuPzJ9xmSU0/9iyFA==
    accessKeyId: 
    accessKeySecret: 
    appid: 
  wechat:
    menuurl: https://service.matridx.com
    ##http://172.17.60.190
    applicationurl: https://ezgene.matridx.com
    ## 送检发送请求查询 检测结果的地址 http://172.17.60.190
    inspectionurl: https://ezgene.matridx.com
    ## 统计外部地址 http://124.160.226.74:8092
    externalurl: https://ezgene.matridx.com
    ## 自定义外部地址，191服务器设置为190访问地址，190服务器设置为191地址
    customizeurl: https://ezgene.matridx.com
    ## 钉钉回调注册地址190 易速这边因为是主站，则不需要这个
    registerurl: 
  systemflg:
    logourl: /images/logoIn-biology-b.png
    title: 易速微控OA
    watermark: 易速
    systemname: 易速
    ## 合同起始编码
    contractcode: YS
    ## 合同买方邮箱
    contractemail: pengtingting@matridx.com
    ## 启动时根据标记redisreset判断是否进行redis数据的删除重新加入的操作, 1进行操作，0不进行操作
    redisreset: 1
  ## 现主要用于身份证扫码
  baidu:
    appkey: zn7Nv0cL9ronYbOMXGK0dSZ/l4v/pcLnUVSVLhEx8R4=
    secret: H2Zh1KK6LQoEM/lgt2KrdETv0qH0itW6f4v9czTHB7YyVYT8gk029pvCGuV+HCfZ
  ##U8账套名称
  accountSet:
    accountName: "015"
  prefix:
    ## 分布式系统，主程序的地址
    igamsweb: /igams-web-ezgene
    ## 如果本身为分布式子系统，则这个地方不为空，到时候会自动连接主程序prefix.igamsweb，如果未设置，则直接访问本身
    urlprefix: 
  rabbit:
    ## 系统信息同步时的标记，还需在rabbit下进行配置，使Routing key为sys.igams.jcsj.del能同时匹配到sys.igams.jcsj.del，sys.igams.jcsj.del.production
    ## 其中production就是这个flg标记
    flg: 
    ## 不同Web系统直接需要区分，否则rabbit消息很有可能被未知系统截取  ez.
    preflg: 
    ##是否发送rabbit标记(用户信息等)     1：发送 主要用于 product 和系统用户这边
    configflg: 0
    ##是否接收rabbit标记(用户信息等)     1：接收   
    receiveflg: 0
    ##体系同步是否发送    1：发送
    systemconfigflg: 0
    ##体系同步是否接收    1：接收
    systemreceiveflg: 0
  ## cookie所存放的域名
  cookie:
    domain: matridx.com
  ## 跳转的认证中心，如果用本系统，则不用设置，否则是 https://medlab.matridx.com/
  loginCentre:
    url: 
  ## 打算废弃2022-10-20 ,需要合并到 matridx.rabbit.configflg 和 receiveflg
  rabbitflg:
    ##是否发送rabbit标记     1：发送 主要用于 product 和系统用户这边
    configflg: 0
    ##是否接收rabbit标记     1：接收
    receiveflg: 0
  operationflg:
    ## 是否保存到U8里 0：不保存  1 保存
    operationcode: 1
  blanklist:
    host: 172.17.60.185,ezgene.matridx.com,60.191.45.244,124.160.226.76
## 打印sql
logging:
  config: classpath:/log4j-ezgene.xml
server:
  port: ${sport:8086}