spring:
  application:
    name: igams-web
  session:
    #session存储类型
    store-type: redis
    #设置session超时时间
    timeout: 2000
  #redis:
    #redis的地址
    #host: 127.0.0.1
    #redis的端口
    #port: 6379
  ## druid配置
  datasource:
    ## 连接池最小连接数量
    minIdle: 5
    ## 连接池最大连接数量
    maxActive: 200
    ## 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
    initialSize: 10
    ## 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
    maxWait: 60000
    ## 设置数据库执行最大时间，当设置不足时会报 PSQLException: An I/O error occurred while sending to the backend.
    socketTimeout: 60000
    ## 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒;有两个含义：1) Destroy线程会检测连接的间隔时间 2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
    timeBetweenEvictionRunsMillis: 60000
    ## 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    ## 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    testWhileIdle: true
    ## 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    testOnBorrow: true
    ## 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false
    ## 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql5.5以下的版本中没有PSCache功能，建议关闭掉。5.5及以上版本有PSCache，建议开启。
    poolPreparedStatements: true
    ## 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
    maxPoolPreparedStatementPerConnectionSize: 100
    ## Druid的监控统计功能:属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：
    #监控统计用的filter:stat
    #日志用的filter:slf4j
    #防御SQL注入的filter:wall
    filters: config,stat,slf4j
    ## 连接数据库的额外参数 
    connectionProperties: 3000;
    ## 缺省多个DruidDataSource的监控数据是各自独立的，在Druid-0.2.17版本之后，支持配置公用监控数据，
    useGlobalDataSourceStat: true
    ## druid的登录用户名
    druidLoginName: admin
    ## druid的登录密码
    druidPassword: 1234
    ## 超过时间限制是否回收
    removeAbandoned: true
    ## 超过时间限制多长，单位是毫秒 ，180000毫秒=3分钟
    removeAbandonedTimeout: 180000
  thymeleaf:
    #prefix: classpath*:/static/
    suffix: .html
    encoding: UTF-8
    cache: false
  #resources:
    #“spring.mvc.static-path-pattern”用于阐述HTTP请求地址，而“spring.resources.static-locations”则用于描述静态资源的存放位置。
    #资源映射地址为classpath:/content/
    #static-locations: classpath*:/
  #mvc:
    #资源映射路径为/static/**
    #static-path-pattern: /**
  #缓存管理
  cache:
    ehcache:
      config: classpath:config/ehcache/ehcache.xml
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 172.17.60.191
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: Matridx_2022!
    pool:
            # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
            # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
            # 连接池中的最大空闲连接
      max-idle: 8
            # 连接池中的最小空闲连接
      min-idle: 0
        # 连接超时时间（毫秒） 中时间设置不能为0
    timeout: 5000
  #spring boot自带的tomcat限制了上传图片的大小，为1M
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  #消息队列
  rabbitmq:
    port: 5672
    #发送确认
    publisher-confirms: true
    #addresses: ${mqaddr:matridx:matridx2019!@101.37.247.249:5672}
    host: ${mqhost:101.37.247.249}
    username: ${mqname:admin}
    password: ${mqpass:matridx2019!}
    #virtual-host: /
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true     # 是否开启消费者重试（为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息）
          max-attempts: 5   # 最大重试次数
          max-interval: 20000   # 重试最大间隔时间
          initial-interval: 2000  # 重试初始间隔时间
          # 重试间隔*乘子得出下次重试间隔  2s  4s  8s  16s  此处16s>10s  走10s
          multiplier: 2 # 间隔时间乘子，间隔时间*乘子=下一次的间隔时间，最大不能超过设置的最大间隔时间
    report:
      port: ${reportport:9003}
      #发送确认
      publisher-confirms: true
      host: ${reporthost:101.37.247.249}
      username: ${reportname:rabbit_matridx}
      password: ${reportpass:matridx2020!}
  mq2:
    host: ${mqhost2:101.37.247.249}
    port: ${mqport2:5672}
    username: ${mqname2:admin}
    password: ${mqpass2:matridx2019!}
    ##发送确认
    publisher-confirms: true
    sleeptime: ${mqtime2:10000}
  mail:
    default-encoding: UTF-8
    host: smtp.matridx.com
    viewname: 杰毅生物
    protocol: smtp
    username: lctj@matridx.com
    password: jytj123@
    #mail.smtp.timeout:邮件smtp时间限制,单位毫秒
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 120000
          writetimeout: 120000
        smtps:
          connectiontimeout: 5000
          timeout: 120000
          writetimeout: 120000
  smtp: 
    connectiontimeout: 5000
    timeout: 120000
    writetimeout: 120000
    auth: true
    starttls: 
      enable: true
      required: true
  config:
    import: optional:configserver:${uri:http://172.17.60.101:8960}
postsql:
  datasource:
    driverClassName: org.postgresql.Driver
    username: AEBrmFhq9gZ4Yeq+mogdzQ==
    password: DmnVklgEln/9NePegyMNig==
    url: E6Bxa5hFXjN+sYdjKG06wCVRVtUpZbWq5tAcg4sXjnQnD4Uo6p8JvqzZOWVzceZa
    #E6Bxa5hFXjN+sYdjKG06wCVRVtUpZbWq5tAcg4sXjnQnD4Uo6p8JvqzZOWVzceZa
    validationQuery: SELECT 1 
sqlserver:
  gmds:
    username: C7PnCpt+ks/6vf8lMKVK/w==
    password: pYp3U6ckXgrmMnqj3TzLAQ==
    #jdbc:sqlserver://192.168.1.130:1433;database=ahos";
    ##url: 05rJvWC/dZNwL93RtuHWFL1gjbOKK4njiHtPS3xM/t++qoIvC+7EEzgD2O+Oo2KXXUwM1uj944lMCopLJDbKpQ==
    url: 05rJvWC/dZNwL93RtuHWFL1gjbOKK4njiHtPS3xM/t++qoIvC+7EEzgD2O+Oo2KXoGt8ORPBn6I3cenjs9CiuPCzkjmgcpT6Ntn5R9XiZEW9a/q8mGcIBJR6mtfl7eQ8nbOZF3oz6FJ+fUs2lf8BKQ==
    ##flag: 麦特
  matridxds:
    username: C7PnCpt+ks/6vf8lMKVK/w==
    password: pYp3U6ckXgrmMnqj3TzLAQ==
    #jdbc:sqlserver://192.168.1.130:1433;database=ahos;user=sa;password=ahtec";
    ##url: 05rJvWC/dZNwL93RtuHWFL1gjbOKK4njiHtPS3xM/t++qoIvC+7EEzgD2O+Oo2KXXUwM1uj944lMCopLJDbKpQ==
    url: 05rJvWC/dZNwL93RtuHWFL1gjbOKK4njiHtPS3xM/t++qoIvC+7EEzgD2O+Oo2KXoGt8ORPBn6I3cenjs9CiuPCzkjmgcpT6Ntn5R9XiZEW9a/q8mGcIBJR6mtfl7eQ8nbOZF3oz6FJ+fUs2lf8BKQ==
    flag: 生物
mysql:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: DHKQ6lsioogOgVKx8M0fhQ==
    password: 3nXPvsTM3gB3gOlLwTEGRA==
    url: FTgiIv8O4oUmb5oXHTFXURPq4s3qmez9Pf9qRU0LtrGbuu0hgZKkCpihLplVu6exfR3M6JTpKwjqWyUTP8Dp1wBAa5hYavYGeGHqvpqIHc0=
    validationQuery: SELECT 1
druid:
  stat:
    ## 连接数据库的额外参数 
    slowSqlMillis: 3000
    mergeSql: true
security:
  oauth2:
    resource:
      #将我们的资源拦截的过滤器运行顺序放到第3个执行,也就是在oauth2的认证服务器后面执行
      filter-order: 3
# 打印sql
logging:
  level:
    com.matridx.igams.sample.dao.post: debug
    com.matridx.igams.common.dao.post: debug
    com.matridx.igams.production.dao.post: debug
    com.matridx.igams.warehouse.dao.post: debug
    com.matridx.igams.production.dao.matridxsql: debug
    com.matridx.igams.research.dao.post: debug
    com.matridx.igams.web.dao.post: debug
    com.matridx.igams.dmp.dao.post: debug
    com.matridx.igams.wechat.dao.post: debug
    com.matridx.igams.experiment.dao.post: debug
    com.matridx.igams.finance.dao.financesql: debug
    com.matridx.localization.dao.post: debug
    #com.matridx.igams.web.dao.matridxsql: debug
    org.springframework.security.oauth2.provider.token.store: debug
  config: classpath:/log4j2_back.xml
##myibatis 拦截配置
sql:
  interceptor:
    pagesqlid: .*getPaged*.*
    dialect: postgresql
##角色切换配置： 0不支持切换，1支持切换
matridx:
  role:
    switch: 1
  basictype:
    file: config/comm/basicType.xml
  imptype:
    file: config/comm/config-import.xml
  exptype:
    file: config/comm/config-export.xml
    limit: 500
  fileupload:
    prefix: 
    tempPath: /matridx/fileupload/temp/
    releasePath: /matridx/fileupload/release/
  file:
    ##文件导出存放路径
    exportFilePath: /matridx/download/
    ##文件保存路径前缀
    pathPrefix: 
    ##文件转换最大次数
    translimit: 5
    ##pooling导出路径
    poolingExportFilePath: /matridx/pooling/
  ftp:
    wordpath: /wordFile
    pdfpath: /pdfFile
    #url: 172.17.50.35
    url: 172.17.60.177
    user: ftpuser
    pd: matridx
    port: 21
  ## 天隆对接
  ftpPcr:
    addr: 60.191.45.245
    port: 7821
    username: abs
    password: 123456
  ##钉钉
  dingtalk:
    ## 服务器对外端口
    callbackurl: https://medlab.matridx.com
    cropid: PAi6mqqSMLdnxhFqQOdG7dsZefVmxGWVEvq0JsEZips=
    ## 要求解密后为43位
    aeskey: meg2JLExn/OMMQCDJvaAvT812XJ11pKFLXM6LJqL1+GM5YLWGZZkyvVMNH3H7QNm
    ## 解密后随意
    token: 9HASPQHOnVmPR6TilCzcDKS2CtVYmm+DHgdv6DOhL/M=
    ## appkey 配置的是 工作提醒的
    appkey: SjiVL+I3B6kEhRLZF4/FYb4nE6hsaQF5pzqRdFsSUFM=
    appsecret: Rebf6/oPXPP/H41hYBzQimFnVrm0vsQCzaXvIC7i8a9qcdocNErZDsK6ol+OHhAmet3/jn0VpbpqWm8QoL8jSzJVhPyCTTb2m8Ia5X4cJ9k=
    agentid: 667lPwpNVwmh3pV6LMNA6Q==
    ##miniurl: dingtalk://dingtalkclient/action/open_micro_app?miniAppId=2021001102630915&version=1560993&agentId=213508707&pVersion=1&packageType=1&corpId=ding3afdff6046a29be5
    ## 跳转钉钉小程序路径
    jumpdingtalkurl: Lz0Qi39mDV9YbnhyI3+8xhciRl4pY5+eMLzG+soXtK1iy373PwQ04d6uT8EjVHNzN1/TmqvX+PxcICDIthwarcnkEW6oiX7nSZjSdrpIWFouz7TUB9Q+1GIIysJ26i0NSPd7HfBpROxF6cbxK08YLLT9WYEj+n3K8x3EAwP7tEOazDHlvtl4be1KjJ/R5VDqVMZZEvfDAQCLrY0XaqUXfKIIVdtFTEHf/klymWO10sM=
    ##钉钉小程序 现主要用于扫码登录所使用
    miniappkey: kC6c7IjbNcf50IqGMq1aaj+XplQLqSod0auY/BU5mEg=
    miniappsecret: 2ZmEBEks6lVSZU2dtA8Mu1dYLcRa7Pku9ta/fQaV5SD7Nled58UFOZti9RShQH7/jvWqydyU1pKGwFQT9P+A2DJVhPyCTTb2m8Ia5X4cJ9k=
    ## 北京分公司
    #appkey-bj: PZueHmO2ZnYUFf96M1EC8HAyb18XqvdSwHoZGeO8b8A=
    #appsecret-bj: I5BjffVVeVXBrQihdkeXDmfdbpJLXyAzeB6ACMX3EB8BcWXNKXq7MxIlfGjfBsYw+YDiAQoiCwhnlIzlqrNYaTJVhPyCTTb2m8Ia5X4cJ9k=
    ## 杭州分公司
    #appkey-hz: PIP2DUi92R4G8av2Zt2CYkm6QNV0XdICEQ4O0kmz2X8=
    #appsecret-hz: o8GL4UhxaP2DvCWgyIdiKRxHXpcEH9uFrZKbrI/kSTwQa3yAFJDBijx0y7Uc9kpQVZPTrbvstWCRUdY69qKN2TJVhPyCTTb2m8Ia5X4cJ9k=
  ##语音识别
  audio:
    savepath: /matridx/audio/save/
    audiotype: ali       ##ali  baidu
    #accessKeyId: ZY5umhS7CN9RRVKg1x3poKfc8IzB4TkAp0/GRS/sXYo=
    #accessKeySecret: YgFUZcqxPzLq286Nwmfj4BFfN+QbP4eu8EGl52g42tIyVYT8gk029pvCGuV+HCfZ
    #appid: L2rjGmuPzJ9xmSU0/9iyFA==
    accessKeyId: Fyj2gzZ9dU2Xw2lxrxfBQzJVhPyCTTb2m8Ia5X4cJ9k=
    accessKeySecret: AElsGW16bjaYU2qiTVqwIOzhlmPt5FpxGq6c5XKsKHM=
    appid: vo88lJAbqCj5CzwR8/u4cTJVhPyCTTb2m8Ia5X4cJ9k=
  wechat:
    menuurl: https://service.matridx.com
    ##http://172.17.60.191
    applicationurl: https://medlab.matridx.com
    ## 送检发送请求查询 检测结果的地址,生物信息系统
    inspectionurl: http://172.17.60.226:8000
    ## 统计外部地址
    externalurl: https://medlab.matridx.com
    ## 送检销售周报微信发送模板ID
    kpi_templateid: KbjP9S5hWiKDUWtH_LWKefDy4eFpi-XC6Hi7D5oEuSg
    ## 样本状态异常时发送的微信模板ID
    ybzt_templateid: _rJRqBD-c_HetxZBo0LoooBZECFpgG5XVKPM31eTRKk
    ## 自定义外部地址，191服务器设置为190访问地址，190服务器设置为191地址
    customizeurl: https://company.matridx.com
    ## 钉钉回调注册地址190
    registerurl: https://company.matridx.com
  ##阿里云短信
  aliyunSms: 
    accessKeyId: GB3oWZjNqD177DTTdjKelzJVhPyCTTb2m8Ia5X4cJ9k=
    accessSecret: jDp6CBmApWl/XLtobsbblOs9lXhNO+2cV7zK3SuWHEc=
    signName: 杰毅医检
    signNameMatridx: 杰毅生物
    templateCode: SMS_170840387
    ##预约成功短信
    templateCodeXgyy: SMS_236565506
    ##报告发出短信
    templateCodeXgbg: SMS_235794581
    ##预约成功后的预约码短信
    templateCodeXglj: SMS_235794552
  ##阿里云语音
  aliyunVoice: 
    accessKeyId: CVqhZf8gqRy01VGeY31vSPOc+Bs8yZb346jGGojXUU0=
    accessSecret: g/RkqNoVt/AR9MEhsZ4FlbvxMQiSLCGt4vaKv9w8km4=
  ## 现主要用于身份证扫码
  baidu:
    appkey: zn7Nv0cL9ronYbOMXGK0dSZ/l4v/pcLnUVSVLhEx8R4=
    secret: H2Zh1KK6LQoEM/lgt2KrdETv0qH0itW6f4v9czTHB7YyVYT8gk029pvCGuV+HCfZ
  systemflg:
    logourl: /images/logoIn-biology-b.png
    title: 杰毅医检OA
    watermark: 杰毅生物
    systemname: 杰毅生物
    ## 定时任务是否执行 0：不执行  1：执行
    remindflg: ${remindflg:0}
    ## 启动时根据标记redisreset判断是否进行redis数据的删除重新加入的操作, 1进行操作，0不进行操作
    redisreset: ${redisreset:0}
  ## cookie所存放的域名
  cookie:
    domain: matridx.com
    cookiekey: pathogen.matridx.com
  ## 跳转的认证中心，如果用本系统，则不用设置，否则是 https://medlab.matridx.com/
  loginCentre:
    url: 
  prefix:
    ## 分布式系统，主程序的地址
    igamsweb: /igams-web
    ## 如果本身为分布式子系统，则这个地方不为空，到时候会自动连接主程序prefix.igamsweb，如果未设置，则直接访问本身
    urlprefix: 
    production: 
    warehouse: 
  rabbit:
    ## 系统信息同步时的标记，还需在rabbit下进行配置，使Routing key为sys.igams.jcsj.del能同时匹配到sys.igams.jcsj.del，sys.igams.jcsj.del.production
    ## 其中production就是这个flg标记
    flg: 
    ## 不同Web系统直接需要区分，否则rabbit消息很有可能被未知系统截取
    preflg: 
    ##是否发送rabbit标记(用户信息等)     1：发送 主要用于 product 和系统用户这边
    configflg: 0
    ##是否接收rabbit标记(用户信息等)     1：接收   
    receiveflg: 0
    ##体系同步是否发送    1：发送
    systemconfigflg: 0
    ##体系同步是否接收    1：接收
    systemreceiveflg: 0
    ##sse 长连接，这个标记用于区分是哪一个服务器的
    ssekey: .pathogenBack
  operationflg:
    ## 是否保存到U8里 0：不保存  1 保存
    operationcode: 0
  ## 水印
  watermark:
    ## 是否单独运行
    standalone: true
    ## 是否要覆盖目标文件
    overwrite: true
    screenShot: true
    ## 文档转换配置
    languageDir: /xpdf-chinese-simplified
    pdfToolsCmd: /opt/openoffice.org3/program/soffice
    openOfficeLocation: /opt/openoffice.org3/program
    pdfConverter: openoffice
    ## 水印图片路径
    imagePath: /images/logo/
    ## 水印字  杰毅生物
    watermark: 天使关爱计划
    ## 水印字体大小
    watermarkFontsize: 20
    ## 水印横向间隔（A4）数目
    watermarkNumX: 2
    ## 水印纵向间隔（A4）数目
    watermarkNumY: 3
    ## 水印显示透明度
    watermarkFillOpacity: 0.3
    ## 水印显示倾斜角度
    watermarkRotation: 35
    ## 水印字体
    watermarkFontsizeForImage: 30
  sf:
    ##顺丰平台顾客编码
    client_code: JYSWJW
    ##顺丰平台校验码
    check_word: x303u6lj59tqMKjBtEqqZjHCCgYqH40w
    ##顺丰生产环境地址
    call_url_prod: https://sfapi.sf-express.com/std/service
  #京东物流 Token 一年需要更新一次 当前是 2023-03-10
  jingdong:
    appSecret: c9431790cc7844a0addf888ba9573b98
    appKey: c40b1bce312d4eff951f4bd1c7beb79a
    serverUrl: https://api.jdl.com
    customerCode: 021K1407284
    accessToken:  a2c279b980534d9997b1e6ce238b8503
    refreshToken:  d108448759174db4a354facec46b2bb2
  #新冠上报地址
  reportSubmit:
    ##健康平台批次服务号
    pc_address: http://192.26.64.134:8889/SJCJHQRWHJKQ/PCRWHHQQ
    ##健康平台单次服务号
    dc_address: http://192.26.64.134:8889/SJCJHQRWHJKQ/HQDCRWHQ
    ##健康平台上传服务号
    data_submit: http://192.26.64.134:8889/SJCJSJSCJKQ/SJSCQ
    #22位机构编码
    health_organ: 330110PDY10181417P1202
    #接入系统编码
    health_domain: 3301000143
    #采集结果接收服务编码
    receive_code: JYCJJGHCCJ:HZJYCJJGHCFW
    cjsj_address: http://192.26.64.134:8889/HSJCCJXXSCFWZSJK/HSJCCJXXSCZSFW
    cjsj_code: FWCJSJCJ:HSJCCJXXSCZSFW
    #报告机构
    organization_name: 杭州杰毅医学检验实验室有限公司
  #橄榄枝健康
  glzhealth:
    ##履约确认时调用对方的地址
    appointmentfinishurl: http://localhost:8086/ws/ganlanzhi
  #阿里健康
  alihealth:
    appSecret: 17cc7a528439a07a63b8c662c3df8f5a
    appKey: 33460000
    serverUrl: https://eco.taobao.com/router/rest
    merchantAesKey: WwYaE9eLbGw5B9Un
  # 杏和系统配置文件（配置文件的matridx下）--
  xinghe:
    # 调用凭证
    ticket: 8eaadf17e7b76a650455a5d6d1105fff
    url: http://118.178.255.230:9001/XingHeAreaService.asmx
    wsdlurl: http://118.178.255.230:9001/XingHeAreaService.asmx?WSDL
    # 检测机构
    hospitalservice: 33A038
  qianmai:
    url: https://lims20foreign.cmlabs.com.cn
    entrustHosCode: 杰毅
    usercode: jieyi
    password: Abc123,.,.
  henuo:
    url: https://a.ldrmed.com:4432/api
    account: 103
    password: abcd1234
    userType: 3
    entrustHosCode: 103
  # 艾迪康系统对接
  aidikang:
    url: https://dataexchange.adicon.com.cn:9281
    newurl: https://lego-vip.adicon.com.cn
    businessclass: ADC_BC0050
    username: A2023Jecszth.cd
    password: C2yp1e1504c98fb1baHcc1.b5387n
  #毓璜顶医院对接  http://123.130.112.90:8030/OutSideService.asmx?WSDL
  yuhuangding:
    wsdlurl: http://123.130.112.90:8032/OutSideService.asmx?WSDL
  blanklist:
    host: 172.17.60.191,medlab.matridx.com,60.191.45.242,60.191.45.245,124.160.226.75,124.160.226.74
  openMq2: true
  # 网页端的AI助手配置
  aliyunBL:
    appId: Ocxh6OqyZdeGwBOiLFc44VTlRp/gjHS8lOUxXmU/TfkyVYT8gk029pvCGuV+HCfZ
    apiKey: 8hKq/Z3GmhTgFDZ25sFWv2ghoJT2TxRyGdNm69mm0zUG8O1oUTP6RvohZDdsA5Z/
zuul:
  #需要忽略的头部信息，不在传播到其他服务
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
  routes:
    igams-cloud-matridx: /matridxigams/**
eureka:
  instance:
    instance-id: ${ipaddr:localhost}:${server.port}
    #home-page-url-path: ${ipaddr:localhost}:${server.http.port}
    #health-check-url-path: ${ipaddr:localhost}:${server.http.port}/actuator/health
    #status-page-url-path: ${ipaddr:localhost}:${server.http.port}/actuator/info
    #home-page-url: http://${ipaddr:localhost}:${server.http.port}
    #health-check-url: http://${ipaddr:localhost}:${server.http.port}/actuator/health
    #status-page-url: http://${ipaddr:localhost}:${server.http.port}/actuator/info
server:
  port: ${port:8390}
  #http:
    #port: ${port:8390}
  #ssl:
    #key-store: 9922037_medlab.matridx.com.pfx
    #key-store-password: ykzw3ej8