spring:
  application:
    name: igams-web
  redis:
    ## Redis服务器地址
    host: 127.0.0.1
    ## Redis服务器连接密码（默认为空）
    password:
    port: 10001
  rabbitmq:
    addresses: ${mqaddr:admin:matridx2019!@172.17.60.188:5672}
    host: ${mqhost:172.17.52.95}
    username: ${mqname:admin}
    password: ${mqpass:xksr0911.}
    virtualHost: ${mqvirtualhost:/}
    port: ${mqport:9003}
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    viewname: 杰毅生物
    protocol: smtp
    username: 
    password: 
postsql:
  datasource:
    driverClassName: org.postgresql.Driver
    username: AEBrmFhq9gZ4Yeq+mogdzQ==
    password: DmnVklgEln/9NePegyMNig==
    url: E6Bxa5hFXjN+sYdjKG06wJ4rdyisoRVLdb2Upibi5aMnD4Uo6p8JvqzZOWVzceZa
    validationQuery: SELECT 1
#sqlserver:
#  gmds:
#    username: C7PnCpt+ks/6vf8lMKVK/w==
#    password: oavtufUPXtIA2XoEPj8mCg==
#    #jdbc:sqlserver://192.168.1.130:1433;database=ahos";
#    url: 05rJvWC/dZNwL93RtuHWFOwhx8odJYDGpeGdcV8McIa+qoIvC+7EEzgD2O+Oo2KXXUwM1uj944lMCopLJDbKpQ==
#  matridxds:
#    username: C7PnCpt+ks/6vf8lMKVK/w==
#    password: oavtufUPXtIA2XoEPj8mCg==
#    #jdbc:sqlserver://192.168.1.130:1433;database=ahos";
#    url: 05rJvWC/dZNwL93RtuHWFOwhx8odJYDGpeGdcV8McIa+qoIvC+7EEzgD2O+Oo2KX9hwh9PEgRNg4FkJWqFgNbg==
##角色切换配置： 0不支持切换，1支持切换
matridx:
  role:
    switch: 1
  exptype:
    limit: 500
  fileupload:
    prefix: 
    tempPath: /matridx/fileupload/temp/
    releasePath: /matridx/fileupload/release/
  file:
    ##文件导出存放路径
    exportFilePath: /matridx/download/
    ##文件保存路径前缀
    pathPrefix: 
    ##文件转换最大次数
    translimit: 5
  ftp:
    wordpath: /wordFile
    pdfpath: /pdfFile
    url: 172.17.52.18
    user: ftpuser
    pd: matridx
    port: 21
  ##钉钉
  dingtalk:
    appkey: SjiVL+I3B6kEhRLZF4/FYb4nE6hsaQF5pzqRdFsSUFM=
    appsecret: Rebf6/oPXPP/H41hYBzQimFnVrm0vsQCzaXvIC7i8a9qcdocNErZDsK6ol+OHhAmet3/jn0VpbpqWm8QoL8jSzJVhPyCTTb2m8Ia5X4cJ9k=
    agentid: 667lPwpNVwmh3pV6LMNA6Q==
  ##语音识别
  audio:
    savepath: /matridx/audio/save/
    audiotype: ali       ##ali  baidu
    #accessKeyId: ZY5umhS7CN9RRVKg1x3poKfc8IzB4TkAp0/GRS/sXYo=
    #accessKeySecret: YgFUZcqxPzLq286Nwmfj4BFfN+QbP4eu8EGl52g42tIyVYT8gk029pvCGuV+HCfZ
    #appid: L2rjGmuPzJ9xmSU0/9iyFA==
    accessKeyId: Fyj2gzZ9dU2Xw2lxrxfBQzJVhPyCTTb2m8Ia5X4cJ9k=
    accessKeySecret: AElsGW16bjaYU2qiTVqwIOzhlmPt5FpxGq6c5XKsKHM=
    appid: vo88lJAbqCj5CzwR8/u4cTJVhPyCTTb2m8Ia5X4cJ9k=
  wechat: 
    ##菜单推送微信的地址
    menuurl: http://localhost:8085
    ##钉钉查看访问的路径
    applicationurl: http://172.17.52.18:8086
    ## 送检发送请求查询 检测结果的地址
    inspectionurl: http://localhost:8085
    ## 统计外部地址
    externalurl: http://101.68.81.90:8093
    appid: 1
    secret: 2
    paternerkey: 
    mchid:  
  baidu:
    appkey: 
    secret: 
  alipay:
    ## 应用ID,您的APPID，收款账号既是您的APPID对应支付宝账号
    app_id: 
    ## 应用ID,您的APPID，收款账号既是您的APPID对应支付宝账号
    #uid: 2088102177450010
    ## 商户私钥，您的PKCS8格式RSA2私钥
    alipay_private_key: 
    ## 支付宝公钥,查看地址：https://openhome.alipay.com/platform/keyManage.htm 对应APPID下的支付宝公钥。
    alipay_public_key: 
    ## 服务器异步通知页面路径  需http://格式的完整路径，不能加?id=123这类自定义参数 
    notify_url: http://101.68.81.90:8099/wechat/pay/aliPayNotify
    ## 页面跳转同步通知页面路径 需http://格式的完整路径，不能加?id=123这类自定义参数 
    return_url: http://101.68.81.90:8099/wechat/pay/aliPayComplete
    ## 签名方式
    alipay_sign_type: RSA2
    ## 支付宝网关
    gatewayUrl: 
  ##阿里云短信
  aliyunSms: 
    accessKeyId: 
    accessSecret: 
    signName: 杰毅检验
    templateCode: SMS_170840387
  systemflg:
    logourl: /images/logoIn-biology.png
    watermark: 杰毅麦特
  prefix:
    urlprefix: 
    title: 杰毅生物OA
    igamsweb: /lwj-igams-web
  rabbit:
    ## 系统信息同步时的标记，还需在rabbit下进行配置，使Routing key为sys.igams.jcsj.del能同时匹配到sys.igams.jcsj.del，sys.igams.jcsj.del.production
    ## 其中production就是这个flg标记
    flg: 
zuul:
  ##需要忽略的头部信息，不在传播到其他服务
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
  routes:
    lwj-igams-production: /matridxprod/**
    yjw-igams-production: /yjwprod/**
    lsy-igams-production: /lsyprod/**
    zh-igams-production: /zhprod/**
    igams-cloud-lab: /labigams/**
server:
  #ssl:
    #key-store: server.keystore
    #key-alias: tomcat
    #enabled: true
    #key-store-password: matridx2019
    #key-store-type: JKS