spring:
  application:
    name: gxj-igams-web
  redis:
    ## Redis服务器地址
    host: 172.17.60.197
    ## Redis服务器连接密码（默认为空）
    password: matridx2021
    port: 7382
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    viewname: 杰毅生物
    protocol: smtp
    username: hongminzheng@163.com
    password: RCQXFNEEVNJICHNZ
  cloud:
    nacos:
      discovery:
        #        server-addr: 60.191.45.243:8828
        #        username: matridx
        #        password: nacos2020!
        server-addr: ${servip:172.17.60.197:8828}
        username: ${servname:matridx}
        password: ${servpass:nacos2020!}
        namespace: ${nsp:1bb5f403-49c2-4f78-94aa-45ea8a766961}
        ip: ${ipaddr:172.17.60.111}
        port: ${ipport:80}
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: ${clientid:oauclient} #客户端id
          client-secret: ${clientpass:123456} #客户端密钥
          #          introspection-uri: ${introuri:https://devauth.matridx.com}/oauth2/introspect #oauth自检接口
          introspection-uri: http://cs.server.com:8091/oauth2/introspect
#  本地
#postsql:
#  datasource:
#    username: o+iJ59jV0h1b2w6RWhS4Sg==
#    password: MrTVAg0Sn2SfQZE/HUZ5IQ==
#    url: E6Bxa5hFXjN+sYdjKG06wOCsp1DH0IZMJUquJ5w+uYPtmycHAIPwBJtbT3XsGaP4
#    188
postsql:
  datasource:
    username: AEBrmFhq9gZ4Yeq+mogdzQ==
    password: DmnVklgEln/9NePegyMNig==
    url: E6Bxa5hFXjN+sYdjKG06wJ4rdyisoRVLdb2Upibi5aMnD4Uo6p8JvqzZOWVzceZa
sqlserver:
  gmds:
    username: C7PnCpt+ks/6vf8lMKVK/w==
    password: KUZmZ4Ds0epg3B3AQIwbnw==
    url: 05rJvWC/dZNwL93RtuHWFAZc3ItMuGi+V6ujpzN80lW+qoIvC+7EEzgD2O+Oo2KXK5ILWx/JzunHNuGNb40X+76YkXoo3dHKJir6yzDLGqayNybunbdN2ULv8YhBREPV
    flag: 麦特
  matridxds:
    username: C7PnCpt+ks/6vf8lMKVK/w==
    password: KUZmZ4Ds0epg3B3AQIwbnw==
    url: 05rJvWC/dZNwL93RtuHWFAZc3ItMuGi+V6ujpzN80lW+qoIvC+7EEzgD2O+Oo2KXK5ILWx/JzunHNuGNb40X+76YkXoo3dHKJir6yzDLGqayNybunbdN2ULv8YhBREPV
    flag: 生物
##角色切换配置： 0不支持切换，1支持切换
matridx:
  cookie:
    domain: cs.client.com
    cookiekey: 1
    ## 跳转的认证中心，如果用本系统，则不用设置，否则是 https://medlab.matridx.com/
    loginCentre:
      url:
  cnv:
    auditurl: http://172.17.53.87:8086
  #橄榄枝健康
  glzhealth:
    appointmentfinishurl: http://localhost:8086/ws/ganlanzhi
    #我方需给对方加密后的key
    glzhealthKey: ganlanzhihealth
  #阿里健康
  alihealth:
    appSecret: 17cc7a528439a07a63b8c662c3df8f5a
    appKey: 33460000
    serverUrl: https://eco.taobao.com/router/rest
    merchantAesKey: WwYaE9eLbGw5B9Un
  #京东物流
  jingdong:
    appSecret: c9431790cc7844a0addf888ba9573b98
    appKey: c40b1bce312d4eff951f4bd1c7beb79a
    serverUrl: https://api.jdl.com
    customerCode: 021K1407284
    accessToken: d3d507b3516c494dbec43ae0996dc9ca
    refreshToken: 6f025e160ac84ad6b91b27f8c7ac4ef5
  #顺丰物流
  sf:
    ##顺丰平台顾客编码
    client_code: JYSWJW
    ##顺丰平台校验码
    check_word: x303u6lj59tqMKjBtEqqZjHCCgYqH40w
    ##顺丰生产环境地址
    call_url_prod: https://sfapi.sf-express.com/std/service
    ##顺丰沙箱环境地址
    call_url_box: https://sfapi-sbox.sf-express.com/std/service
  role:
    switch: 1
  exptype:
    limit: 500
  fileupload:
    prefix:
    tempPath: /matridx/fileupload/temp/
    releasePath: /matridx/fileupload/release/
  file:
    ##文件导出存放路径
    exportFilePath: /matridx/download/
    poolingExportFilePath: /matridx/download/
    ##文件保存路径前缀
    pathPrefix:
    ##文件转换最大次数
    translimit: 5
  ftp:
    wordpath: /wordFile
    pdfpath: /pdfFile
    #    url: 172.17.60.184
    url: 172.17.60.177
    user: ftpuser
    pd: matridx
    port: 21
  ##钉钉
  dingtalk:
    miniurl: Lz0Qi39mDV9YbnhyI3+8xhciRl4pY5+eMLzG+soXtK1iy373PwQ04d6uT8EjVHNzN1/TmqvX+PxcICDIthwarcnkEW6oiX7nSZjSdrpIWFouz7TUB9Q+1GIIysJ26i0NO05sBV/mJHB40XeEMBVBtLT9WYEj+n3K8x3EAwP7tEOazDHlvtl4be1KjJ/R5VDqVMZZEvfDAQCLrY0XaqUXfKIIVdtFTEHf/klymWO10sM=
    jumpdingtalkurl: Lz0Qi39mDV9YbnhyI3+8xhciRl4pY5+eMLzG+soXtK1iy373PwQ04d6uT8EjVHNz84DQUkLhuH9AIUKNQLyjjKxPpUnS3vwSb7F0SPNBaLguz7TUB9Q+1GIIysJ26i0NSSJ3ri0g+6ypFrNd63GNPOd294rmQV2NCYW7ej8zRi4y/ydIDnScydU5F6Oa7nrEWK7+FaEt+vRlxOn/gMXDhCt+eA0pOQ1kuDQGvZDPFxw=
    appkey: kC6c7IjbNcf50IqGMq1aaj+XplQLqSod0auY/BU5mEg=
    appsecret: 2ZmEBEks6lVSZU2dtA8Mu1dYLcRa7Pku9ta/fQaV5SD7Nled58UFOZti9RShQH7/jvWqydyU1pKGwFQT9P+A2DJVhPyCTTb2m8Ia5X4cJ9k=
    agentid: 667lPwpNVwmh3pV6LMNA6Q==
    callbackurl: http://dev.matridx.com:8090
    cropid: PAi6mqqSMLdnxhFqQOdG7dsZefVmxGWVEvq0JsEZips=
    aeskey: B6as7DpuYYMxhuqiIHwifJISBZhWicg0eqZPXalq8s8=
    miniappkey: kC6c7IjbNcf50IqGMq1aaj+XplQLqSod0auY/BU5mEg=
    miniappsecret: 2ZmEBEks6lVSZU2dtA8Mu1dYLcRa7Pku9ta/fQaV5SD7Nled58UFOZti9RShQH7/jvWqydyU1pKGwFQT9P+A2DJVhPyCTTb2m8Ia5X4cJ9k=
  ##语音识别
  audio:
    savepath: /matridx/audio/save/
    audiotype: ali       ##ali  baidu
    #accessKeyId: ZY5umhS7CN9RRVKg1x3poKfc8IzB4TkAp0/GRS/sXYo=
    #accessKeySecret: YgFUZcqxPzLq286Nwmfj4BFfN+QbP4eu8EGl52g42tIyVYT8gk029pvCGuV+HCfZ
    #appid: L2rjGmuPzJ9xmSU0/9iyFA==
    accessKeyId: Fyj2gzZ9dU2Xw2lxrxfBQzJVhPyCTTb2m8Ia5X4cJ9k=
    accessKeySecret: AElsGW16bjaYU2qiTVqwIOzhlmPt5FpxGq6c5XKsKHM=
    appid: vo88lJAbqCj5CzwR8/u4cTJVhPyCTTb2m8Ia5X4cJ9k=
  wechat:
    ##菜单推送微信的地址
    menuurl: http://60.191.45.243:8182
    ##钉钉查看访问的路径
    applicationurl: http://172.17.52.95:8086
    ddurl: http://cs.client.com:8094
    ## 送检发送请求查询 检测结果的地址
    inspectionurl: http://172.17.52.95:8085
    ## 统计外部地址
    externalurl: http://cs.client.com:8094
    customizeurl: http://cs.client.com:8094
    ouathurl: https://devauth.matridx.com
    appid: 1
    secret: 2
    paternerkey:
    mchid:
    ## 钉钉回调注册地址190
    registerurl: http://172.17.60.190
  baidu:
    appkey: zn7Nv0cL9ronYbOMXGK0dSZ/l4v/pcLnUVSVLhEx8R4=
    secret: H2Zh1KK6LQoEM/lgt2KrdETv0qH0itW6f4v9czTHB7YyVYT8gk029pvCGuV+HCfZ
    ocrAkey: SYFOHFWA5cBfYPUUWrw3b1na
    ocrSkey: GpyHdf4TPDGf2x9arKYp9gBh7MlGGbsX
  alipay:
    ## 应用ID,您的APPID，收款账号既是您的APPID对应支付宝账号
    app_id:
    ## 应用ID,您的APPID，收款账号既是您的APPID对应支付宝账号
    #uid: 2088102177450010
    ## 商户私钥，您的PKCS8格式RSA2私钥
    alipay_private_key:
    ## 支付宝公钥,查看地址：https://openhome.alipay.com/platform/keyManage.htm 对应APPID下的支付宝公钥。
    alipay_public_key:
    ## 服务器异步通知页面路径  需http://格式的完整路径，不能加?id=123这类自定义参数
    notify_url: http://101.68.81.90:8099/wechat/pay/aliPayNotify
    ## 页面跳转同步通知页面路径 需http://格式的完整路径，不能加?id=123这类自定义参数
    return_url: http://101.68.81.90:8099/wechat/pay/aliPayComplete
    ## 签名方式
    alipay_sign_type: RSA2
    ## 支付宝网关
    gatewayUrl:
  ##阿里云短信
  aliyunSms:
    accessKeyId: GB3oWZjNqD177DTTdjKelzJVhPyCTTb2m8Ia5X4cJ9k=
    accessSecret: jDp6CBmApWl/XLtobsbblOs9lXhNO+2cV7zK3SuWHEc=
    signName: 杰毅检验
    signNameMatridx: 杰毅生物
    templateCode: SMS_170840387
    templateCodeXgyy: SMS_236565506
    templateCodeXgbg: SMS_230420609
  aliOcr:
    ocrIdCardAppCode: 6707b7afcecf40dfb1f2a1c36bda36be
  systemflg:
    logourl: /images/logoIn-biology.png
    watermark: 杰毅麦特
    remindflg: 0
    systemname: 杰毅生物
  prefix:
    urlprefix:
    title: 杰毅生物OA
    igamsweb: /gxj-igams-web
  rabbit:
    ## 系统信息同步时的标记，还需在rabbit下进行配置，使Routing key为sys.igams.jcsj.del能同时匹配到sys.igams.jcsj.del，sys.igams.jcsj.del.production
    ## 其中production就是这个flg标记
    flg:
  #    preflg:
  #杏和软件配置
  xinghe:
    # 调用凭证
    ticket: 8eaadf17e7b76a650455a5d6d1105fff
    #    ticket: 1234567890123
    url: http://118.178.255.230:9001/XingHeAreaService.asmx
    wsdlurl: http://118.178.255.230:9001/XingHeAreaService.asmx?WSDL
    # 检测机构
    hospitalservice: 33A038
  qianmai:
    url: https://lims20foreign.cmlabs.com.cn
    entrustHosCode: 杰毅
    usercode: jieyi
    password: Abc123,.,.
  henuo:
    url: https://a.ldrmed.com:4432/api/
    account: 103
    password: abcd1234
    userType: 3
    entrustHosCode: 103
  aidikang:
    url: https://dataexchange.adicon.com.cn:9281
    #    url: https://adicontest.adicon.com.cn:5000
    newurl: https://lego-vip.adicon.com.cn
    #    newurl: https://limscloud-test.adicon.com.cn:1090
    businessclass: ADC_BC0050
    username: A2023Jecszth.cd
    password: C2yp1e1504c98fb1baHcc1.b5387n
  ## 招行支付功能
  cmbbankpay:
    # 商户号
    merid: 308999150470012
    # 收银员
    userid: N082523824
    # APPID
    appid: 5dbad146-d728-4f7a-bbe2-700a3d91c8e5
    # APP SECRET
    secret: a9bff450-4a4b-4f0d-9cbb-039492d2f883
    # 商户私钥
    private_key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCjn86PmRk6Ae8fNpGliUl+JE+6z5Y0mzFV3XjjKXcEtS6GfWTSsZmOHo5VSIp4THlQ1G10Sr+FGZcAVH6v/XmyPsCRoaKwanBz6c0hnMVRYvILldbqqsoEMJR0ztqABzNXPC1fS9/j8Dy0x5VdPRBpSsBKqylGzJdA0LdMvIBM31SnLXSlnPwRaQgehWDdXpGa+N52b2hi6GFDfClge4E+H6zTvQeiSmmZVCqbpxUKF4181bC9k0DpX+s6xfrmACFvQvZZlYw1JDfUItVXtL+QqpUY0r/DLWj3zQQmREev+dvF7vsUQ+0Z+3Ptr/WMZGREQpeXjGO+um6pkJJtVzfhAgMBAAECggEBAIhPiKCedaKam9/P8RQLxBr/GyDQ8RxQMZCL2bq8/3b/jYvjCMxxwi/gisjHjvvbEbHh1nFsGBNFF0PiIExzCSASIRDxq/v2IEqgexDGbqd3m5dFM+75aySEaBjLfsHrvbyt2Eqshg95QsmD/43WYkalTH6oCtH9fQA1II8f9m6Sv73rjsc7fZzf21xI0euNLcUz1SgWmutPKdT0roOlxcGEpqHABZ4PUuhcFZRymTWs0XahdFR+JQsVww1mdQD6Alg75PFFvyDDajke+nGf+7KZkseSyefcgolCpy1AAL8XD/4krssXnSjgSjWuLEy2uRjbC+gihNoFPLdu9dOcoQECgYEA9/6zkxYGdRhw4arm0Ba5BwG4+vLF2LyzMfdUFOg02Lw5AMtSk2nquZCOBCJ6JoXO4qQ/0U8BdmttwIf5hvbU7ome8kHxqMuF2kw1XdhgO3IRyuCvSuUfhJ50xIvnEVnwjwQdLlyB1ymqcf0FBdgk8NmwusHxm3yz+qImbQYVItECgYEAqOfpLaTdbvyx3zBkzU7V2YLVcu8jRo8dUU0EVF5fh+11N/dyxTdG38YCP4wOkDPvSDx/OIt0ogQr4I1Txc9RJQRJRoiG54NSFOgfykW+ZQnq4aYn/3CvBQIe8X2zM7lTIYKpWn9IeSAfVAiWtWEeQk1QpobUPXkm96JJMPfbaBECgYEAi/L4c/DiBAKe8Tr4tkWcdQ/LzBJlBEK4/WGN2Z6Q9B6ELKaRGw+SntWszziFpmessMnwGbZ0JNfLP/N8JWX2FAcl46DDN3ZjOyX2l9cbt3BQCiVxxto2RykEzEYHSAtxbcPsk9UwkLO6tEkNJJctgZ3X1gzMw+pDxxTqimv8UYECgYBy9hWxaWsFpZxzKn8Rdjz7ZJ9fMQCzf6kWsvLlca5X1/lWdGd7b9ofaKgTFIK9B3wvkG2O0Ow7cddjaQ3Brw+twDMXfMlFPg5aCHvKspmaL5vcpbjHlayqHf1tpH6aD+NTBZm67LMpLgHkskvRfB6aRgFEtrQyewlYtu5WE/0T4QKBgQD057pt7bCVyY7ityQngjuFlt+olBIhaYZZx8QNF6j8AhGPE6wrq2ByLZkwwkt7aqpXa2HQxxX9jFz4YyIyVEDcap52rx8daa1iIjjlCN5w2DRbRJZHKJzcoYgS3yZpnq90i+Ug82PnpGnPAPd26aRrPMURPdm80dHr6LPx4Binmg==
    # 商户公钥
    public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo5/Oj5kZOgHvHzaRpYlJfiRPus+WNJsxVd144yl3BLUuhn1k0rGZjh6OVUiKeEx5UNRtdEq/hRmXAFR+r/15sj7AkaGisGpwc+nNIZzFUWLyC5XW6qrKBDCUdM7agAczVzwtX0vf4/A8tMeVXT0QaUrASqspRsyXQNC3TLyATN9Upy10pZz8EWkIHoVg3V6Rmvjedm9oYuhhQ3wpYHuBPh+s070HokppmVQqm6cVCheNfNWwvZNA6V/rOsX65gAhb0L2WZWMNSQ31CLVV7S/kKqVGNK/wy1o980EJkRHr/nbxe77FEPtGftz7a/1jGRkREKXl4xjvrpuqZCSbVc34QIDAQAB
    # 招行公钥
    cmb_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2xsbUaLEPa8o3JYyjB+wSARyzzsL2QRHlIkSrYUK/cZCXIvA3feVqHfZAFkBtNWg45IxADpmSq5ZgkgZSRqfGoRSlLSnxWqBIB1UAmy0dlKY01xLJhCEHEOsGjcG4RYYMTnQ2T8PHAdE/sIMisdW4PDlV1P2WU0LdZZS8o6sKcXvgZeiZNllKoOvvb5uYccjyq8pjSB1AsYzQ4qK6PgAH4mZlPSyn2IBMzPTgdZQQd0nqfWd94z1sdk8XIGovap7rVCIVGWK11Kfos/XiQgjwIi6t812FSTrsONG9uiAsJoET4ujOUNd/eNkuLOY929ZLbjb+jIYQov5yS4y69i04QIDAQAB
    # 商品描述
    description: 检测费支付
zuul:
  ##需要忽略的头部信息，不在传播到其他服务
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
  routes:
    lwj-igams-production: /matridxprod/**
    yjw-igams-production: /yjwprod/**
    lsy-igams-production: /lsyprod/**
    zh-igams-production: /zhprod/**
    hmz-igams-production: /hmzprod/**
    gxj-igams-production: /gxjprod/**
    igams-cloud-lab: /labigams/**
server:
#ssl:
#key-store: server.keystore
#key-alias: tomcat
#enabled: true
#key-store-password: matridx2019
#key-store-type: JKS