spring:
  application:
    name: igams-web
  redis:
    ## Redis服务器地址 

    timeout: 1000
    host: ${rdbhost:localhost}
    ## Redis服务器连接密码（默认为空）
    #password: 
    port: 6379
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    viewname: 杰毅生物
    protocol: smtp
    username: 
    password: 
  rabbitmq:
    #port: 5672
    port: ${mqport:5672}
    #address: ${mqaddr:admin:matridx2019!@172.17.60.190:5672}
    host: ${mqhost:172.17.60.190}
    username: ${mqname:admin}
    password: ${mqpass:matridx2019!}
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true     # 是否开启消费者重试（为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息）
          max-attempts: 5   # 最大重试次数
          max-interval: 10000   # 重试最大间隔时间
          initial-interval: 2000  # 重试初始间隔时间
          # 重试间隔*乘子得出下次重试间隔  2s  4s  8s  16s  此处16s>10s  走10s
          multiplier: 2 # 间隔时间乘子，间隔时间*乘子=下一次的间隔时间，最大不能超过设置的最大间隔时间
    report:
      port: 5672
      #发送确认
      publisher-confirms: true
      host: ${reporthost:}
      username: ${reportname:}
      password: ${reportpass:}
      notopen: false
  config:
    import: optional:configserver:${uri:http://172.17.60.101:8960}
postsql:
  datasource:
    username: AEBrmFhq9gZ4Yeq+mogdzQ==
    password: MrTVAg0Sn2SfQZE/HUZ5IQ==
    url: E6Bxa5hFXjN+sYdjKG06wOCsp1DH0IZMJUquJ5w+uYPtmycHAIPwBJtbT3XsGaP4
sqlserver:
  gmds:
    username: C7PnCpt+ks/6vf8lMKVK/w==
    password: oavtufUPXtIA2XoEPj8mCg==
    #jdbc:sqlserver://192.168.1.130:1433;database=ahos";
    url: 05rJvWC/dZNwL93RtuHWFOwhx8odJYDGpeGdcV8McIa+qoIvC+7EEzgD2O+Oo2KXXUwM1uj944lMCopLJDbKpQ==
  matridxds:
    username: C7PnCpt+ks/6vf8lMKVK/w==
    password: oavtufUPXtIA2XoEPj8mCg==
    #jdbc:sqlserver://192.168.1.130:1433;database=ahos";
    url: 05rJvWC/dZNwL93RtuHWFOwhx8odJYDGpeGdcV8McIa+qoIvC+7EEzgD2O+Oo2KX9hwh9PEgRNg4FkJWqFgNbg==
##角色切换配置： 0不支持切换，1支持切换
matridx:
  role:
    switch: 1
  basictype:
    file: config/comm/basicType.xml
  imptype:
    file: config/comm/config-import.xml
  exptype:
    file: config/comm/config-export.xml
    limit: 500
  fileupload:
    prefix: 
    tempPath: /matridx/fileupload/temp/
    releasePath: /matridx/fileupload/release/
  file:
    ##文件导出存放路径
    exportFilePath: /matridx/download/
    ##文件保存路径前缀
    pathPrefix: 
    ##文件转换最大次数
    translimit: 5
  ftp:
    wordpath: /wordFile
    pdfpath: /pdfFile
    url: 172.17.52.18
    user: ftpuser
    pd: matridx
    port: 21
  ##钉钉
  dingtalk:
    appkey: SjiVL+I3B6kEhRLZF4/FYb4nE6hsaQF5pzqRdFsSUFM=
    appsecret: Rebf6/oPXPP/H41hYBzQimFnVrm0vsQCzaXvIC7i8a9qcdocNErZDsK6ol+OHhAmet3/jn0VpbpqWm8QoL8jSzJVhPyCTTb2m8Ia5X4cJ9k=
    agentid: 667lPwpNVwmh3pV6LMNA6Q==
  ##语音识别
  audio:
    savepath: /matridx/audio/save/
    audiotype: ali       ##ali  baidu
    #accessKeyId: ZY5umhS7CN9RRVKg1x3poKfc8IzB4TkAp0/GRS/sXYo=
    #accessKeySecret: YgFUZcqxPzLq286Nwmfj4BFfN+QbP4eu8EGl52g42tIyVYT8gk029pvCGuV+HCfZ
    #appid: L2rjGmuPzJ9xmSU0/9iyFA==
    accessKeyId: Fyj2gzZ9dU2Xw2lxrxfBQzJVhPyCTTb2m8Ia5X4cJ9k=
    accessKeySecret: AElsGW16bjaYU2qiTVqwIOzhlmPt5FpxGq6c5XKsKHM=
    appid: vo88lJAbqCj5CzwR8/u4cTJVhPyCTTb2m8Ia5X4cJ9k=
  wechat: 
    ##菜单推送微信的地址
    menuurl: http://localhost:8085
    ##钉钉查看访问的路径
    applicationurl: http://172.17.52.18:8086
    ## 送检发送请求查询 检测结果的地址
    inspectionurl: http://localhost:8085
    ## 统计外部地址
    externalurl: http://101.68.81.90:8093
    appid: 1
    secret: 2
    paternerkey: 
    mchid:  
  baidu:
    appkey: 
    secret: 
  alipay:
    ## 应用ID,您的APPID，收款账号既是您的APPID对应支付宝账号
    app_id: 
    ## 应用ID,您的APPID，收款账号既是您的APPID对应支付宝账号
    #uid: 2088102177450010
    ## 商户私钥，您的PKCS8格式RSA2私钥
    alipay_private_key: 
    ## 支付宝公钥,查看地址：https://openhome.alipay.com/platform/keyManage.htm 对应APPID下的支付宝公钥。
    alipay_public_key: 
    ## 服务器异步通知页面路径  需http://格式的完整路径，不能加?id=123这类自定义参数 
    notify_url: http://101.68.81.90:8099/wechat/pay/aliPayNotify
    ## 页面跳转同步通知页面路径 需http://格式的完整路径，不能加?id=123这类自定义参数 
    return_url: http://101.68.81.90:8099/wechat/pay/aliPayComplete
    ## 签名方式
    alipay_sign_type: RSA2
    ## 支付宝网关
    gatewayUrl: 
  ##阿里云短信
  aliyunSms: 
    accessKeyId: 
    accessSecret: 
    signName: 杰毅检验
    templateCode: SMS_170840387
  systemflg:
    logourl: /images/logoIn-biology.png
    watermark: 杰毅生物
    ## 定时任务是否执行 0：不执行  1：执行
    remindflg: 0
    ## 启动时根据标记redisreset判断是否进行redis数据的删除重新加入的操作, 1进行操作，0不进行操作
    redisreset: 1
    ## 跨域限制
    alloworigin: '*'
  ## cookie所存放的域名
  cookie:
    domain: .matridx.com
  ## 跳转的认证中心，如果用本系统，则不用设置，否则是 https://medlab.matridx.com/
  loginCentre:
    url: 
  ##U8账套名称
  accountSet:
    accountName: 001
  prefix:
    urlprefix: 
    title: 杰毅生物OA
    igamsweb: /lwj-igams-web
  rabbit:
    ## 系统信息同步时的标记，还需在rabbit下进行配置，使Routing key为sys.igams.jcsj.del能同时匹配到sys.igams.jcsj.del，sys.igams.jcsj.del.production
    ## 其中production就是这个flg标记
    flg: 
  # 杏和系统配置文件（配置文件的matridx下）--
  xinghe:
    # 调用凭证
    ticket: 8eaadf17e7b76a650455a5d6d1105fff
    url: http://118.178.255.230:9001/XingHeAreaService.asmx
    wsdlurl: http://118.178.255.230:9001/XingHeAreaService.asmx?WSDL
    # 检测机构
    hospitalservice: 33A038
  blanklist:
    host: 
zuul:
  ##需要忽略的头部信息，不在传播到其他服务
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
  routes:
    lwj-igams-production: /matridxprod/**
    yjw-igams-production: /yjwprod/**
    lsy-igams-production: /lsyprod/**
    zh-igams-production: /zhprod/**
    igams-cloud-lab: /labigams/**
server:
  port: ${sport:8086}
## 打印sql
logging:
  config: classpath:log4j2.xml