
package com.neusoft.si.entrance.webservice.collectdeclareservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "collectDeclareService", targetNamespace = "http://collectdeclareservice.webservice.entrance.si.neusoft.com/", wsdlLocation = "http://192.26.64.134:8889/SJCJHQRWHJKQ/PCRWHHQQ?wsdl")
public class CollectDeclareService_Service
    extends Service
{

    private final static URL COLLECTDECLARESERVICE_WSDL_LOCATION;
    private final static WebServiceException COLLECTDECLARESERVICE_EXCEPTION;
    private final static QName COLLECTDECLARESERVICE_QNAME = new QName("http://collectdeclareservice.webservice.entrance.si.neusoft.com/", "collectDeclareService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.26.64.134:8889/SJCJHQRWHJKQ/PCRWHHQQ?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COLLECTDECLARESERVICE_WSDL_LOCATION = url;
        COLLECTDECLARESERVICE_EXCEPTION = e;
    }

    public CollectDeclareService_Service() {
        super(__getWsdlLocation(), COLLECTDECLARESERVICE_QNAME);
    }

    public CollectDeclareService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), COLLECTDECLARESERVICE_QNAME, features);
    }

    public CollectDeclareService_Service(URL wsdlLocation) {
        super(wsdlLocation, COLLECTDECLARESERVICE_QNAME);
    }

    public CollectDeclareService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COLLECTDECLARESERVICE_QNAME, features);
    }

    public CollectDeclareService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CollectDeclareService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CollectDeclareService
     */
    @WebEndpoint(name = "CollectDeclareServiceImplPort")
    public CollectDeclareService getCollectDeclareServiceImplPort() {
        return super.getPort(new QName("http://collectdeclareservice.webservice.entrance.si.neusoft.com/", "CollectDeclareServiceImplPort"), CollectDeclareService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CollectDeclareService
     */
    @WebEndpoint(name = "CollectDeclareServiceImplPort")
    public CollectDeclareService getCollectDeclareServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://collectdeclareservice.webservice.entrance.si.neusoft.com/", "CollectDeclareServiceImplPort"), CollectDeclareService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COLLECTDECLARESERVICE_EXCEPTION!= null) {
            throw COLLECTDECLARESERVICE_EXCEPTION;
        }
        return COLLECTDECLARESERVICE_WSDL_LOCATION;
    }

}
