spring:
  profiles:
    active: dev
  rabbitmq:
    host: ${mqhost:172.17.60.190}
    username: ${mqname:admin}
    password: ${mqpass:matridx2019!}
    docok: ${mqok:wechat.production.mq.tran.matridx.ok}
  main:
    allow-bean-definition-overriding: true
server:
  port: ${sport:8086}
  tomcat:
    port-header: HEAD,PUT,DELETE,OPTIONS,TRACE,COPY,SEARCH,PROPFIND