spring:
  application:
    name: las-server
  session:
    #session存储类型
    store-type: redis
    #设置session超时时间
    timeout: 2000
  ## druid配置
  datasource:
    ## 连接池最小连接数量
    minIdle: 5
    ## 连接池最大连接数量
    maxActive: 100
    ## 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
    initialSize: 10
    ## 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
    maxWait: 60000
    ## 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒;有两个含义：1) Destroy线程会检测连接的间隔时间 2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
    timeBetweenEvictionRunsMillis: 60000
    ## 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    ## 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    testWhileIdle: true
    ## 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    testOnBorrow: false
    ## 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false
    ## 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql5.5以下的版本中没有PSCache功能，建议关闭掉。5.5及以上版本有PSCache，建议开启。
    poolPreparedStatements: true
    ## 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
    maxPoolPreparedStatementPerConnectionSize: 100
    ## Druid的监控统计功能:属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：
    #监控统计用的filter:stat
    #日志用的filter:slf4j
    #防御SQL注入的filter:wall
    filters: config,stat,slf4j
    ## 连接数据库的额外参数 
    connectionProperties: 3000;
    ## 缺省多个DruidDataSource的监控数据是各自独立的，在Druid-0.2.17版本之后，支持配置公用监控数据，
    useGlobalDataSourceStat: true
    ## druid的登录用户名
    druidLoginName: admin
    ## druid的登录密码
    druidPassword: 1234
    ## 超过时间限制是否回收
    removeAbandoned: true
    ## 超过时间限制多长，单位是毫秒 ，180000毫秒=3分钟
    removeAbandonedTimeout: 180000
  thymeleaf:
    #prefix: classpath*:/static/
    suffix: .html
    encoding: UTF-8
    cache: false
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    viewname: 杰毅生物
    protocol: smtp
    username: 1
    password: 2
  #缓存管理
  cache:
    ehcache:
      config: classpath:config/ehcache/ehcache.xml
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: 
    pool:
            # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
            # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
            # 连接池中的最大空闲连接
      max-idle: 8
            # 连接池中的最小空闲连接
      min-idle: 0
        # 连接超时时间（毫秒） 中时间设置不能为0
    timeout: 5000
  #spring boot自带的tomcat限制了上传图片的大小，为1M
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1000MB
    #消息队列
  rabbitmq:
    address: ${mqaddr:admin:matridx2019!@172.17.60.190:5672}
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true     # 是否开启消费者重试（为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息）
          max-attempts: 5   # 最大重试次数
          max-interval: 10000   # 重试最大间隔时间
          initial-interval: 2000  # 重试初始间隔时间
          # 重试间隔*乘子得出下次重试间隔  2s  4s  8s  16s  此处16s>10s  走10s
          multiplier: 2 # 间隔时间乘子，间隔时间*乘子=下一次的间隔时间，最大不能超过设置的最大间隔时间
    #发送确认
    publisher-confirms: true
    #virtual-host: /
postsql:
  datasource:
    driverClassName: org.postgresql.Driver
    username: ${dbuser:AEBrmFhq9gZ4Yeq+mogdzQ==}
    password: ${dbpass:DmnVklgEln/9NePegyMNig==}
    url: ${dburl:E6Bxa5hFXjN+sYdjKG06wMD2DA7457ThLcyaMeSx4sgnD4Uo6p8JvqzZOWVzceZa}
    validationQuery: SELECT 1 
druid:
  stat:
    ## 连接数据库的额外参数 
    slowSqlMillis: 3000
    mergeSql: true
security:
  oauth2:
    resource:
      #将我们的资源拦截的过滤器运行顺序放到第3个执行,也就是在oauth2的认证服务器后面执行
      filter-order: 3
# 打印sql
logging:
  level:
    com.matridx.server: debug
##myibatis 拦截配置
sql:
  interceptor:
    pagesqlid: .*getPaged*.*
    dialect: postgresql
##角色切换配置： 0不支持切换，1支持切换
matridx:
  role:
    switch: 1
  basictype:
    file: config/comm/basicType.xml
  imptype:
    file: config/comm/config-import.xml
  exptype:
    file: config/comm/config-export.xml
    limit: 500
  fileupload:
    prefix: 
    tempPath: /matridx/fileupload/temp/
    releasePath: /matridx/fileupload/release/
  file:
    ##文件导出存放路径
    exportFilePath: /matridx/download/
    ##文件保存路径前缀
    pathPrefix: 
    ##文件转换最大次数
    translimit: 5
  netty:
    port: 8094
    boss_size: 1
    work_size: 200
    ## cmd接收命令后同步还是异步执行 true: 异步执行  false:根据命令的最后一位进行同步还是异步
    cmd_exec_async: true
    #区域 默认01
    area: '01'
    #桥接 默认0，如果为1 ，则需要同时设置主服务器地址
    bridgingflg: false
    #主服务器注册地址
    defaultZone: 172.17.52.26
server:
  port: ${port:80}