
package com.neusoft.si.entrance.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "carryXmlToDbService", targetNamespace = "http://webservice.entrance.si.neusoft.com/", wsdlLocation = "http://192.26.64.134:8889/SJCJSJSCJKQ/SJSCQ?wsdl")
public class CarryXmlToDbService_Service
    extends Service
{

    private final static URL CARRYXMLTODBSERVICE_WSDL_LOCATION;
    private final static WebServiceException CARRYXMLTODBSERVICE_EXCEPTION;
    private final static QName CARRYXMLTODBSERVICE_QNAME = new QName("http://webservice.entrance.si.neusoft.com/", "carryXmlToDbService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.26.64.134:8889/SJCJSJSCJKQ/SJSCQ?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CARRYXMLTODBSERVICE_WSDL_LOCATION = url;
        CARRYXMLTODBSERVICE_EXCEPTION = e;
    }

    public CarryXmlToDbService_Service() {
        super(__getWsdlLocation(), CARRYXMLTODBSERVICE_QNAME);
    }

    public CarryXmlToDbService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CARRYXMLTODBSERVICE_QNAME, features);
    }

    public CarryXmlToDbService_Service(URL wsdlLocation) {
        super(wsdlLocation, CARRYXMLTODBSERVICE_QNAME);
    }

    public CarryXmlToDbService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CARRYXMLTODBSERVICE_QNAME, features);
    }

    public CarryXmlToDbService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CarryXmlToDbService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CarryXmlToDbService
     */
    @WebEndpoint(name = "CarryXmlToDbServiceImplPort")
    public CarryXmlToDbService getCarryXmlToDbServiceImplPort() {
        return super.getPort(new QName("http://webservice.entrance.si.neusoft.com/", "CarryXmlToDbServiceImplPort"), CarryXmlToDbService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CarryXmlToDbService
     */
    @WebEndpoint(name = "CarryXmlToDbServiceImplPort")
    public CarryXmlToDbService getCarryXmlToDbServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.entrance.si.neusoft.com/", "CarryXmlToDbServiceImplPort"), CarryXmlToDbService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CARRYXMLTODBSERVICE_EXCEPTION!= null) {
            throw CARRYXMLTODBSERVICE_EXCEPTION;
        }
        return CARRYXMLTODBSERVICE_WSDL_LOCATION;
    }

}
