package com.matridx.igams.common.enums;
/**
 * 审核类型枚举类
 * @author xinyf
 * @date 2015-5-20
 */
public enum AuditTypeEnum {
	AUDIT_PAPERREPORTAPPLY("AUDIT_PAPERREPORTAPPLY"),//纸质报告申请
	AUDIT_INVOICE("AUDIT_INVOICE"),//发票审核
	AUDIT_SALEORDER("AUDIT_SALEORDER"),//销售订单审核
	AUDIT_FREESAMPLES("AUDIT_FREESAMPLES"),//免费样本申请
	AUDIT_VIPSAMPLES("AUDIT_VIPSAMPLES"),//VIP样本申请
	AUDIT_PKSAMPLES("AUDIT_PKSAMPLES"),//PK样本申请
	AUDIT_SAMPAPPLY("AUDIT_SAMPAPPLY"),//标本申请
	AUDIT_COVID("AUDIT_COVID"),//新冠报告审核
	AUDIT_GENERAL_INSPECTION("AUDIT_GENERAL_INSPECTION"),//普检审核
	AUDIT_METRIEL("AUDIT_METRIEL"),		//物料编码申请
	AUDIT_BUSINESS_CONTRACT("AUDIT_BUSINESS_CONTRACT"),		//商务合同
	AUDIT_RISK_BOARD("AUDIT_RISK_BOARD"),		//风险上机
	AUDIT_METRIELMOD("AUDIT_METRIELMOD"),//物料修改申请
	QUALITY_FILE_ADD("QUALITY_FILE_ADD"),//文件申请
	QUALITY_FILE_MOD("QUALITY_FILE_MOD"),//文件修订申请
	AUDIT_GOODS_APPLY("AUDIT_GOODS_APPLY"),//领料申请
	AUDIT_GOODS_APPLY_DING("AUDIT_GOODS_APPLY_DING"),//领料申请DING
	AUDIT_GOODS_DEVICE("AUDIT_GOODS_DEVICE"),//设备领料审核
	AUDIT_BORROWING("AUDIT_BORROWING"),//借出借用申请
	AUDIT_REPAID("AUDIT_REPAID"),//借出归还审核
	AUDIT_GOODS_REAGENT("AUDIT_GOODS_REAGENT"),//质量检验审核（试剂）
	AUDIT_GOODS_THORGH("AUDIT_GOODS_THORGH"),//质量检验审核（退货或归还）
	AUDIT_GOODS_CONSUMABLE("AUDIT_GOODS_CONSUMABLE"),//质量检验审核（耗材）
	AUDIT_GOODS_ARRIVAL("AUDIT_GOODS_ARRIVAL"),//货物到货审核
	AUDIT_GOODS_PENDING("AUDIT_GOODS_PENDING"),//采购红字
	AUDIT_GOODS_INSTRUMENT("AUDIT_GOODS_INSTRUMENT"),//质量检验审核（仪器）
	AUDIT_GOODS_STORAGE("AUDIT_GOODS_STORAGE"),//入库审核
	AUDIT_RECHECK("AUDIT_RECHECK"),//复测审核  医学部在系统中提交复测
	AUDIT_ADDCHECK("AUDIT_ADDCHECK"),//加测审核  医学部在系统中提交加测
	AUDIT_ADDCHECK_REM("AUDIT_ADDCHECK_REM"),//加测去人源  医学部在系统中提交加测去人源
	AUDIT_LAB_RECHECK("AUDIT_LAB_RECHECK"),//实验室复测审核
	AUDIT_LAB_ADDCHECK("AUDIT_LAB_ADDCHECK"),//实验室加测审核
	AUDIT_LAB_ADDCHECK_REM("AUDIT_LAB_ADDCHECK_REM"),//实验室加测去人源
	AUDIT_OUT_RECHECK("AUDIT_OUT_RECHECK"),//外部复测审核  生信部数据量不足时自动调用
		AUDIT_DING_RECHECK("AUDIT_DING_RECHECK"),//钉钉复测审核   开放给外部销售人员在钉钉端提交复测申请
	AUDIT_LIBRARY("AUDIT_LIBRARY"),//文库审核
	AUDIT_SAMPNUM("AUDIT_SAMPNUM"),//标本量审核
	AUDIT_DEVICEINFO("AUDIT_DEVICEINFO"),//设备信息审核
	AUDIT_SAMPLE("AUDIT_SAMPLE"),//样本审核
	AUDIT_DEVICECHECK("AUDIT_DEVICECHECK"),//设备验收审核
	AUDIT_MEASURE("AUDIT_MEASURE"),//设备计量
	AUDIT_VERIFICATION("AUDIT_VERIFICATION"),//送检验证审核
	AUDIT_LAB_VERIFICATION("AUDIT_LAB_VERIFICATION"),//实验室送检验证审核
	AUDIT_REQUISITIONS("AUDIT_REQUISITIONS"),//请购审核
	AUDIT_CONTRACT("AUDIT_CONTRACT"), //合同申请
	AUDIT_REQUISITIONS_CANCEL("AUDIT_REQUISITIONS_CANCEL"),//取消请购审核
	AUDIT_GOODS_BACK("AUDIT_GOODS_BACK"),//货物退回审核
	AUDIT_REQUISITIONS_ADMINISTRATION("AUDIT_REQUISITIONS_ADMINISTRATION"),//请购审核(行政)
	AUDIT_REQUISITIONS_DEVICE("AUDIT_REQUISITIONS_DEVICE"),//请购审核(设备)
	AUDIT_REQUISITIONS_SERVICE("AUDIT_REQUISITIONS_SERVICE"),//请购审核(服务)
	AUDIT_REQUISITIONS_OUTSOURCE("AUDIT_REQUISITIONS_OUTSOURCE"),//请购审核(委外)
	AUDIT_GOODS_DELIVERY("AUDIT_GOODS_DELIVERY"),//领料出库
	AUDIT_CONTRACT_PAYMENT("AUDIT_CONTRACT_PAYMENT"),//合同付款申请
    AUDIT_ADMINISTRATION("AUDIT_ADMINISTRATION"),//行政领料审核
    AUDIT_ADMINISTRATION_DEVICE("AUDIT_ADMINISTRATION_DEVICE"),//行政领料审核(设备)
	AUDIT_INSTORE("AUDIT_INSTORE"),//行政入库审核
	AUDIT_ADMINISTRATIONCONFIRMPURCHASE("AUDIT_ADMINISTRATIONCONFIRMPURCHASE"),//行政请购确认审核
	AUDIT_ADMINPURCHASEPAY("AUDIT_ADMINPURCHASEPAY"),//行政请购付款审核(月结)
	AUDIT_ADMINPURCHASEPAY_PTP("AUDIT_ADMINPURCHASEPAY_PTP"),//行政请购付款审核(公对公)
	AUDIT_REQUISITIONSTWO("AUDIT_REQUISITIONSTWO"),//OA请购审核
	AUDIT_SHIPPING("AUDIT_SHIPPING"),//发货审核
	AUDIT_CONTRACT_OA("AUDIT_CONTRACT_OA"), //OA合同申请
	AUDIT_FG_PLAN("AUDIT_FG_PLAN"), //成品需求计划
	AUDIT_YQ_PRODUCE("AUDIT_YQ_PRODUCE"), //生产指令仪器1
	AUDIT_YQ_PRODUCE_TWO("AUDIT_YQ_PRODUCE_TWO"), //生产指令仪器2
	AUDIT_YQ_PRODUCE_THREE("AUDIT_YQ_PRODUCE_THREE"), //生产指令仪器3
	AUDIT_YQ_PRODUCE_FOUR("AUDIT_YQ_PRODUCE_FOUR"), //生产指令仪器4
	AUDIT_YQ_PRODUCE_FIVE("AUDIT_YQ_PRODUCE_FIVE"), //生产指令仪器5
	AUDIT_YQ_PRODUCE_SIX("AUDIT_YQ_PRODUCE_SIX"), //生产指令仪器6
	AUDIT_YQ_PRODUCE_SEVEN("AUDIT_YQ_PRODUCE_SEVEN"), //生产指令仪器7
	AUDIT_YQ_PRODUCE_EIGHT("AUDIT_YQ_PRODUCE_EIGHT"), //生产指令仪器8
	AUDIT_YQ_PRODUCE_NINE("AUDIT_YQ_PRODUCE_NINE"), //生产指令仪器9
	AUDIT_YQ_PRODUCE_TEN("AUDIT_YQ_PRODUCE_TEN"), //生产指令仪器10
	AUDIT_SJ_PRODUCE("AUDIT_SJ_PRODUCE"), //生产指令试剂1
	AUDIT_SJ_PRODUCE_TWO("AUDIT_SJ_PRODUCE_TWO"), //生产指令试剂2
	AUDIT_SJ_PRODUCE_THREE("AUDIT_SJ_PRODUCE_THREE"), //生产指令试剂3
	AUDIT_SJ_PRODUCE_FOUR("AUDIT_SJ_PRODUCE_FOUR"), //生产指令试剂4
	AUDIT_SJ_PRODUCE_FIVE("AUDIT_SJ_PRODUCE_FIVE"), //生产指令试剂5
	AUDIT_SJ_PRODUCE_SIX("AUDIT_SJ_PRODUCE_SIX"), //生产指令试剂6
	AUDIT_SJ_PRODUCE_SEVEN("AUDIT_SJ_PRODUCE_SEVEN"), //生产指令试剂7
	AUDIT_SJ_PRODUCE_EIGHT("AUDIT_SJ_PRODUCE_EIGHT"), //生产指令试剂8
	AUDIT_SJ_PRODUCE_NINE("AUDIT_SJ_PRODUCE_NINE"), //生产指令试剂9
	AUDIT_SJ_PRODUCE_TEN("AUDIT_SJ_PRODUCE_TEN"), //生产指令试剂10
	AUDIT_SJ_PRODUCE_ELEVEN("AUDIT_SJ_PRODUCE_ELEVEN"), //生产指令试剂11
	AUDIT_SJ_PRODUCE_TWELVE("AUDIT_SJ_PRODUCE_TWELVE"), //生产指令试剂12
	AUDIT_SJ_PRODUCE_THIRTEEN("AUDIT_SJ_PRODUCE_THIRTEEN"), //生产指令试剂13
	AUDIT_SJ_PRODUCE_FOURTEEN("AUDIT_SJ_PRODUCE_FOURTEEN"), //生产指令试剂14
	AUDIT_SJ_PRODUCE_FIFTEEN("AUDIT_SJ_PRODUCE_FIFTEEN"), //生产指令试剂15
	AUDIT_SJ_STRUCTURE("AUDIT_SJ_STRUCTURE"), //产品结构
	AUDIT_TRAIN("AUDIT_TRAIN"), //培训审核
	AUDIT_RFS_FC("AUDIT_RFS_FC"), //送检RFS 复测项目生贺
	AUDIT_RFS_SJ("AUDIT_RFS_SJ"), //送检RFS 送检项目生贺
	RETURN_GOODS("RETURN_GOODS"), //退货
	AUDIT_GERM_PICK("AUDIT_GERM_PICK"),//菌种领料审核
	AUDIT_PERFORMANCE_TEMPLATE("AUDIT_PERFORMANCE_TEMPLATE"),//绩效模板审核
	AUDIT_PERFORMANCE("AUDIT_PERFORMANCE"),//绩效审核
	AUDIT_QUALITYAGREEMENT("AUDIT_QUALITYAGREEMENT"),//质量协议审核
	AUDIT_MARKETING_CONTRACT("AUDIT_MARKETING_CONTRACT"),//营销合同审核
	AUDIT_BUSINESS_PAYMENT_APPLICATION("AUDIT_BUSINESS_PAYMENT_APPLICATION"),//商务付款申请审核
	AUDIT_BUSINESS_INVOICE_APPLICATION("AUDIT_BUSINESS_INVOICE_APPLICATION"),//商务开票申请审核
	AUDIT_DEVICE_METERING("AUDIT_DEVICE_METERING"),//设备计量审核
	AUDIT_TURN_METERING("AUDIT_TURN_METERING"),//设备移交审核
	AUDIT_DEVICE_All("AUDIT_DEVICE_All"),//设备验收审核(总)
	AUDIT_DEVICE_TEST("AUDIT_DEVICE_TEST"),//设备验证审核
	AUDIT_DEVICE_SCRAP("AUDIT_DEVICE_SCRAP"),//设备报废审核
	AUDIT_DETECTIONAPPLICATION("AUDIT_DETECTIONAPPLICATION"),//检出申请审核
	AUDIT_DEVICE_UPKEEP("AUDIT_DEVICE_UPKEEP"),//设备维修保养审核
	AUDIT_DEVICE_STOCKRETURN("AUDIT_DEVICE_STOCKRETURN"),//设备退库申请审核
	AUDIT_EQUIPMENT_INVENTORY("AUDIT_EQUIPMENT_INVENTORY"),//设备盘点审核
	AUTID_SAMPLE_ALLOT("AUTID_SAMPLE_ALLOT"),//样本调拨审核
	AUDIT_CLEARING_RECORDS("AUDIT_CLEARING_RECORDS"),//清场记录审核
	AUDIT_VERIFICATION_APPLICATION("AUDIT_VERIFICATION_APPLICATION"),//供方验证申请审核
	AUDIT_VERIFICATION_AUDIT("AUDIT_VERIFICATION_AUDIT"),//供方验证审核
	AUDIT_SUPPLIER_EVALUATION("AUDIT_SUPPLIER_EVALUATION"),//供方评价审核
	AUDIT_ZDHYHHX("AUDIT_ZDHYHHX"),//自动化用户信息
	AUDIT_SUPPLIER_PERFORMANCE("AUDIT_SUPPLIER_PERFORMANCE"),//供方绩效审核
	AUDIT_PERFORMANCE_CHECK("AUDIT_PERFORMANCE_CHECK"),//绩效核算
	;
	
	private final String code;
	
	AuditTypeEnum(String code) {
		this.code = code;
	}
	
	public String getCode() {
		return code;
	}

	public static AuditTypeEnum getByCode(String code) {
		for (AuditTypeEnum auditTypeEnum : AuditTypeEnum.values()) {
			if (auditTypeEnum.getCode().equals(code)) {
				return auditTypeEnum;
			}
		}
		return null;
	}
}
