package com.matridx.igams.common.enums;

/**
 * 基础数据类别枚举类
 * 
 * @author fuwb
 * @time 20150401
 */
public enum BasicDataTypeEnum {
	APPLICATION_REASON("APPLICATION_REASON"),//申请原因
	ASSET_CLASS("ASSET_CLASS"),//资产类别
	ASSET_GROUP("ASSET_GROUP"),//资产组
	INCREASE_MODE("INCREASE_MODE"),//增加方式
	USE_STATUES("USE_STATUES"),//使用状况
	DEPRECIATION_METHOD("DEPRECIATION_METHOD"),//折旧方法
	DEPRECIATION_ACCOUNT("DEPRECIATION_ACCOUNT"),//折旧科目
	APPLICATION_ITEM("APPLICATION_ITEM"),//申请项目
	APPLICATION_SUBITEM("APPLICATION_SUBITEM"),//申请子项目
	SAMPLE_TYPE("SAMPLE_TYPE"),//标本类型
	UNIT_SOURCE("UNIT_SOURCE"),//来源单位
	MATERIEL_TYPE("MATERIEL_TYPE"),//物料类别
	MATERIEL_SAFE_TYPE("MATERIEL_SAFE_TYPE"),//物料安全类别
	MATERIELQUALITY_TYPE("MATERIELQUALITY_TYPE"),//物料质量类别
	MATERIEL_SUBTYPE("MATERIEL_SUBTYPE"),//物料子类别
	DOCUMENT_TYPE("DOCUMENT_TYPE"),//文件分类
	DOCUMENT_SUBTYPE("DOCUMENT_SUBTYPE"),//文件类别
	RESEARCH_TYPE("RESEARCH_TYPE"),//研发类型
	TASK_TYPE("TASK_TYPE"),//任务类型
	TASK_URGENT("TASK_URGENT"),//任务紧急度
	/**首页类型**/
	HOME_PAGE_TYPE("HOME_PAGE_TYPE"),
	/**标本用途**/
	SAMPLE_USE("SAMPLE_USE"),
	PROVINCE("PROVINCE"), // 省份
	PERUNIT_TYPE("PERUNIT_TYPE"), // 借用单位类型
	CITY("CITY"), // 城市
	DISTRICT("DISTRICT"), // 县区
	TASK_LABEL("TASK_LABEL"),//任务标签
	TASK_RANK("TASK_RANK"),//任务级别
	JOB_RANK("JOB_RANK"),//职级
	REPORT_TEMEPLATE("REPORT_TEMEPLATE"),//报告模板
	WECGATSAMPLE_TYPE("WECGATSAMPLE_TYPE"),//微信标本类型
	GENERALSAMPLE_TYPE("GENERALSAMPLE_TYPE"),//普检标本类型
	DETECT_TYPE("DETECT_TYPE"),//检测项目
	RYNYJY_TYPE("RYNYJY_TYPE"),//入院耐药基因
	RFS_RESULTS_TYPE("RFS_RESULTS_TYPE"),//ResFirst™检测结果
	DETECT_SUBTYPE("DETECT_SUBTYPE"),//检测子项目
	GENDER_TYPE("GENDER_TYPE"),//性别
	CLINICAL_TYPE("CLINICAL_TYPE"),//临床症状
	DETECTION_TYPE("DETECTION_TYPE"),//前期检测
	PATHOGENY_TYPE("PATHOGENY_TYPE"),//病原
	UNIT_TYPE("UNIT_TYPE"), //单位
	PROJECT_GROUP("PROJECT_GROUP"),
	SAMPLESTATE("SAMPLESTATE"),//标本状态
	WAREHOUSE_TYPE("WAREHOUSE_TYPE"),//仓库类别
	GROUPING("GROUPING"),//分组
	HWXX_CHECK("HWXX_CHECK"),//验收情况;
	FIRST_SJXXKZ("FIRST_SJXXKZ"),//送检扩展1
	SECOND_SJXXKZ("SECOND_SJXXKZ"),//送检扩展2
	THIRD_SJXXKZ("THIRD_SJXXKZ"),//送检扩展3
	FOURTH_SJXXKZ("FOURTH_SJXXKZ"),//送检扩展4
	PROCESS_TYPE("PROCESS_TYPE"),//流程类别
	SUPPLIER_TYPE("SUPPLIER_TYPE"),//供应商管理类别
	KHGL_TYPE("KHGL_TYPE"),//客户管理类型
	CLASSIFY("CLASSIFY"),//合作伙伴分类
	SUBCLASSIFICATION("SUBCLASSIFICATION"),//合作伙伴子分类
	PARTNER_TYPE("PARTNER_TYPE"),//伙伴类型
	PARTNER_LEVEL("PARTNER_LEVEL"),//伙伴级别
	REPORTWAY_TYPE("REPORTWAY_TYPE"),//报告方式
	STAMP_TYPE("STAMP_TYPE"),//盖章类型
	BODYTEMP_TYPE("BODYTEMP_TYPE"),//体温类型
	SYMPTOM_TYPE("SYMPTOM_TYPE"),//症状类型
	CRP_TYPE("CRP_TYPE"),//CRP类型
	PCT_TYPE("PCT_TYPE"),//PCT类型
	LEUKOCYTEL_TYPE("LEUKOCYTEL_TYPE"),//白细胞类型
	NEUTROPHILS_TYPE("NEUTROPHILS_TYPE"),//中性粒类型
	SD_TYPE("SD_TYPE"),//快递类型
	DETECTION_UNIT("DETECTION_UNIT"),//检测单位
	XXXJ_TYPE("XXXJ_TYPE"),//信息小结类型
	DETECTION_UNIT_EXTEND("DETECTION_UNIT_EXTEND"),//检测单位扩展
	NUMBERJING_CATEGORY("NUMBERJING_CATEGORY"),//编号类别
	MANAGEMENT_CATEGORY("MANAGEMENT_CATEGORY"),//管理类别
	INFORMATION_TYPE("INFORMATION_TYPE"),//信息类型
	EXCEPTION_DISTINGUISH("EXCEPTION_DISTINGUISH"),//异常区分
	EXCEPTION_SUBDISTINGUISH("EXCEPTION_SUBDISTINGUISH"),//异常子区分
	EXCEPTION_TYPE("EXCEPTION_TYPE"),//异常类型

	NODECODE_XIANSHENG("NODECODE_XIANSHENG"),//先声code对应
	SUBCLASSEXCEPTION_TYPE("SUBCLASSEXCEPTION_TYPE"),//异常子类别
	VISITUNIT_CLASSIFY("VISITUNIT_CLASSIFY"),//拜访单位分类
	VISITUNIT_TYPE("VISITUNIT_TYPE"),//拜访单位类别
	VISITUNIT_GRADE("VISITUNIT_GRADE"),//拜访单位等级
	VISITUNIT_RATING("VISITUNIT_RATING"),//客户分级
	VISITCUSTOMER_SOURCE("VISITCUSTOMER_SOURCE"),//拜访客户来源
	FREQUENCY_TYPE("FREQUENCY_TYPE"),//频率类型
	VISITRECORDS_TYPE("VISITRECORDS_TYPE"),//拜访记录类别
	VISITRECORDS_DISTINGUISH("VISITRECORDS_DISTINGUISH"),//拜访记录区分
	NEWS_CLASS("NEWS_CLASS"),//资讯类别
	NEWS_SUBCLASS("NEWS_SUBCLASS"),//资讯子类型
	CALIBRATION_METHOD("CALIBRATION_METHOD"),//检定方法
	VERIFICATION_TYPE("VERIFICATION_TYPE"),//送检验证方法
	VERIFICATION_RESULT("VERIFICATION_RESULT"),//送检报告结果
	CLIENT_NOTICE("CLIENT_NOTICE"),//客户通知
	DISTINGUISH("DISTINGUISH"),//区分
	SELFEXEMPTION_PROJECT("SELFEXEMPTION_PROJECT"),//自免项目
	SELFEXEMPTION_DESTINATION("SELFEXEMPTION_DESTINATION"),//自免目的地
	SEND_TYPE("SEND_TYPE"),//发送类型
	PURCHASE_ITEMENCODING("PURCHASE_ITEMENCODING"),//项目编码
	PURCHASE_CLASS_ITEMENCODING("PURCHASE_CLASS_ITEMENCODING"),//项目大类
	PAYMENT_TYPE("PAYMENT_TYPE"),//支付方式
	PAYER("PAYER"),//付款方
	CONTRACT_PAYEY("CONTRACT_PAYEY"),//合同付款方
	ANTIBODY("ANTIBODY"), //副瘤性神经综合征抗体
	MATERIEL_SUBTYPE_COLLECTIVELY("MATERIEL_SUBTYPE_COLLECTIVELY"),//物料子类别统称
	USER_DISTINGUISH("USER_DISTINGUISH"),//用户区分
	USER_SUB_DISTINGUISH("USER_SUB_DISTINGUISH"),//用户子区分
	SYSTEM_CODE("SYSTEM_CODE"),//系统代码
	INVOICE_APPLICATION("INVOICE_APPLICATION"),//开票申请
	INSPECTION_DIVISION("INSPECTION_DIVISION"),//送检区分
	QUERY_DIVISION("QUERY_DIVISION"),//查询区分
	DISPLAY_MODE("DISPLAY_MODE"),//显示方式
	RECHECK("RECHECK"),//复检&加测&去人源
	PAYMENT_METHOD("PAYMENT_METHOD"),//付款方式
	PAYMENTBACK_METHOD("PAYMENTBACK_METHOD"),//回款方式
	INVOICE_METHOD("INVOICE_METHOD"),//发票方式
	CONTRACT_TYPE("CONTRACT_TYPE"),//合同类型
	CURRENCY("CURRENCY"),//币种
	TEXT_TEMPID("TEXT_TEMPID"), //文本语音模板id
	INVOICE_CLASS("INVOICE_CLASS"),//发票种类
	INVOICE_TYPE("INVOICE_TYPE"),//发票类型
	INVOICE_BODY("INVOICE_BODY"),//开票主体
	CUSTOMER_BUSINESS_TYPE("CUSTOMER_BUSINESS_TYPE"),//客户业务分类
	DINGTALK_AUDTI_CALLBACK_TYPE("DINGTALK_AUDTI_CALLBACK_TYPE"),//钉钉审批回调类型
	AUDIT_TYPE("AUDIT_TYPE"),//审批类型
	DINGTALK_CALLBACK_PREFIX("DINGTALK_CALLBACK_PREFIX"),//钉钉审批回调前缀
	MESSAGE_TYPE("MESSAGE_TYPE"),//消息类型
    POOLING_TEMPLATE("POOLING_TEMPLATE"),//pooling模板
	MACHINE_TYPE("MACHINE_TYPE"),//仪器类型
	REAGENT_SELECT("REAGENT_SELECT"),//试剂选择
    INBOUND_TYPE("INBOUND_TYPE"),//入库类别
	BOM_TYPE("BOM_TYPE"),//BOM类别
	SCBOM_TYPE("SCBOM_TYPE"),//生产BOM类别
	SUPPLY_TYPE("SUPPLY_TYPE"),//供应类别
	OUTPUT_TYPE("OUTPUT_TYPE"),//产出类别
	RISKY_ACTIONS("RISKY_ACTIONS"),//标本处理
    PURCHASE_TYPE("PURCHASE_TYPE"),//采购类型
    SALE_TYPE("SALE_TYPE"),//销售目标类型
	SALE_CLASSIFY("SALE_CLASSIFY"),//销售分类
	SALE_SUBCLASSIFY("SALE_SUBCLASSIFY"),//销售子分类
	AUDITGOODS_BACK_TYPE("AUDITGOODS_BACK_TYPE"),//退回类型
	PURCHASE_SUB_TYPE("PURCHASE_SUB_TYPE"),//请购类型，区分物料请购，服务，设备，行政等
	XXDY_TYPE("XXDY_TYPE"),//信息对应
	DETECTION_PROJECT_TYPE("DETECTION_PROJECT_TYPE"),//检测类型
	RESEARCH_ITEM("RESEARCH_ITEM"),//所属研发项目
	DELIVERY_TYPE("DELIVERY_TYPE"), //出库类别
	DELIVERY_RECEIPTS_TYPE("DELIVERY_RECEIPTS_TYPE"), //出库单据类别
	QUALITY_REQUIRE("QUALITY_REQUIRE"),//质量要求
	PRODUCTION_TYPE("PRODUCTION_TYPE"),//产品类别（所属产品类别）
	PCR_TEMPLATE("PCR_TEMPLATE"),//PCR运行设置模板
	PCRMACHINE_ID("PCRMACHINE_ID"),//PCR仪器型号ID
	REFUND_METHOD("REFUND_METHOD"),//退款方式
	DINGMESSAGETYPE("DINGMESSAGETYPE"),//钉钉消息类型
	DISCHARGESTATUS("DISCHARGESTATUS"),//出院状态
	QMNGSDISCHARGESTATUS("QMNGSDISCHARGESTATUS"),//QMNGS出院状态
	TREATMENTDEPARTMENT("TREATMENTDEPARTMENT"),//就诊科室
	PATIENTCATEGORY("PATIENTCATEGORY"),//病人类别
	QMNGSPATIENTCATEGORY("QMNGSPATIENTCATEGORY"),//Q-MNGS病人类别
	COMPLICATION("COMPLICATION"),//既往合并症
	QMNGSCOMPLICATION("QMNGSCOMPLICATION"),//Q-MNGS既往合并症
	HOSPITAL("HOSPITAL"),//医院
	QUESTIONBANK_TYPE("QUESTIONBANK_TYPE"),//题库类别
	ANTIBACTERIALHISTORY("ANTIBACTERIALHISTORY"),//感染部位及既往抗菌药物暴露史
	QMNGSANTIBACTERIALHISTORY("QMNGSANTIBACTERIALHISTORY"),//QMNGS感染部位及既往抗菌药物暴露史
	QMNGSGROUPRESULT("QMNGSGROUPRESULT"),//QMNGS患者分组结果
	QMNGSFREQUENCY("QMNGSFREQUENCY"),//QMNGS频次
	QMNGSMEDICATIONBASIS("QMNGSMEDICATIONBASIS"),//QMNGS用药依据
	QMNGSDRUGSTOPREASONS("QMNGSDRUGSTOPREASONS"),//QMNGS停药原因
	QMNGS72EFFICACYJUDGMENT("QMNGS72EFFICACYJUDGMENT"),//QMNGS感染相关临床疗效判定
	QMNGSINFECTIONDIAGNOSIS("QMNGSINFECTIONDIAGNOSIS"),//QMNGS感染相关诊断
	REPORTMODEL("REPORTMODEL"),//模板
	TEST_RESULT("TEST_RESULT"), //检验结果
	PAYAPPLY_PAYER("PAYAPPLY_PAYER"),//付款申请付款方
	PAYAPPLY_PAYWAY("PAYAPPLY_PAYWAY"),//付款申请付款方式
	JAVA_SERVER("JAVA_SERVER"), //Java服务器
	TRAINCATEGORY("TRAINCATEGORY"), //培训类别
	SUBCLASSTRAINCATEGORY("SUBCLASSTRAINCATEGORY"), //培训子类别
	PAY_BELONG("PAY_BELONG"),//费用归属
	SUBGROUP("SUBGROUP"), //亚组分类
	MOLECULAR_DETECTION("MOLECULAR_DETECTION"),//分子检测类型
	MOLECULAR_OBJECT("MOLECULAR_OBJECT"),//分子检测对象类型
	MOLECULAR_SAMPLE("MOLECULAR_SAMPLE"),//分子标本类型
	MOLECULAR_ITEM("MOLECULAR_ITEM"),//分子检测项目
	MOLECULAR_SUBITEM("MOLECULAR_SUBITEM"),//分子检测子项目
	IDCARD_CATEGORY("IDCARD_CATEGORY"),//证件类型
	MOLECULAR_DETECTION_RESULT("MOLECULAR_DETECTION_RESULT"),//分子检测结果
	VERIFY_RESULT("VERIFY_RESULT"),//验证结果
	XG_SAMPLESTATE("XG_SAMPLESTATE"),//新冠标本状态
	GENERAL_SAMPLESTATE("GENERAL_SAMPLESTATE"),//普检标本状态
	HOLIDAY_TYPE("HOLIDAY_TYPE"),//假期类型
	RECHECK_REASON("RECHECK_REASON"),//复测加测原因
	SELLING_TYPE("SELLING_TYPE"),//销售类型
	MARKET_SELLING_TYPE("MARKET_SELLING_TYPE"),//营销销售类型
	ATTENDANCE_STATUS("ATTENDANCE_STATUS"),//出勤状态
	CK_PERMISSIONS_TYPE("CK_PERMISSIONS_TYPE"),//仓库分类
	DELIVERY_METHOD("DELIVERY_METHOD"),//运送方式
	ARRIVAL_CATEGORY("ARRIVAL_CATEGORY"),//到货类别 
	TYPEOF_SERVICE("TYPEOF_SERVICE"), //业务类型
	STAFF_TYPE("STAFF_TYPE"),//员工类型
	RECONCILIATION_TYPE("RECONCILIATION_TYPE"),//对账类型/医检对账周期
	RISK_TYPE("RISK_TYPE"),//风险类别
	LIBRARY_TEMPLATE("LIBRARY_TEMPLATE"),//文库模板
	COLLECT_SAMPLES("COLLECT_SAMPLES"),//采样点
	VISIT_TYPE("VISIT_TYPE"),//就诊类型
	CASE_ENROLLMENT_UNIT("CASE_ENROLLMENT_UNIT"),//病例入组单位
	DEPARTMENT_TYPE("DEPARTMENT_TYPE"),//科室
	JNSJCDIZQYYS("JNSJCDIZQYYS"),//艰难梭菌治疗
	JNSJKS("JNSJKS"),//艰难梭菌科室
	JNSJDW("JNSJDW"),//艰难梭菌单位
	PREPARATIVE_METHOD("PREPARATIVE_METHOD"),//制备法
	YQ_PROPERTY_TYPE("YQ_PROPERTY_TYPE"),//仪器属性类型
	YQ_PROCESS_TYPE("YQ_PROCESS_TYPE"),//实验室流程类型
	HBPXGHXYW("HBPXGHXYW"),//HBP血管活性药物
	HBPQZBB("HBPQZBB"),//HBP确诊标本
	HBPGRBW("HBPGRBW"),//HBP感染部位
	HBPJWBS("HBPJWBS"),//HBP既往病史
	DOCUMENTNUM("DOCUMENTNUM"),//文件编码
	CONTRACT_RISK("CONTRACT_RISK"),//合同风险程度
	CONTRACT_CLASSIFY("CONTRACT_CLASSIFY"),//合同分类
	CONTRACT_SUB_CLASSIFY("CONTRACT_SUB_CLASSIFY"),//合同子分类
	INVOICE_OBJECT("INVOICE_OBJECT"),//开票对象
	CONTRACT_CHAPTERS("CONTRACT_CHAPTERS"),//合同用章
	SALE_CATEGORY("SALE_CATEGORY"),//销售类别
	PRODUCTS_TYPE("PRODUCTS_TYPE"),//生产产品类别
	LOCATION_CATEGORY("LOCATION_CATEGORY"),//库位类别
	DISPATCH_TYPE("DISPATCH_TYPE"),//收发类别
	RECEIPTS_TYPE("RECEIPTS_TYPE"),//单据类型
	SENDING_METHOD("SENDING_METHOD"),//寄送方式
	EXPENSE_TYPE("EXPENSE_TYPE"),//报销类型
	RESEARCH_PROJECT("RESEARCH_PROJECT"),//科研项目
	TUMOR_JUDGEMENT("TUMOR_JUDGEMENT"),//肿瘤判断
	MODEL_PREDICTION("MODEL_PREDICTION"),//模型预测
	TUMOR_RESULT("TUMOR_RESULT"),//肿瘤结果
	JUDGE_REASON("JUDGE_REASON"),//判断原因
	SAMPLE_ENTRY_TYPE("SAMPLE_ENTRY_TYPE"),//样本录入类型

	SEQUENCER_CODE("SEQUENCER_CODE"),//测序仪
	GENERAL_RESULT("GENERAL_RESULT"),//普检结果
	FILETYPE_PERMISSION_SETTINGS("FILETYPE_PERMISSION_SETTINGS"), //文件类型权限设置
	RECEIPTS_TRANSMIT_TYPE("RECEIPTS_TRANSMIT_TYPE"),//单据传达方式
	MEETING_FEE_EXPENSE_SUBJECT("MEETING_FEE_EXPENSE_SUBJECT"),//会议费报销科目
	PRODUCT_CLASS("PRODUCT_CLASS"),//产品类型
	ADMINISTRATION_INBOUND_TYPE("ADMINISTRATION_INBOUND_TYPE"),//行政入库类别
	OBSERVATION_REQUIREMENTS("OBSERVATION_REQUIREMENTS"),//留样观察要求
	DEVICE_NUMBER("DEVICE_NUMBER"),//设备编号
	ACCOUNT_TYPE("ACCOUNT_TYPE"),//账套类型
	AFFILIATED_COMPANY("AFFILIATED_COMPANY"),//所属公司
	CUSTOMER_CATEGORY("CUSTOMER_CATEGORY"),//客户类别
	EXPENSE_CATEGORY("EXPENSE_CATEGORY"),//费用类别
	GERM_CLASS("GERM_CLASS"),//菌种分类
	GERM_TYPE("GERM_TYPE"),//菌种类型
	MATERIAL_CLASSIFICATION("MATERIAL_CLASSIFICATION"),//物料分类
	NOTIF_GROUP("NOTIF_GROUP"),//通知群
	STYLE("STYLE"),//样式
	EQUIPMENT_TYPE("EQUIPMENT_TYPE"),//设备类型
	ASSESSMENT_TYPE("ASSESSMENT_TYPE"),//考核类型
	ASSESSMENT_PERIOD("ASSESSMENT_PERIOD"),//考核周期
	TEMPLATE_LEVEL("TEMPLATE_LEVEL"),//模板级别
	TEMPLATE_TYPE("TEMPLATE_TYPE"),//模板类型
	TEMPLATE_MESSAGE("TEMPLATE_MESSAGE"),//消息模版
	TEMPLATE_SUBTYPE("TEMPLATE_SUBTYPE"),//模板子类型
	PLATFORM_OWNERSHIP("PLATFORM_OWNERSHIP"),//销售部门
	PLATFORM_OWNERSHIP_ORIGIN("PLATFORM_OWNERSHIP_ORIGIN"),//平台归属
	CHAPTER_TYPE("CHAPTER_TYPE"),//用章类型
	MARKETING_CONTRACT_TYPE("MARKETING_CONTRACT_TYPE"),//营销合同类型
	EXCEPTION_COPY_TYPE("EXCEPTION_COPY_TYPE"),//异常复制类型

	FEEDBACK_DISTINGUISH("FEEDBACK_DISTINGUISH"),//反馈区分

	DEVICE_TURN_REASON("DEVICE_TURN_REASON"),//设备移交原因
	DECONTAMINATION_METHOD("DECONTAMINATION_METHOD"),//去污方式
	DETECTIONAPPLICATION_TYPE("DETECTIONAPPLICATION_TYPE"),//检出申请类型
	ACCOUNT_U8("ACCOUNT_U8"),//U8账套
	REPORT_FORMS("REPORT_FORMS"),//报表
	ACCOUNT_SUBJECT("ACCOUNT_SUBJECT"),//报表科目
	ACCOUNT_SUB_SUBJECT("ACCOUNT_SUB_SUBJECT"),//报表子科目
	RECONCILIATION_FIELD("RECONCILIATION_FIELD"),//对账字段

	EXCEPTION_STATISTICS("EXCEPTION_STATISTICS"),//异常类型
	SALEFEEDBACK_TYPE("SALEFEEDBACK_TYPE"),//售后反馈类型
	TRAINING_METHODS("TRAINING_METHODS"),//培训方式
	COMPLAINT_SOURCE("COMPLAINT_SOURCE"),//投诉来源
	AWARD_TYPE("AWARD_TYPE"),//奖品类型
    CLEARING_PROJECT("CLEARING_PROJECT"),//清场项目
	HOMEPAGE_PROCESS_TYPE("HOMEPAGE_PROCESS_TYPE"),//首页流程类型
	ACCOUNT_SUBJECT_TWO("ACCOUNT_SUBJECT_TWO"),//报表科目(非重复)
	ACCOUNT_SUB_SUBJECT_TWO("ACCOUNT_SUB_SUBJECT_TWO"),//报表子科目(非重复)
	YXHT_TYPE("YXHT_TYPE"),//营销合同类型
	QRCODE_SETTING("QRCODE_SETTING"),
	EVALUATION_TYPE("EVALUATION_TYPE"),//评估类型
	EVALUATION_ITEM("EVALUATION_ITEM"),//评估项目
	EVALUATION_CONTENT("EVALUATION_CONTENT"),//评估内容
	EVALUATION_GRADE("EVALUATION_GRADE"),//评估等级
	RANGE_OF_PRICE("RANGE_OF_PRICE"),//价格范围
	DEVICE_TYPE("DEVICE_TYPE"),
	QUALITY_SAMPLE_SETTING("QUALITY_SAMPLE_SETTING"),//质控标本设置
	DISCOUNT_CLASSIFY("DISCOUNT_CLASSIFY"),
	DISCOUNT_SUBCLASSIFY("DISCOUNT_SUBCLASSIFY"),
	DISCOUNT_PROJECT_CORRESPOND("DISCOUNT_PROJECT_CORRESPOND"),
	DISCOUNT_FORM("DISCOUNT_FORM"),
	APPROVAL_SYNCHRONIZATION_PERMISSIONS("APPROVAL_SYNCHRONIZATION_PERMISSIONS"),//审批同步权限
	WHITELIST_INSP_CONFIRM("WHITELIST_INSP_CONFIRM"),//白名单(外部接口样本接收)
	LIBRARY_SUFFIX("LIBRARY_SUFFIX"),//文库后缀类型

	;
	//TRANSVERSE_PROJECT_TYPE("TRANSVERSE_PROJECT_TYPE"); // 横向项目类型


	private final String code;

	BasicDataTypeEnum(String code) {
		this.code = code;
	}

	public String getCode() {
		return code;
	}
}