package com.matridx.igams.common.enums;

/**
 * 业务类型枚举类
 * 
 * @author fuwb
 * @time 20150512
 */
public enum BusTypeEnum {
	IMP_MATER("IMP_MATER"),//物料导入
	IMP_BUSINESS_CONTRACT("IMP_BUSINESS_CONTRACT"),//商务合同
	IMP_RISK_BOARD("IMP_RISK_BOARD"),//风险上机
	IMP_CHAPTER_CONTRACT("IMP_CHAPTER_CONTRACT"),//双章合同
	IMP_BUSINESS_PARTNERS("IMP_BUSINESS_PARTNERS"),//商务客户
	IMP_DOCUMENT("IMP_DOCUMENT"),//文件导入
	IMP_IMPORTDOCUMENT("IMP_IMPORTDOCUMENT"),//文件批量导入
	IMP_DOCUMENT_BATCH("IMP_DOCUMENT_BATCH"),//文件批量导入
	IMP_SIGNATURE("IMP_SIGNATURE"),//签名导入
	IMP_TASK("IMP_TASK"),//任务导入
	IMP_RESEARCH("IMP_RESEARCH"),//研发导入
	IMP_SAMPLE("IMP_SAMPLE"),//标本导入
	IMP_PERFORMANCE_TEMPLATE("IMP_PERFORMANCE_TEMPLATE"),//绩效目标导入
	/*IMP_DETECTION("IMP_DETECTION"),//送检结果
	IMP_DETECTION_R("IMP_DETECTION_R"),//送检结果
	IMP_DETECTION_C("IMP_DETECTION_C"),//送检结果
	IMP_DETECTION_Z("IMP_DETECTION_Z"),//送检结果自免
	IMP_DETECTION_Q("IMP_DETECTION_Q"),//送检结果QmNGS
	IMP_DETECTION_Q_R("IMP_DETECTION_Q_R"),//送检结果QmNGS
	IMP_DETECTION_Q_C("IMP_DETECTION_Q_C"),//送检结果QmNGS
	IMP_DETECTION_REM("IMP_DETECTION_REM"),//送检结果[去人源]
	IMP_DETECTION_R_REM("IMP_DETECTION_R_REM"),//送检结果[去人源]
	IMP_DETECTION_C_REM("IMP_DETECTION_C_REM"),//送检结果[去人源]
	IMP_DETECTION_Q_REM("IMP_DETECTION_Q_REM"),//送检结果[去人源QmNGS]
	IMP_DETECTION_Q_R_REM("IMP_DETECTION_Q_R_REM"),//送检结果[去人源QmNGS]
	IMP_DETECTION_Q_C_REM("IMP_DETECTION_Q_C_REM"),//送检结果[去人源QmNGS]
	IMP_WORD_DETECTION("IMP_WORD_DETECTION"),//送检结果word(DNA)版
	IMP_WORD_DETECTION_R("IMP_WORD_DETECTION_R"),//送检结果word(RNA)版
	IMP_WORD_DETECTION_C("IMP_WORD_DETECTION_C"),//送检结果word(RNA+DNA)版
	IMP_WORD_DETECTION_Z("IMP_WORD_DETECTION_Z"),//送检结果word自免检测版
	IMP_WORD_DETECTION_Q("IMP_WORD_DETECTION_Q"),//送检结果word(DNA)版QmNGS
	IMP_WORD_DETECTION_Q_R("IMP_WORD_DETECTION_Q_R"),//送检结果word(RNA)版QmNGS
	IMP_WORD_DETECTION_Q_C("IMP_WORD_DETECTION_Q_C"),//送检结果word(RNA+DNA)版QmNGS
	IMP_WORD_DETECTION_REM("IMP_WORD_DETECTION_REM"),//送检结果word(DNA)版[去人源]
	IMP_WORD_DETECTION_R_REM("IMP_WORD_DETECTION_R_REM"),//送检结果word(RNA)版[去人源]
	IMP_WORD_DETECTION_C_REM("IMP_WORD_DETECTION_C_REM"),//送检结果word(RNA+DNA)版[去人源]
	IMP_WORD_DETECTION_Q_REM("IMP_WORD_DETECTION_Q_REM"),//送检结果word(DNA)版[去人源QmNGS]
	IMP_WORD_DETECTION_Q_R_REM("IMP_WORD_DETECTION_Q_R_REM"),//送检结果word(RNA)版[去人源QmNGS]
	IMP_WORD_DETECTION_Q_C_REM("IMP_WORD_DETECTION_Q_C_REM"),//送检结果word(RNA+DNA)版[去人源QmNGS]*/
	IMP_ORDER("IMP_ORDER"),//销售订单导入
	IMP_DISTRIBUTION_PERSONEL("IMP_DISTRIBUTION_PERSONEL"),//分发人员导入
	IMP_TOPIC("IMP_TOPIC"),//考试题目导入
	IMP_TRAIN_RECORDS("IMP_TRAIN_RECORDS"),//培训记录导入
	IMP_REPORT("IMP_REPORT"),//脓毒症报告导入
	IMP_SALE("IMP_SALE"),//销售目标导入
	IMP_INSPECTION("IMP_INSPECTION"),//送检信息附件
	IMP_SPECIALINSPECTION("IMP_SPECIALINSPECTION"),//特检导入
	IMP_WZZK("IMP_WZZK"),//物种质控导入
	IMPORT_INSPECTION("IMPORT_INSPECTION"),//送检报告导入
	IMP_TEMPLATE("IMP_TEMPLATE"),//模板导入
	IMP_PROJECT("IMP_PROJECT"),//项目导入
	IMP_CHECKOUT("IMP_CHECKOUT"),//质量检验
	IMP_MESSAGE("IMP_MESSAGE"),//任务留言
	IMP_CONFIRM("IMP_CONFIRM"),//任务确认
	IMP_REQUISITION("IMP_REQUISITION"),//领料导入
	IMP_GOODS("IMP_GOODS"),//货物导入
	IMP_FEEDBACK("IMP_FEEDBACK"),//送检反馈
	IMP_MEDHISTORY("IMP_MEDHISTORY"),//以往病史
	IMP_SCHEME("IMP_SCHEME"),//方案导入（助手小程序）
	IMP_TEMP_WORD("IMP_TEMP_WORD"),//临时word文件
	IMP_LIBRARY("IMP_LIBRARY"),//文库导入
	IMP_REPORTZIP("IMP_REPORTZIP"),//报告压缩
	IMP_SMS("IMP_SMS"),//短信导入
	IMP_CELLCOUNTING("IMP_CELLCOUNTING"),//细胞计数导入
	IMP_WECHAT_MATERIAL("IMP_WECHAT_MATERIAL"),//公众号素材导入
	IMP_REPORT_TEMEPLATE("IMP_REPORT_TEMEPLATE"),//报告模板导入
	IMP_EXCEPTION("IMP_EXCEPTION"),//送检异常
	IMP_EXCEPTION_FEEDBACK("IMP_EXCEPTION_FEEDBACK"),//送检异常反馈
	IMP_MEASUREMENT("IMP_MEASUREMENT"),//上传证书扫描件(计量校准)
	IMP_VERIFIFCATION("IMP_VERIFIFCATION"),//送检验证复检
	IMP_SEQ_QUALITY("IMP_SEQ_QUALITY"),//测序质量图导入
	IMP_SEQ_QUALITY_CHROMOSOME("IMP_SEQ_QUALITY_CHROMOSOME"),//染色体曼哈顿图导入(原图)
	IMP_SEQ_QUALITY_CHROMOSOME_DEAL("IMP_SEQ_QUALITY_CHROMOSOME_DEAL"),//染色体曼哈顿图导入(非原图，截取后的)
	IMP_WORD_DETECTION_SELF("IMP_WORD_DETECTION_SELF"),//送检自免数据
	IMP_REPORT_TEMEPLATE_XPERT("IMP_REPORT_TEMEPLATE_XPERT"),//送检XPERT数据
	IMP_REPORT_TEMEPLATE_GM("IMP_REPORT_TEMEPLATE_GM"),//送检XPERT数据
	IMP_REPORT_TEMEPLATE_GXM("IMP_REPORT_TEMEPLATE_GXM"),//送检XPERT数据
	IMP_PURCHASE("IMP_PURCHASE"),//请购附件导入
	IMP_PURCHASE_GENERATE("IMP_PURCHASE_GENERATE"),//请购附件word版
	IMP_PURCHASEZIP("IMP_PURCHASEZIP"),//请购附件压缩
	IMP_TEMEPLATE_IMAGES("IMP_TEMEPLATE_IMAGES"),//报告附件
	IMP_INSPECTION_CONFIRM("IMP_INSPECTION_CONFIRM"),//收样确认
	IMP_WORD_DETECTION_HBMC_NO_D("IMP_WORD_DETECTION_HBMC_NO_D"),//送检结果word合作伙伴为无版
	IMP_WORD_DETECTION_HBMC_NO_R("IMP_WORD_DETECTION_HBMC_NO_R"),//送检结果word(RNA)版
	IMP_WORD_DETECTION_HBMC_NO_C("IMP_WORD_DETECTION_HBMC_NO_C"),//送检结果word(RNA+DNA)版
	IMP_WORD_DETECTION_HBMC_NO_D_REM("IMP_WORD_DETECTION_HBMC_NO_D_REM"),//送检结果word合作伙伴为无版[去人源]
	IMP_WORD_DETECTION_HBMC_NO_R_REM("IMP_WORD_DETECTION_HBMC_NO_R_REM"),//送检结果word(RNA)版[去人源]
	IMP_WORD_DETECTION_HBMC_NO_C_REM("IMP_WORD_DETECTION_HBMC_NO_C_REM"),//送检结果word(D+R)版[去人源]
	IMP_REPORT_TEMEPLATE_XPERT_X_WORD("IMP_REPORT_TEMEPLATE_XPERT_X_WORD"),
	IMP_REPORT_TEMEPLATE_XPERT_Y_WORD("IMP_REPORT_TEMEPLATE_XPERT_Y_WORD"),
	IMP_REPORT_TEMEPLATE_XPERT_G_WORD("IMP_REPORT_TEMEPLATE_XPERT_G_WORD"),
	IMP_REPORT_C_TEMEPLATE_D("IMP_REPORT_C_TEMEPLATE_D"), // 送检结果PDC【PDF(DNA)版】
	IMP_REPORT_C_TEMEPLATE_R("IMP_REPORT_C_TEMEPLATE_R"), // 送检结果PDC【PDF(RNA)版】
	IMP_REPORT_C_TEMEPLATE_C("IMP_REPORT_C_TEMEPLATE_C"), // 送检结果PDC【PDF(D+R)版】
	IMP_REPORT_C_TEMEPLATE_D_WORD("IMP_REPORT_C_TEMEPLATE_D_WORD"), // 送检结果PDC【word(DNA)版】
	IMP_REPORT_C_TEMEPLATE_R_WORD("IMP_REPORT_C_TEMEPLATE_R_WORD"), // 送检结果PDC【word(RNA)版】
	IMP_REPORT_C_TEMEPLATE_C_WORD("IMP_REPORT_C_TEMEPLATE_C_WORD"), // 送检结果PDC【word(D+R)版】
	IMP_FILE_RFS_TEMEPLATE("IMP_FILE_RFS_TEMEPLATE"), // Z项目上传
	IMP_FILE_JHNY_TEMEPLATE("IMP_FILE_JHNY_TEMEPLATE"), // 结核耐药文件上传
	IMP_FILE_JHNY_INFO_TEMEPLATE("IMP_FILE_JHNY_INFO_TEMEPLATE"), // 结核耐药文件上传
	IMP_REPORT_TWO("IMP_REPORT_TWO"), // 第二份报告模板
	IMP_FILE_JHNY_RESULT_TEMEPLATE("IMP_FILE_JHNY_RESULT_TEMEPLATE"),
	IMP_REPORT_QINDEX_TEMEPLATE_D("IMP_REPORT_QINDEX_TEMEPLATE_D"), // 送检结果QmNGS【PDF(DNA)版】
	IMP_REPORT_QINDEX_TEMEPLATE_R("IMP_REPORT_QINDEX_TEMEPLATE_R"), // 送检结果QmNGS【PDF(RNA)版】
	IMP_REPORT_QINDEX_TEMEPLATE_C("IMP_REPORT_QINDEX_TEMEPLATE_C"), // 送检结果QmNGS【PDF(D+R)版】
	IMP_REPORT_QINDEX_TEMEPLATE_D_WORD("IMP_REPORT_QINDEX_TEMEPLATE_D_WORD"), // 送检结果QmNGS【word(DNA)版】 
	IMP_REPORT_QINDEX_TEMEPLATE_R_WORD("IMP_REPORT_QINDEX_TEMEPLATE_R_WORD"), // 送检结果QmNGS【word(RNA)版】
	IMP_REPORT_QINDEX_TEMEPLATE_C_WORD("IMP_REPORT_QINDEX_TEMEPLATE_C_WORD"), // 送检结果QmNGS【word(D+R)版】 
	IMP_SPEED_D("IMP_SPEED_D"), // 送检结果极速【PDF(DNA)版】
	IMP_SPEED_R("IMP_SPEED_R"), // 送检结果极速【PDF(RNA)版】
	IMP_SPEED_C("IMP_SPEED_C"), // 送检结果极速【PDF(D+R)版】
	IMP_SPEED_D_WORD("IMP_SPEED_D_WORD"), // 送检结果极速【word(DNA)版】
	IMP_SPEED_R_WORD("IMP_SPEED_R_WORD"), // 送检结果极速【word(RNA)版】
	IMP_SPEED_C_WORD("IMP_SPEED_C_WORD"), // 送检结果极速【word(D+R)版】
	IMP_SPEED_REM_D("IMP_SPEED_REM_D"), // 送检结果极速【PDF(DNA)版[去人源]】
	IMP_SPEED_REM_R("IMP_SPEED_REM_R"), // 送检结果极速【PDF(RNA)版[去人源]】
	IMP_SPEED_REM_C("IMP_SPEED_REM_C"), // 送检结果极速【PDF(D+R)版[去人源]】
	IMP_SPEED_REM_D_WORD("IMP_SPEED_REM_D_WORD"), // 送检结果极速【word(DNA)版[去人源]】
	IMP_SPEED_REM_R_WORD("IMP_SPEED_REM_R_WORD"), // 送检结果极速【word(RNA)版[去人源]】
	IMP_SPEED_REM_C_WORD("IMP_SPEED_REM_C_WORD"), // 送检结果极速【word(D+R)版[去人源]】

	IMP_REPORT_ONCO_QINDEX_TEMEPLATE_D("IMP_REPORT_ONCO_QINDEX_TEMEPLATE_D"), // 送检结果ONCO_QmNGS【PDF(DNA)版】
	IMP_REPORT_ONCO_QINDEX_TEMEPLATE_R("IMP_REPORT_ONCO_QINDEX_TEMEPLATE_R"), // 送检结果ONCO_QmNGS【PDF(RNA)版】
	IMP_REPORT_ONCO_QINDEX_TEMEPLATE_C("IMP_REPORT_ONCO_QINDEX_TEMEPLATE_C"), // 送检结果ONCO_QmNGS【PDF(D+R)版】
	IMP_REPORT_ONCO_QINDEX_TEMEPLATE_O("IMP_REPORT_ONCO_QINDEX_TEMEPLATE_O"), // 送检结果ONCO_QmNGS【PDF(Seq)版】
	IMP_REPORT_ONCO_QINDEX_TEMEPLATE_D_WORD("IMP_REPORT_ONCO_QINDEX_TEMEPLATE_D_WORD"), // 送检结果ONCO_QmNGS【word(DNA)版】
	IMP_REPORT_ONCO_QINDEX_TEMEPLATE_R_WORD("IMP_REPORT_ONCO_QINDEX_TEMEPLATE_R_WORD"), // 送检结果ONCO_QmNGS【word(RNA)版】
	IMP_REPORT_ONCO_QINDEX_TEMEPLATE_C_WORD("IMP_REPORT_ONCO_QINDEX_TEMEPLATE_C_WORD"), // 送检结果ONCO_QmNGS【word(D+R)版】
	IMP_REPORT_ONCO_QINDEX_TEMEPLATE_O_WORD("IMP_REPORT_ONCO_QINDEX_TEMEPLATE_O_WORD"), // 送检结果ONCO_QmNGS【word(Seq)版】
	
	IMP_REPORT_C_TEMEPLATE_REM_D("IMP_REPORT_C_TEMEPLATE_REM_D"), // 送检结果PDC【PDF(DNA)版 [去人源]】
	IMP_REPORT_C_TEMEPLATE_REM_R("IMP_REPORT_C_TEMEPLATE_REM_R"), // 送检结果PDC【PDF(RNA)版[去人源]】
	IMP_REPORT_C_TEMEPLATE_REM_C("IMP_REPORT_C_TEMEPLATE_REM_C"), // 送检结果PDC【PDF(D+R)版[去人源]】
	IMP_REPORT_C_TEMEPLATE_REM_D_WORD("IMP_REPORT_C_TEMEPLATE_REM_D_WORD"), //送检结果PDC【word(DNA)版[去人源]】
	IMP_REPORT_C_TEMEPLATE_REM_R_WORD("IMP_REPORT_C_TEMEPLATE_REM_R_WORD"), //送检结果PDC【word(RNA)版[去人源]】
	IMP_REPORT_C_TEMEPLATE_REM_C_WORD("IMP_REPORT_C_TEMEPLATE_REM_C_WORD"), //送检结果PDC【word(D+R)版[去人源]】
	
	IMP_REPORT_QINDEX_TEMEPLATE_REM_D("IMP_REPORT_QINDEX_TEMEPLATE_REM_D"), // 送检结果QmNGS【PDF(DNA)版 [去人源]】
	IMP_REPORT_QINDEX_TEMEPLATE_REM_R("IMP_REPORT_QINDEX_TEMEPLATE_REM_R"), // 送检结果QmNGS【PDF(RNA)版 [去人源]】
	IMP_REPORT_QINDEX_TEMEPLATE_REM_C("IMP_REPORT_QINDEX_TEMEPLATE_REM_C"), // 送检结果QmNGS【PDF(D+R)版 [去人源]】
	IMP_REPORT_QINDEX_TEMEPLATE_REM_D_WORD("IMP_REPORT_QINDEX_TEMEPLATE_REM_D_WORD"), //送检结果QmNGS【word(DNA)版[去人源QmNGS]】
	IMP_REPORT_QINDEX_TEMEPLATE_REM_R_WORD("IMP_REPORT_QINDEX_TEMEPLATE_REM_R_WORD"), //送检结果QmNGS【word(RNA)版[去人源QmNGS]】
	IMP_REPORT_QINDEX_TEMEPLATE_REM_C_WORD("IMP_REPORT_QINDEX_TEMEPLATE_REM_C_WORD"), //送检结果QmNGS【word(D+R)版[去人源QmNGS]】
	IMP_REPORT_TEMEPLATE_XPERT_X("IMP_REPORT_TEMEPLATE_XPERT_X"),
	IMP_REPORT_TEMEPLATE_XPERT_Y("IMP_REPORT_TEMEPLATE_XPERT_Y"),
	IMP_REPORT_TEMEPLATE_XPERT_G("IMP_REPORT_TEMEPLATE_XPERT_G"),
	IMP_REPORT_ONCO_QINDEX_TEMEPLATE_REM_D("IMP_REPORT_ONCO_QINDEX_TEMEPLATE_REM_D"), // 送检结果ONCO_QmNGS【PDF(DNA)版 [去人源]】
	IMP_REPORT_ONCO_QINDEX_TEMEPLATE_REM_R("IMP_REPORT_ONCO_QINDEX_TEMEPLATE_REM_R"), // 送检结果ONCO_QmNGS【PDF(RNA)版 [去人源]】
	IMP_REPORT_ONCO_QINDEX_TEMEPLATE_REM_C("IMP_REPORT_ONCO_QINDEX_TEMEPLATE_REM_C"), // 送检结果ONCO_QmNGS【PDF(D+R)版 [去人源]】
	IMP_REPORT_ONCO_QINDEX_TEMEPLATE_REM_O("IMP_REPORT_ONCO_QINDEX_TEMEPLATE_REM_O"), // 送检结果ONCO_QmNGS【PDF(Seq)版 [去人源]】
	IMP_REPORT_ONCO_QINDEX_TEMEPLATE_REM_D_WORD("IMP_REPORT_ONCO_QINDEX_TEMEPLATE_REM_D_WORD"), //送检结果ONCO_QmNGS【word(DNA)版[去人源ONCO_QmNGS]】
	IMP_REPORT_ONCO_QINDEX_TEMEPLATE_REM_R_WORD("IMP_REPORT_ONCO_QINDEX_TEMEPLATE_REM_R_WORD"), //送检结果ONCO_QmNGS【word(RNA)版[去人源ONCO_QmNGS]】
	IMP_REPORT_ONCO_QINDEX_TEMEPLATE_REM_C_WORD("IMP_REPORT_ONCO_QINDEX_TEMEPLATE_REM_C_WORD"), //送检结果ONCO_QmNGS【word(D+R)版[去人源ONCO_QmNGS]】
	IMP_REPORT_ONCO_QINDEX_TEMEPLATE_REM_O_WORD("IMP_REPORT_ONCO_QINDEX_TEMEPLATE_REM_O_WORD"), //送检结果ONCO_QmNGS【word(Seq)版[去人源ONCO_QmNGS]】

	IMP_REPORT_TEMEPLATE_Z6("IMP_REPORT_TEMEPLATE_Z6"), // 送检结果自免6项
	IMP_REPORT_TEMEPLATE_Z8("IMP_REPORT_TEMEPLATE_Z8"), // 送检结果自免8项
	IMP_REPORT_TEMEPLATE_Z12("IMP_REPORT_TEMEPLATE_Z12"), // 送检结果自免12项
	IMP_REPORT_TEMEPLATE_Z18("IMP_REPORT_TEMEPLATE_Z18"), // 送检结果自免18项
	IMP_REPORT_TEMEPLATE_F("IMP_REPORT_TEMEPLATE_F"), // 送检结果副瘤
	IMP_REPORT_TEMEPLATE_T3("IMP_REPORT_TEMEPLATE_T3"),//送检脱髓鞘三项
	IMP_REPORT_TEMEPLATE_T6("IMP_REPORT_TEMEPLATE_T6"),//送检脱髓鞘六项
	IMP_REPORT_TEMEPLATE_K("IMP_REPORT_TEMEPLATE_K"),//送检寡克隆区带检测
	
	IMP_REPORT_TEMEPLATE_Z6_WORD("IMP_REPORT_TEMEPLATE_Z6_WORD"), // 送检结果自免6项word版
	IMP_REPORT_TEMEPLATE_Z8_WORD("IMP_REPORT_TEMEPLATE_Z8_WORD"), // 送检结果自免8项word版
	IMP_REPORT_TEMEPLATE_Z12_WORD("IMP_REPORT_TEMEPLATE_Z12_WORD"), // 送检结果自免12项word版
	IMP_REPORT_TEMEPLATE_Z18_WORD("IMP_REPORT_TEMEPLATE_Z18_WORD"), // 送检结果自免18项word版
	IMP_REPORT_TEMEPLATE_F_WORD("IMP_REPORT_TEMEPLATE_F_WORD"), // 送检结果副瘤word版
	IMP_REPORT_TEMEPLATE_T3_WORD("IMP_REPORT_TEMEPLATE_T3_WORD"),//送检脱髓鞘三项word版
	IMP_REPORT_TEMEPLATE_T6_WORD("IMP_REPORT_TEMEPLATE_T6_WORD"),//送检脱髓鞘六项word版
	IMP_REPORT_TEMEPLATE_K_WORD("IMP_REPORT_TEMEPLATE_K_WORD"),//送检寡克隆区带检测word版

	IMP_REPORT_TNGS_TEMEPLATE_D("IMP_REPORT_TNGS_TEMEPLATE_D"), // 送检结果tmNGS【PDF(DNA)版】
	IMP_REPORT_TNGS_TEMEPLATE_C("IMP_REPORT_TNGS_TEMEPLATE_C"), // 送检结果tmNGS【PDF(D+R)版】
	IMP_REPORT_TNGS_TEMEPLATE_D_WORD("IMP_REPORT_TNGS_TEMEPLATE_D_WORD"), // 送检结果tmNGS【word(DNA)版】
	IMP_REPORT_TNGS_TEMEPLATE_C_WORD("IMP_REPORT_TNGS_TEMEPLATE_C_WORD"), // 送检结果tmNGS【word(D+R)版】

	IMP_TRAIN_PICTURE("IMP_TRAIN_PICTURE"), //培训文件（图片）
	IMP_TRAIN("IMP_TRAIN"), //培训文件
	IMP_CONTRACT_WORD("IMP_CONTRACT_WORD"), //生成合同文件word版
	IMP_CONTRACT("IMP_CONTRACT"), //生成合同文件pdf版
	IMP_SUBCONTRACT("IMP_SUBCONTRACT"), //提交合同文件
	IMP_SUBSUPPLIER("IMP_SUBSUPPLIER"), //提交供应商附件
	IMP_SUBSUPPLIERZIP("IMP_SUBSUPPLIERZIP"), //供应商附件压缩包
	IMP_FORMWORKSUBSUPPLIER("IMP_FORMWORKSUBSUPPLIER"), //提交供应商模板附件
	IMP_UPLOADCONTRACT("IMP_UPLOADCONTRACT"), //提交合同文件
	IMP_BANK_PAY_QRCODE("IMP_BANK_PAY_QRCODE"), // 银行付款聚合二维码
	IMP_UPLOADINSPECTION("IMP_UPLOADINSPECTION"),//提交检验文件
	IMP_SUBPICKING("IMP_SUBPICKING"), //提交领料文件
	IMP_DEMAND("IMP_DEMAND"), //提交需求计划文件
	IMP_PRODUCE("IMP_PRODUCE"), //生产文件
	
	IMP_LABORATORY_BG("IMP_LABORATORY_BG"), //实验室结构图
	IMP_DEVICE_BG("IMP_DEVICE_BG"), //实验室仪器图
	IMP_HZXX_TEMPLATE("IMP_HZXX_TEMPLATE"),//病例报告模板
	IMP_REPORT_HJYZ("IMP_REPORT_HJYZ"),//宏基因组报告
	IMP_PCR_TEMEPLATE("IMP_PCR_TEMEPLATE"), //PCR运行设置模板
	IMP_REPORT_COVID_WORD("IMP_REPORT_COVID_WORD"), //生成报告单
	IMP_REPORT_COVID("IMP_REPORT_COVID"), //生成报告pdf版
	IMP_LOGISTICS_ARRIVE("IMP_LOGISTICS_ARRIVE"),//物流送达附件
	IMP_LOGISTICS_CANCELRECEIPT("IMP_LOGISTICS_CANCELRECEIPT"),//取消取件附件
	IMP_DETECTION_TEMPLATE("IMP_DETECTION_TEMPLATE"),//新冠检测人检模板
	IMP_DETECTION_TEMPLATE_GOODS("IMP_DETECTION_TEMPLATE_GOODS"),//新冠检测物检模板
	IMP_REPORT_COVID_DATA("IMP_REPORT_COVID_DATA"),//新冠检测检测数据文件
	IMP_FP_ANNEX("IMP_FP_ANNEX"),//合同发票附件
	IMP_LIBRARY_EXCEL("IMP_LIBRARY_EXCEL"), //文库附件
	IMP_LIBRARY_POOLING_EXPORT("IMP_LIBRARY_POOLING_EXPORT"), //pooling导出附件
	IMP_LIBRARY_POOLING_UPLOAD("IMP_LIBRARY_POOLING_UPLOAD"), //pooling上传附件
	IMP_DOCKER("IMP_DOCKER"), //docker
	IMP_LIBRARY_EXCEL_IN("IMP_LIBRARY_EXCEL_IN"), //文库附件导入
	IMP_MOLECULAR_DETECTION("IMP_MOLECULAR_DETECTION"),//分子检测导入
    IMP_MOLECULAR_GOODSDETECTION("IMP_MOLECULAR_GOODSDETECTION"),//分子物检导入
    IMP_IDENTITY_CARD_IMG("IMP_IDENTITY_CARD_IMG"),//身份证图片
    IMP_LOGISTICS_PICKUP_IMG("IMP_LOGISTICS_PICKUP_IMG"),//物流取件图片

	IMP_LIBRARY_SEQUENCING_IMG("IMP_LIBRARY_SEQUENCING_IMG"),//文库测序质量
	IMP_CNV_RESULT_IMG("IMP_CNV_RESULT_IMG"),//cnv结果图片
    IMP_QRCODE_IMG("IMP_QRCODE_IMG"),//二维码图片
	IMP_ACQRCODEINFO_P_IMG("IMP_ACQRCODEINFO_P_IMG"),//防伪二维码图片(竖版)
	IMP_ACQRCODEINFO_H_IMG("IMP_ACQRCODEINFO_H_IMG"),//防伪二维码图片(横版)
	IMP_HPV_TEMPLATE("IMP_HPV_TEMPLATE"),//HPV报告模板
	IMP_SCREENING_TEMPLATE("IMP_SCREENING_TEMPLATE"),//基础数据 分子检测子项目的报告模板
	IMP_SCREENING("IMP_SCREENING"),//普检导入
	IMP_REPORT_HPV_WORD("IMP_REPORT_HPV_WORD"), //生成报告单
	IMP_REPORT_HPV("IMP_REPORT_HPV"), //生成报告pdf版
	IMP_SAMPLING_SUMMARY("IMP_SAMPLING_SUMMARY"),//留样小结附件
	IMP_SAMPLING_Q_SUMMARY("IMP_SAMPLING_Q_SUMMARY"),//取样小结 检验报告附件
	IMP_SAMPLING_Q_SUMMARY_RESULT("IMP_SAMPLING_Q_SUMMARY_RESULT"),//取样小结 检验结果附件
	IMP_PRODUCTION_REVIEW("IMP_PRODUCTION_REVIEW"),//生产评审附件
	IMP_LOGISTICS_DISPATCH_IMG("IMP_LOGISTICS_DISPATCH_IMG"),//物流派单图片
	IMP_LOGISTICS_MAINTENANCE("IMP_LOGISTICS_DISPATCH_IMG"),//物流维护图片
	BOM_IMPORT("BOM_IMPORT"),//BOM导入
//	IMP_PCRTLPD("IMP_PCRTLPD"),//天隆tlpd实验结果源文件
//	IMP_PCRXLXS("IMP_PCRXLXS"),//天隆XLSX实验结果表格文件

	IMP_REPORT_RFS_TEMEPLATE_F_WORD("IMP_REPORT_RFS_TEMEPLATE_F_WORD"),//Z项目报告WORD
	IMP_REPORT_RFS_TEMEPLATE_F("IMP_REPORT_RFS_TEMEPLATE_F"),//Z项目报告PDF

	IMP_REPORT_XIANSHENG("IMP_REPORT_XIANSHENG"),//先声回传;
	IMP_REPORT_YUHUANGDING_XML("IMP_REPORT_YUHUANGDING_XML"),//毓璜顶回传报告xml;
	IMP_REPORT_XINGHE_XML("IMP_REPORT_XINGHE_XML"),//杏和回传报告xml;
	IMP_REPORT_QIANMAI_XML("IMP_REPORT_QIANMAI_XML"),//千麦回传报告xml;
	IMP_REPORT_AIDIKANG_XML("IMP_REPORT_AIDIKANG_XML"),//艾迪康回传报告xml;
	IMP_REPORT_UNUPLOAD_CDC_TXT("IMP_REPORT_UNUPLOAD_CDC_TXT"),//疾控TXT(未上传);
	IMP_REPORT_UPLOADED_CDC_TXT("IMP_REPORT_UPLOADED_CDC_TXT"),//疾控TXT(已上传);
	IMP_CORRESPOND_INFORMATION("IMP_CORRESPOND_INFORMATION"),//对应信息导入;
	IMP_QUALITY_AGREEMENT_FILE("IMP_QUALITY_AGREEMENT_FILE"),//质量协议
	IMP_UPQUALITYCONTRACT("IMP_UPQUALITYCONTRACT"), //提交质量协议文件
	IMP_QUALITY_WORD("IMP_QUALITY_WORD"), //生成合同文件word版
	IMP_QUALITYT("IMP_QUALITYT"), //生成合同文件pdf版
    IMP_MARKETING_CONTRACT("IMP_MARKETING_CONTRACT"), //营销合同文件
	IMP_UPLOADMARKETING_CONTRACT("IMP_UPLOADMARKETING_CONTRACT"), //双章营销合同
	IMP_BUSINESS_PAYMENT_APPLICATION_FILE("IMP_BUSINESS_PAYMENT_APPLICATION_FILE"), //商务付款申请附件
	IMP_UPLOAD_CREDIT("IMP_UPLOAD_CREDIT"), //应收账款上传附件
	IMP_INVOICE_CREDIT("IMP_INVOICE_CREDIT"), //应收账款开票附件
	IMP_MARKETING_SIN("IMP_MARKETING_SIN"), //营销看板
	IMP_DEVICE_CHECK("IMP_DEVICE_CHECK"),//设备验收附件
	IMP_CUSTOM("IMP_CUSTOM"), //客户附件
	IMP_DETECTION_APPLICATION_FILE("IMP_DETECTION_APPLICATION_FILE"), //检出申请附件

	IMP_ZZXJ_APPLICATION_FILE("IMP_ZZXJ_APPLICATION_FILE"), //质控小结附件
	IMP_DETECTION_APPLICATION_ZIP("IMP_DETECTION_APPLICATION_ZIP"), //检出申请压缩包
	IMP_ARRIVALGOODS("IMP_ARRIVALGOODS"), //到货附件
	FINANCE_TEMPLATE("FINANCE_TEMPLATE"),//财务报表模板
	FINANCE_ACCOUNT("FINANCE_ACCOUNT"),//财务报表
	IMP_PRODUCT_MANUAL("IMP_PRODUCT_MANUAL"),//产品说明书
	IMP_PRODUCT_MANUAL_QRCODE("IMP_PRODUCT_MANUAL_QRCODE"),//产品说明书二维码

	IMP_BIOINFORMATION("IMP_BIOINFORMATION"),//生信整合附件
	IMP_SAMPLERECORD("IMP_SAMPLERECORD"),//外部仪器接口附件接收
	IMP_INSPECTIONGOODS_REPORT("IMP_INSPECTIONGOODS_REPORT"),//物料检验报告
	IMP_INSPECTIONGOODS_RECORD("IMP_INSPECTIONGOODS_RECORD"),//物料检验记录
	IMP_INSPECTIONGOODS_BACKDROP("IMP_INSPECTIONGOODS_BACKDROP"),//背景信息上传

	IMP_INSPECTIONGOODS_DATA("IMP_INSPECTIONGOODS_DATA"),//物料检验记录
	IMP_QUALITY_COMPLAINTS("IMP_QUALITY_COMPLAINTS"),//质量投诉附件
	IMP_COMPLAINTS_HANDLING_SITUATION("IMP_COMPLAINTS_HANDLING_SITUATION"),//投诉处理情况附件
	IMP_NOTICE("IMP_NOTICE"),//首页公告
	IMP_TRAIN_QRCODE("IMP_TRAIN_QRCODE"),//培训签到二维码
	IMP_REPORT_FLU_WORD("IMP_REPORT_FLU_WORD"), //甲乙流报告word
	IMP_REPORT_FLU("IMP_REPORT_FLU"), //甲乙流报告
	IMP_FILE_FLU_TEMEPLATE("IMP_FILE_FLU_TEMEPLATE"), // 甲乙流结果上传

	IMP_REPORT_JHPCR("IMP_REPORT_JHPCR"),//结核PCR报告

	IMP_REPORT_JHPCR_WORD("IMP_REPORT_JHPCR_WORD"),//结核PCR报告word

	IMP_FILE_JHPCR_TEMEPLATE("IMP_FILE_JHPCR_TEMEPLATE"),//结核PCR结果上传
	IMP_ANNUAL_PLAN("IMP_ANNUAL_PLAN"),//年度培训导入
	IMP_AWARD_MANAGEMENT("IMP_AWARD_MANAGEMENT"),//奖品管理附件
	IMP_VISIT_RECORDS("IMP_VISIT_RECORDS"),//拜访记录附件
	IMP_FINANCIAL_BUDGET("IMP_FINANCIAL_BUDGET"),//财务预算导入

	IMP_PPTGL_FILE("IMP_PPTGL_FILE"),//PPTGL附件
	IMP_QRCODE_LOGO("IMP_QRCODE_LOGO"),//二维码logo

	IMP_HEALTH("IMP_HEALTH"),//健康档案

	IMP_LIBRARY_JCSQ("IMP_LIBRARY_JCSQ"),//检出申请文库参考
	IMP_UPLOADTOOL("IMP_UPLOADTOOL"),//上传工具
	IMP_DINGDING("IMP_DINGDING"),
	;
	private final String code;

	BusTypeEnum(String code) {
		this.code = code;
	}

	public String getCode() {
		return code;
	}
}
