spring:
  application:
    name: hk-igams-hrm
  redis:
    ## Redis服务器地址
    host: localhost
    ## Redis服务器连接密码（默认为空）
    password:
  ##消息队列
  rabbitmq:
    host: 172.17.60.190
    username: admin
    password: matridx2019!
    docok: mq.tran.matridx.ok
  mail:
    host: smtp.163.com
    viewname: 杰毅生物
    protocol: smtp
    username:
    password:
postsql:
  datasource:
    username: AEBrmFhq9gZ4Yeq+mogdzQ==
    password: MrTVAg0Sn2SfQZE/HUZ5IQ==
    url: E6Bxa5hFXjN+sYdjKG06wOCsp1DH0IZMJUquJ5w+uYNwmSkXKQ/GVXcTxW7YRxtj
sqlserver:
  gmds:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: C7PnCpt+ks/6vf8lMKVK/w==
    password: KUZmZ4Ds0epg3B3AQIwbnw==
    #jdbc:sqlserver://192.168.1.130:1433;database=ahos";
    url: 05rJvWC/dZNwL93RtuHWFNVuK+t/UnPhJNfqWZU8FsK+qoIvC+7EEzgD2O+Oo2KX9hwh9PEgRNg4FkJWqFgNbg==
    validationQuery: SELECT 1
    flag: 麦特
  matridxds:
    username: C7PnCpt+ks/6vf8lMKVK/w==
    password: KUZmZ4Ds0epg3B3AQIwbnw==
    #jdbc:sqlserver://192.168.1.130:1433;database=ahos";
    url: 05rJvWC/dZNwL93RtuHWFNVuK+t/UnPhJNfqWZU8FsK+qoIvC+7EEzgD2O+Oo2KX9hwh9PEgRNg4FkJWqFgNbg==
    validationQuery: SELECT 1
    # 针对当前系统物料需要保存的表来配置，其它业务不做判断
    flag: 生物
##角色切换配置： 0不支持切换，1支持切换
matridx:
  ## 账套
  accountSet:
    accountName: "001"
  ## 水印
  watermark:
    ## 是否单独运行
    standalone: true
    ## 是否要覆盖目标文件
    overwrite: true
    screenShot: true
    ## 文档转换配置
    languageDir: /xpdf-chinese-simplified
    pdfToolsCmd: /opt/openoffice.org3/program/soffice
    openOfficeLocation: /opt/openoffice.org3/program
    pdfConverter: openoffice
    ## 水印图片路径
    imagePath: /images/logo/
    ## 水印字  杰毅生物
    watermark: \u6770\u6bc5\u751f\u7269
    watermarkName: 杰毅麦特
    ## 水印字体大小
    watermarkFontsize: 20
    ## 水印横向间隔（A4）数目
    watermarkNumX: 2
    ## 水印纵向间隔（A4）数目
    watermarkNumY: 3
    ## 水印显示透明度
    watermarkFillOpacity: 0.3
    ## 水印显示倾斜角度
    watermarkRotation: 35
    ## 水印字体
    watermarkFontsizeForImage: 30
  systemflg:
    logourl: /images/logoIn-biology.png
    watermark: 杰毅麦特
    systemname: 杰毅生物
    ## remindflg决定是否发送提醒，0不发送，1和null为发送
    remindflg: 0
  rabbitflg:
    #rabbit同步是否接受标记 1：接受 其他或空不接收
    receiveflg: 0
    #rabbit同步系统标记
    systemflg: .matridx.tx
  role:
    switch: 1
  exptype:
    limit: 500
  fileupload:
    prefix:
    tempPath: /matridx/fileupload/temp/
    releasePath: /matridx/fileupload/release/
  file:
    ##文件导出存放路径
    exportFilePath: /matridx/download/
    ##文件保存路径前缀
    pathPrefix:
    ##文件转换最大次数
    translimit: 5
  ftp:
    wordpath: /wordFile
    pdfpath: /pdfFile
    url: 172.17.53.52
    user: ftpuser
    pd: matridx
    port: 21
  ##钉钉
  dingtalk:
    appkey: SjiVL+I3B6kEhRLZF4/FYb4nE6hsaQF5pzqRdFsSUFM=
    appsecret: Rebf6/oPXPP/H41hYBzQimFnVrm0vsQCzaXvIC7i8a9qcdocNErZDsK6ol+OHhAmet3/jn0VpbpqWm8QoL8jSzJVhPyCTTb2m8Ia5X4cJ9k=
    agentid: 667lPwpNVwmh3pV6LMNA6Q==
    matridx:
    ## 跳转钉钉小程序路径
    jumpdingtalkurl: Lz0Qi39mDV9YbnhyI3+8xhciRl4pY5+eMLzG+soXtK1iy373PwQ04d6uT8EjVHNzN1/TmqvX+PxcICDIthwarcnkEW6oiX7nSZjSdrpIWFouz7TUB9Q+1GIIysJ26i0NO05sBV/mJHB40XeEMBVBtLT9WYEj+n3K8x3EAwP7tEOazDHlvtl4be1KjJ/R5VDqVMZZEvfDAQCLrY0XaqUXfKIIVdtFTEHf/klymWO10sM=
    ## 服务器对外端口
    #callbackurl: http://101.68.81.93
    cropid: PAi6mqqSMLdnxhFqQOdG7dsZefVmxGWVEvq0JsEZips=
    aeskey: 0t88uYEVcsN+rSL4kAfb3nMU5jf9VEX+6Bs1L49He+bmU4J5wqxCB8r1lHr8GfRg
  ##语音识别
  audio:
    savepath: /matridx/audio/save/
    audiotype: ali       ##ali  baidu
    #accessKeyId: ZY5umhS7CN9RRVKg1x3poKfc8IzB4TkAp0/GRS/sXYo=
    #accessKeySecret: YgFUZcqxPzLq286Nwmfj4BFfN+QbP4eu8EGl52g42tIyVYT8gk029pvCGuV+HCfZ
    #appid: L2rjGmuPzJ9xmSU0/9iyFA==
    accessKeyId: Fyj2gzZ9dU2Xw2lxrxfBQzJVhPyCTTb2m8Ia5X4cJ9k=
    accessKeySecret: AElsGW16bjaYU2qiTVqwIOzhlmPt5FpxGq6c5XKsKHM=
    appid: vo88lJAbqCj5CzwR8/u4cTJVhPyCTTb2m8Ia5X4cJ9k=
  wechat:
    ##菜单推送微信的地址
    menuurl: http://localhost:8085
    ##钉钉查看访问的路径
    #applicationurl: http://172.17.60.188
    applicationurl: http://172.17.53.52:8086
    ## 送检发送请求查询 检测结果的地址
    inspectionurl: http://localhost:8085
    ## 统计外部地址
    externalurl: http://172.17.53.52:8086
    appid: 1
    secret: 2
    paternerkey:
    mchid:
  baidu:
    appkey:
    secret:
  alipay:
    ## 应用ID,您的APPID，收款账号既是您的APPID对应支付宝账号
    app_id:
    ## 应用ID,您的APPID，收款账号既是您的APPID对应支付宝账号
    #uid: 2088102177450010
    ## 商户私钥，您的PKCS8格式RSA2私钥
    alipay_private_key:
    ## 支付宝公钥,查看地址：https://openhome.alipay.com/platform/keyManage.htm 对应APPID下的支付宝公钥。
    alipay_public_key:
    ## 服务器异步通知页面路径  需http://格式的完整路径，不能加?id=123这类自定义参数
    notify_url: http://101.68.81.90:8099/wechat/pay/aliPayNotify
    ## 页面跳转同步通知页面路径 需http://格式的完整路径，不能加?id=123这类自定义参数
    return_url: http://101.68.81.90:8099/wechat/pay/aliPayComplete
    ## 签名方式
    alipay_sign_type: RSA2
    ## 支付宝网关
    gatewayUrl:
  ##阿里云短信
  aliyunSms:
    accessKeyId:
    accessSecret:
    signName: 杰毅检验
    templateCode: SMS_170840387
  prefix:
    urlprefix: /hkhrm
    #igamsweb: /hk-igams-web
    igamsweb: /common-igams-web
  rabbit:
    ## 系统信息同步时的标记，还需在rabbit下进行配置，使Routing key为sys.igams.jcsj.del能同时匹配到sys.igams.jcsj.del，sys.igams.jcsj.del.production
    ## 其中production就是这个flg标记
    flg: .hkhrm
server:
  port: ${sport:8088}
