## 公司内部管理系统用 杰毅麦特 分布式系统
spring:
  application:
    name: igams-cloud-ks
  redis:
    ## Redis服务器地址
    host: redis
    ## Redis服务器连接密码（默认为空）
    password: Matridx_ks_2022!
  rabbitmq:
    host: ${mqhost:172.17.60.191}
    port: 5672
    username: ${mqname:admin}
    password: ${mqpass:matridx2019!}
    docok: ${mqok:production.mq.tran.matridx.ok}
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true     # 是否开启消费者重试（为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息）
          max-attempts: 5   # 最大重试次数
          max-interval: 20000   # 重试最大间隔时间
          initial-interval: 2000  # 重试初始间隔时间
          # 重试间隔*乘子得出下次重试间隔  2s  4s  8s  16s  此处16s>10s  走10s
          multiplier: 2 # 间隔时间乘子，间隔时间*乘子=下一次的间隔时间，最大不能超过设置的最大间隔时间
  config:
    import: optional:configserver:${uri:http://172.17.60.192:8860}
sqlserver:
  matridxds:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: C7PnCpt+ks/6vf8lMKVK/w==
    password: pYp3U6ckXgrmMnqj3TzLAQ==
    #jdbc:sqlserver://192.168.1.130:1433;database=ahos;user=sa;password=ahtec";
    ##url: 05rJvWC/dZNwL93RtuHWFL1gjbOKK4njiHtPS3xM/t++qoIvC+7EEzgD2O+Oo2KXGdnri3NgFMsSryq6X4Usog==
    url: 05rJvWC/dZNwL93RtuHWFL1gjbOKK4njiHtPS3xM/t++qoIvC+7EEzgD2O+Oo2KXw5j4ZEXxEJgjQK3SVIpSo/CzkjmgcpT6Ntn5R9XiZEW9a/q8mGcIBJR6mtfl7eQ8nbOZF3oz6FJ+fUs2lf8BKQ==
    #flag: 恺思
postsql:
  datasource:
    username: AEBrmFhq9gZ4Yeq+mogdzQ==
    password: DmnVklgEln/9NePegyMNig==
    url: E6Bxa5hFXjN+sYdjKG06wAqfeQK7rfwXaPGZO5j0ihx5D+FWf9P4+oPwV0AJRB9Z
##角色切换配置： 0不支持切换，1支持切换
matridx:
  role:
    switch: 1
  basictype:
    file: config/production/comm/basicType.xml
  exptype:
    limit: 500
  fileupload:
    prefix: 
    tempPath: /matridx/fileupload/temp/
    releasePath: /matridx/fileupload/release/
  file:
    ##文件导出存放路径
    exportFilePath: /matridx/download/
    ##文件保存路径前缀
    pathPrefix: 
    ##文件转换最大次数
    translimit: 5
  ftp:
    wordpath: /wordFile
    pdfpath: /pdfFile
    url: 172.17.60.177
    #url: 172.17.60.184
    user: ftpuser
    pd: matridx
    port: 21
  ##钉钉
  dingtalk:
    appkey: VLjcLsXLBqdq2VNg/1dHyePmCZS3ldtgPmRAaUXWevU=
    appsecret: yYMpuKIW6oB7g2q5tWuzGCZWZ36nxK6eqckVxXG7il7FMQmXYVeg7awzHZUoRtU2LeUo7pn111Pdq/XpcAouNTJVhPyCTTb2m8Ia5X4cJ9k=
    agentid: f58T3paimyGbD12fzBIgSA==
    ## 跳转钉钉小程序路径
    jumpdingtalkurl: Lz0Qi39mDV9YbnhyI3+8xhciRl4pY5+eMLzG+soXtK1iy373PwQ04d6uT8EjVHNz84DQUkLhuH9AIUKNQLyjjMqfbcQdiCnT+VDUXF7m82guz7TUB9Q+1GIIysJ26i0NauK5n/6kOGM6ZfZyjR9yOed294rmQV2NCYW7ej8zRi4y/ydIDnScydU5F6Oa7nrEWK7+FaEt+vRlxOn/gMXDhCt+eA0pOQ1kuDQGvZDPFxw=
    ##钉钉小程序 现主要用于扫码登录所使用 杰毅OA
    miniappkey: VLjcLsXLBqdq2VNg/1dHyePmCZS3ldtgPmRAaUXWevU=
    miniappsecret: yYMpuKIW6oB7g2q5tWuzGCZWZ36nxK6eqckVxXG7il7FMQmXYVeg7awzHZUoRtU2LeUo7pn111Pdq/XpcAouNTJVhPyCTTb2m8Ia5X4cJ9k=
  ## 钉钉消息使用
  wechat:
    menuurl: https://service.matridx.com
    applicationurl: http://company.matridx.com
    ## 送检发送请求查询 检测结果的地址
    inspectionurl: http://company.matridx.com
    ## 统计外部地址
    externalurl: http://company.matridx.com
    ## 钉钉回调注册地址190
    registerurl: https://company.matridx.com
  systemflg:
    logourl: /images/logoIn-biology-b.png
    watermark: 恺思
    systemname: 恺思
    ## 合同编号前缀配置
    contractcode: KS
    ## 合同买方邮箱
    contractemail: pengtingting@matridx.com
    ## 定时任务是否执行 0：不执行  1：执行
    remindflg: 1
    ## 启动时根据标记redisreset判断是否进行redis数据的删除重新加入的操作, 1进行操作，0不进行操作
    redisreset: 1
  ##U8账套名称
  accountSet:
    accountName: "006"
  prefix:
    ## 分布式系统，主程序的地址
    igamsweb: /igams-web
    ## 如果本身为分布式子系统，则这个地方不为空，到时候会自动连接主程序prefix.igamsweb（以及传递给页面保持路径），如果未设置，则直接访问本身。
    urlprefix: /ksigams
  rabbit:
    ## 系统信息同步时的标记，还需在rabbit下进行配置，使Routing key为sys.igams.jcsj.del能同时匹配到sys.igams.jcsj.del，sys.igams.jcsj.del.production
    ## 其中production就是这个flg标记
    flg: .ks
    ##是否发送rabbit标记(用户信息等)     1：发送 主要用于 product 和系统用户这边
    configflg: 0
    ##是否接收rabbit标记(用户信息等)     1：接收   
    receiveflg: 1
    ##体系同步是否发送    1：发送
    systemconfigflg: 0
    ##体系同步是否接收    1：接收
    systemreceiveflg: 0
  ## 水印
  watermark:
    ## 是否单独运行
    standalone: true
    ## 是否要覆盖目标文件
    overwrite: true
    screenShot: true
    ## 文档转换配置
    languageDir: /xpdf-chinese-simplified
    pdfToolsCmd: /opt/openoffice.org3/program/soffice
    openOfficeLocation: /opt/openoffice.org3/program
    pdfConverter: openoffice
    ## 水印图片路径
    imagePath: /images/logo/
    ## 水印字  恺思
    watermark: 恺思
    ## 水印字体大小
    watermarkFontsize: 20
    ## 水印横向间隔（A4）数目
    watermarkNumX: 2
    ## 水印纵向间隔（A4）数目
    watermarkNumY: 3
    ## 水印显示透明度
    watermarkFillOpacity: 0.3
    ## 水印显示倾斜角度
    watermarkRotation: 35
    ## 水印字体
    watermarkFontsizeForImage: 30
## 打印sql
logging:
  config: classpath:/log4j2-pro-ks.xml
server:
  port: ${sport:8090}