spring:
  application:
    name: matridx-bioinformation-server
  session:
    #session
    store-type: redis
    #
    timeout: 2000
  ## druid
  datasource:
    ##
    minIdle: 5
    ##
    maxActive: 100
    ##
    initialSize: 10
    ##
    maxWait: 60000
    ## Destroy2) testWhileIdle
    timeBetweenEvictionRunsMillis: 60000
    ##
    minEvictableIdleTimeMillis: 300000
    ##
    testWhileIdle: true
    ##
    testOnBorrow: false
    ##
    testOnReturn: false
    ##
    poolPreparedStatements: true
    ##
    maxPoolPreparedStatementPerConnectionSize: 100
      ## Druid
      #
    #
    #
    filters: config,stat,slf4j
    ##
    connectionProperties: 3000;
    ##
    useGlobalDataSourceStat: true
    ## druid
    druidLoginName: admin
    ## druid
    druidPassword: 1234
    ##
    removeAbandoned: true
    ##
    removeAbandonedTimeout: 180000
  thymeleaf:
    ##prefix: classpath*:/static/
    suffix: .html
    encoding: UTF-8
    cache: false
  ##
  cache:
    ehcache:
      config: classpath:config/ehcache/ehcache.xml
  redis:
    ## Redis
    database: 0
    url: ${rdburl:redis://Matridx_2022!@redis:6379}
    ## Redis
    #host: ${rdbhost:redis}
#    ## Redis
    #port: ${rdbport:6379}
#    ## Redis
    #password: ${rdbpass:Matridx_2022!}
    pool:
      ##
      max-active: 8
      ##
      max-wait: -1
      ##
      max-idle: 8
      ##
      min-idle: 0
    ##
    timeout: 5000
  ##spring boot
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  ##
  rabbitmq:
    host: ${mqhost:172.17.60.190}
    #host: 101.69.228.218
    port: ${mqport:5672}
    username: ${mqname:admin}
    password: ${mqpass:matridx2019!}
    ##
    publisher-confirms: true
    #virtual-host: /
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    viewname:
    protocol: smtp
    username: 1
    password: 1
  smtp:
    auth: true
    starttls:
      enable: true
      required: true
postsql:
  datasource:
    driverClassName: org.postgresql.Driver
    username: ${dbuser:AEBrmFhq9gZ4Yeq+mogdzQ==}
    password: ${dbpass:DmnVklgEln/9NePegyMNig==}
    url: ${dburl:E6Bxa5hFXjN+sYdjKG06wAqfeQK7rfwXaPGZO5j0ihx5D+FWf9P4+oPwV0AJRB9Z}
    validationQuery: SELECT 1
druid:
  stat:
    ##
    slowSqlMillis: 3000
    mergeSql: true
security:
  oauth2:
    resource:
      #
      filter-order: 3
#
logging:
  level:
    com.matridx.server: debug
    com.matridx.igams: debug
##myibatis
sql:
  interceptor:
    pagesqlid: .*getPaged*.*
    dialect: postgresql
##0
matridx:
  operate:
    filePath: /file
    timeout: 5000
    insertTimeout: 10000
#    fileFiltering: dev,etc,home,opt,root,run,sys,usr,var,boot,proc,tmp,bin,sbin,lib,lib64,srv,lib32,libx32
    fileFiltering:
    dockerSock: ${dockerSock:/var/run/docker.sock}
  role:
    switch: 1
  basictype:
    file: config/comm/basicType.xml
  imptype:
    file: config/comm/config-import.xml
  exptype:
    file: config/comm/config-export.xml
    limit: 500
  fileupload:
    prefix:
    tempPath: /matridx/fileupload/temp/
    releasePath: /matridx/fileupload/release/
  file:
    ##
    exportFilePath: /matridx/download/
    ##
    pathPrefix:
    ##
    translimit: 5
  dingtalk:
    appkey:
    appsecret:
    agentid:
  ##
  aliyunSms:
    accessKeyId:
    accessSecret:
    signName:
    templateCode: SMS_170840387
  ftp:
    wordpath: /wordFile
    pdfpath: /pdfFile
    url: 172.17.60.184
    user: ftpuser
    pd: matridx
    port: 21
  systemflg:
    logourl: /images/logoIn-biology-b.png
    watermark:
    systemname:
    ## 1
    redisreset: 1
    ## 1
    sendrabbitmq: 0
  rabbitflg:
    ##    1product
    configflg: 0
    ##    1
    receiveflg: 0
server:
  port: ${port:8078}
    #ssl:
    #key-store: server.keystore
    #key-alias: tomcat
    #enabled: true
  #key-store-password: matridx2019
  #key-store-type: JKS