spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
## 打印sql
logging:
  level:
    com.matridx.igams.common.dao.post: debug
    com.matridx.bioinformation.dao.post: debug
    com.matridx.web.dao.post: debug